# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: check help install install-cuda install-dev install-no-deps install-pipx uninstall uninstall-pipx clean format test-format test-lint test-typecheck test-unit test-unit-verbose test-coverage test-complexity mutation mutation-report

PACKAGE_NAME ?= personal_assistant_dashboard

ifeq ($(OS),Windows_NT)
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/Scripts/python.exe
else
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/bin/python
endif

# Interpreter used to bootstrap the venv. Override in CI to pin the venv
# to the matrix Python (e.g. `make install-dev PY_SYS=python`) so CI
# doesn't fall back to the container's system python3.
PY_SYS ?= python3

$(info venv: $(VENV_DIR))

check: test-format test-lint test-typecheck test-unit test-coverage  ## Run format, lint, typecheck, test, coverage (default)

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

$(PYTHON):
	$(PY_SYS) -m venv $(VENV_DIR)

install: $(PYTHON)  ## Install package
	$(PYTHON) -m pip install .

install-dev: $(PYTHON)  ## Install in editable mode with dev deps
	$(PYTHON) -m pip install -e ".[dev]"

install-cuda: $(PYTHON)  ## Install with CUDA GPU acceleration deps
	$(PYTHON) -m pip install -e ".[cuda]"

install-no-deps: $(PYTHON)  ## Install in editable mode without dependencies
	$(PYTHON) -m pip install -e . --no-deps

uninstall: $(PYTHON)  ## Uninstall package
	$(PYTHON) -m pip uninstall -y $(PACKAGE_NAME)

clean:  ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev  ## Format code with black
	$(PYTHON) -m black $(PACKAGE_NAME) tests

test-format: install-dev  ## Check formatting without modifying files
	$(PYTHON) -m black --check $(PACKAGE_NAME) tests

test-lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 $(PACKAGE_NAME) tests

test-typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy $(PACKAGE_NAME)

test-unit: install-dev  ## Run pytest
	$(PYTHON) -m pytest

test-unit-verbose: install-dev  ## Run pytest with verbose output
	$(PYTHON) -m pytest -v

test-coverage: install-dev  ## Run pytest with coverage
	$(PYTHON) -m pytest --cov=$(PACKAGE_NAME) --cov-report=term

test-complexity: install-dev  ## Cyclomatic complexity check (xenon)
	$(PYTHON) -m xenon $(PACKAGE_NAME) --max-absolute B --max-modules B --max-average A

mutation: install-dev  ## Run mutation testing (not part of check — run in CI or on-demand)
	$(PYTHON) -m mutmut run --CI --paths-to-mutate "$(PACKAGE_NAME)"

mutation-report: $(PYTHON)  ## Show results of last mutation run
	$(PYTHON) -m mutmut results

# PROJECT_NAME is the distribution name from [project] name in pyproject.toml.
# This may differ from PACKAGE_NAME (the Python module name).
PROJECT_NAME ?= $(PACKAGE_NAME)

install-pipx:  ## Install globally via pipx
	python3 -m pipx install . --force

uninstall-pipx:  ## Uninstall global pipx install
	python3 -m pipx uninstall $(PROJECT_NAME)

-include make/run.mk
