# Generated By: Claude Code (Claude Opus 4.6)
"""Shared test fixtures and helpers for personal assistant tests."""

from __future__ import annotations

import subprocess
import urllib.request
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from personal_assistant_dashboard.state_repo import init_repo

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture(autouse=True)
def _block_subprocess(request: pytest.FixtureRequest) -> object:
    """Block subprocess globally unless marked as integration test."""
    # Allow subprocess for integration tests or when state_dir fixture is used
    if "integration" in request.keywords or "state_dir" in request.fixturenames:
        yield
        return

    def _blocked(*args: object, **kwargs: object) -> object:
        cmd = args[0] if args else kwargs.get("args", "?")
        raise RuntimeError(f"subprocess blocked by conftest: {cmd!r}. Mock it instead.")

    with (
        patch.object(subprocess, "run", side_effect=_blocked),
        patch.object(subprocess, "Popen", side_effect=_blocked),
        patch.object(subprocess, "call", side_effect=_blocked),
        patch.object(subprocess, "check_call", side_effect=_blocked),
        patch.object(subprocess, "check_output", side_effect=_blocked),
    ):
        yield


@pytest.fixture(autouse=True)
def _block_urlopen(request: pytest.FixtureRequest) -> object:
    """Block real HTTP calls globally.

    Any test that needs urlopen must patch it explicitly. This prevents
    a missed mock from reaching the network (or a local AgentPulse
    instance) during unit tests.
    """
    if "integration" in request.keywords:
        yield
        return

    def _blocked(*args: object, **kwargs: object) -> object:
        target = args[0] if args else kwargs.get("url", "?")
        raise RuntimeError(
            f"urllib.request.urlopen blocked by conftest: {target!r}. "
            "Patch it in the test."
        )

    with patch.object(urllib.request, "urlopen", side_effect=_blocked):
        yield


_PROJECT_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(autouse=True)
def _block_real_filesystem(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Prevent tests from writing outside tmp_path."""

    def _is_allowed(path: Path) -> bool:
        resolved = path.resolve()
        return str(resolved).startswith(str(tmp_path)) or str(resolved).startswith(
            str(_PROJECT_ROOT / ".venv")
        )

    def _guard(original):  # type: ignore[no-untyped-def]
        def guarded(self, *args, **kwargs):  # type: ignore[no-untyped-def]
            if not _is_allowed(self):
                raise PermissionError(f"Test tried to write outside tmp_path: {self}")
            return original(self, *args, **kwargs)

        return guarded

    for method in ("write_text", "write_bytes", "rename", "unlink", "rmdir"):
        monkeypatch.setattr(Path, method, _guard(getattr(Path, method)))


@pytest.fixture()
def state_dir(tmp_path: Path) -> Path:
    """Create and initialize a state repo in a temp directory.

    Tests using this fixture will allow subprocess calls for git operations.
    """
    repo = tmp_path / "pa-state"
    init_repo(path=repo)
    return repo


@pytest.fixture()
def gws_response() -> str:
    """Load the sample GWS calendar response."""
    return (FIXTURES_DIR / "gws_calendar_response.json").read_text()


def mock_subprocess_result(
    *,
    stdout: str = "",
    stderr: str = "",
    returncode: int = 0,
) -> MagicMock:
    """Create a mock subprocess.run result."""
    result = MagicMock()
    result.returncode = returncode
    result.stdout = stdout
    result.stderr = stderr
    return result
