# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for DPI detection and Tkinter scaling."""

from unittest.mock import MagicMock, patch

from personal_assistant_dashboard.dpi import (
    _screen_physical_dpi,
    _xft_dpi,
    apply_dpi_scaling,
    detect_scale_factor,
)


def _mock_root(*, screen_px=1920, screen_mm=508, tk_scaling=1.333):
    """Create a mock Tk root with screen metrics."""
    root = MagicMock()
    root.winfo_screenwidth.return_value = screen_px
    root.winfo_screenmmwidth.return_value = screen_mm
    root.tk.call.return_value = tk_scaling
    return root


class TestScreenPhysicalDpi:
    def test_normal_96dpi(self):
        root = _mock_root(screen_px=1920, screen_mm=508)  # ~96 DPI
        dpi = _screen_physical_dpi(root)
        assert dpi is not None
        assert abs(dpi - 96.0) < 1.0

    def test_hidpi_192dpi(self):
        root = _mock_root(screen_px=3840, screen_mm=508)  # ~192 DPI
        dpi = _screen_physical_dpi(root)
        assert dpi is not None
        assert abs(dpi - 192.0) < 1.0

    def test_zero_mm_returns_none(self):
        root = _mock_root(screen_mm=0)
        assert _screen_physical_dpi(root) is None

    def test_exception_returns_none(self):
        root = MagicMock()
        root.winfo_screenmmwidth.side_effect = RuntimeError("no display")
        assert _screen_physical_dpi(root) is None


class TestXftDpi:
    @patch("personal_assistant_dashboard.dpi.subprocess.run")
    def test_parses_xft_dpi(self, mock_run):
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout="Xft.dpi:\t192\n",
        )
        assert _xft_dpi() == 192.0

    @patch("personal_assistant_dashboard.dpi.subprocess.run")
    def test_no_xft_dpi_returns_none(self, mock_run):
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout="Xft.antialias:\t1\n",
        )
        assert _xft_dpi() is None

    @patch("personal_assistant_dashboard.dpi.subprocess.run")
    def test_xrdb_failure_returns_none(self, mock_run):
        mock_run.return_value = MagicMock(returncode=1, stdout="")
        assert _xft_dpi() is None

    @patch("personal_assistant_dashboard.dpi.subprocess.run")
    def test_xrdb_not_found_returns_none(self, mock_run):
        mock_run.side_effect = FileNotFoundError("xrdb not found")
        assert _xft_dpi() is None


class TestDetectScaleFactor:
    @patch.dict("os.environ", {}, clear=True)
    @patch("personal_assistant_dashboard.dpi.sys.platform", "darwin")
    def test_non_linux_returns_1(self):
        root = _mock_root()
        assert detect_scale_factor(root) == 1.0

    @patch.dict("os.environ", {"PA_DASHBOARD_SCALE": "1.5"})
    def test_env_var_override(self):
        root = _mock_root()
        assert detect_scale_factor(root) == 1.5

    @patch.dict("os.environ", {"PA_DASHBOARD_SCALE": "not-a-number"})
    @patch("personal_assistant_dashboard.dpi.sys.platform", "linux")
    @patch("personal_assistant_dashboard.dpi._screen_physical_dpi", return_value=None)
    @patch("personal_assistant_dashboard.dpi._xft_dpi", return_value=None)
    def test_invalid_env_var_falls_through(self, _xft, _screen):
        root = _mock_root()
        assert detect_scale_factor(root) == 1.0

    @patch.dict("os.environ", {}, clear=True)
    @patch("personal_assistant_dashboard.dpi.sys.platform", "linux")
    @patch("personal_assistant_dashboard.dpi._screen_physical_dpi", return_value=192.0)
    @patch("personal_assistant_dashboard.dpi._xft_dpi", return_value=None)
    def test_hidpi_screen_triggers_scaling(self, _xft, _screen):
        root = _mock_root(tk_scaling=1.333)  # 96 DPI
        factor = detect_scale_factor(root)
        assert factor == 2.0

    @patch.dict("os.environ", {}, clear=True)
    @patch("personal_assistant_dashboard.dpi.sys.platform", "linux")
    @patch("personal_assistant_dashboard.dpi._screen_physical_dpi", return_value=96.0)
    @patch("personal_assistant_dashboard.dpi._xft_dpi", return_value=None)
    def test_normal_dpi_no_scaling(self, _xft, _screen):
        root = _mock_root(tk_scaling=1.333)
        assert detect_scale_factor(root) == 1.0

    @patch.dict("os.environ", {}, clear=True)
    @patch("personal_assistant_dashboard.dpi.sys.platform", "linux")
    @patch("personal_assistant_dashboard.dpi._screen_physical_dpi", return_value=None)
    @patch("personal_assistant_dashboard.dpi._xft_dpi", return_value=192.0)
    def test_xft_dpi_fallback(self, _xft, _screen):
        root = _mock_root(tk_scaling=1.333)
        factor = detect_scale_factor(root)
        assert factor == 2.0

    @patch.dict("os.environ", {}, clear=True)
    @patch("personal_assistant_dashboard.dpi.sys.platform", "linux")
    @patch("personal_assistant_dashboard.dpi._screen_physical_dpi", return_value=None)
    @patch("personal_assistant_dashboard.dpi._xft_dpi", return_value=None)
    def test_no_data_returns_1(self, _xft, _screen):
        root = _mock_root()
        assert detect_scale_factor(root) == 1.0

    @patch.dict("os.environ", {}, clear=True)
    @patch("personal_assistant_dashboard.dpi.sys.platform", "linux")
    @patch("personal_assistant_dashboard.dpi._screen_physical_dpi", return_value=110.0)
    @patch("personal_assistant_dashboard.dpi._xft_dpi", return_value=None)
    def test_below_threshold_no_scaling(self, _xft, _screen):
        """DPI just slightly above baseline should not trigger scaling."""
        root = _mock_root(tk_scaling=1.333)
        assert detect_scale_factor(root) == 1.0


class TestApplyDpiScaling:
    def test_override_applied(self):
        root = _mock_root(tk_scaling=1.333)
        factor = apply_dpi_scaling(root, override=2.0)
        assert factor == 2.0
        root.tk.call.assert_any_call("tk", "scaling", 1.333 * 2.0)

    def test_near_unity_skipped(self):
        root = _mock_root(tk_scaling=1.333)
        factor = apply_dpi_scaling(root, override=1.02)
        assert factor == 1.0

    @patch("personal_assistant_dashboard.dpi.detect_scale_factor", return_value=1.5)
    def test_auto_detect_applied(self, _detect):
        root = _mock_root(tk_scaling=1.333)
        factor = apply_dpi_scaling(root)
        assert factor == 1.5
        root.tk.call.assert_any_call("tk", "scaling", 1.333 * 1.5)

    @patch("personal_assistant_dashboard.dpi.detect_scale_factor", return_value=1.0)
    def test_no_scaling_needed(self, _detect):
        root = _mock_root(tk_scaling=1.333)
        factor = apply_dpi_scaling(root)
        assert factor == 1.0
