# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for _fetch_incoming_change_requests."""

import json
from unittest.mock import patch

from personal_assistant_dashboard.prs_tab import (
    _fetch_incoming_change_requests,
)


def _pr(number: int, repo: str = "org/repo") -> dict:
    return {
        "html_url": f"https://github.com/{repo}/pull/{number}",
        "repository_url": f"https://api.github.com/repos/{repo}",
        "number": number,
    }


def _mock_reviews(*review_states: list[tuple[str, str]]):
    """Return a side_effect fn for run_cmd. Each arg is [(login, state), ...]."""
    call_idx = {"i": 0}

    def side_effect(cmd, **kwargs):
        i = call_idx["i"]
        call_idx["i"] += 1
        if i < len(review_states):
            reviews = [
                {"user": {"login": login}, "state": state}
                for login, state in review_states[i]
            ]
            return type(
                "R",
                (),
                {
                    "returncode": 0,
                    "stdout": json.dumps(reviews),
                },
            )()
        return type("R", (), {"returncode": 1, "stdout": "", "stderr": ""})()

    return side_effect


@patch("personal_assistant_dashboard.prs_tab.run_cmd")
def test_single_reviewer_changes_requested(mock_cmd):
    mock_cmd.side_effect = _mock_reviews([("alice", "CHANGES_REQUESTED")])
    result = _fetch_incoming_change_requests([_pr(1)])
    assert result == {"https://github.com/org/repo/pull/1": 1}


@patch("personal_assistant_dashboard.prs_tab.run_cmd")
def test_reviewer_approved_after_changes_requested(mock_cmd):
    mock_cmd.side_effect = _mock_reviews(
        [("alice", "CHANGES_REQUESTED"), ("alice", "APPROVED")]
    )
    result = _fetch_incoming_change_requests([_pr(1)])
    assert result == {"https://github.com/org/repo/pull/1": 0}


@patch("personal_assistant_dashboard.prs_tab.run_cmd")
def test_multiple_reviewers_mixed(mock_cmd):
    mock_cmd.side_effect = _mock_reviews(
        [
            ("alice", "CHANGES_REQUESTED"),
            ("bob", "APPROVED"),
            ("carol", "CHANGES_REQUESTED"),
        ]
    )
    result = _fetch_incoming_change_requests([_pr(1)])
    assert result == {"https://github.com/org/repo/pull/1": 2}


@patch("personal_assistant_dashboard.prs_tab.run_cmd")
def test_no_decision_reviews(mock_cmd):
    mock_cmd.side_effect = _mock_reviews([("alice", "COMMENTED")])
    result = _fetch_incoming_change_requests([_pr(1)])
    assert result == {"https://github.com/org/repo/pull/1": 0}


@patch("personal_assistant_dashboard.prs_tab.run_cmd")
def test_all_approved(mock_cmd):
    mock_cmd.side_effect = _mock_reviews([("alice", "APPROVED"), ("bob", "APPROVED")])
    result = _fetch_incoming_change_requests([_pr(1)])
    assert result == {"https://github.com/org/repo/pull/1": 0}
