# Generated By: Claude Code (Claude Opus 5)
"""Test label-star -> PR-star matching."""

from personal_assistant_dashboard.prs_tab import _label_starred_urls

PRS = [
    {"html_url": "u1", "labels": [{"name": "urgent"}, {"name": "bug"}]},
    {"html_url": "u2", "labels": [{"name": "bug"}]},
    {"html_url": "u3", "labels": []},
    {"html_url": "u4"},
    {"labels": [{"name": "urgent"}]},
]


def test_matches_any_starred_label():
    assert _label_starred_urls(PRS, {"urgent"}) == {"u1"}
    assert _label_starred_urls(PRS, {"bug"}) == {"u1", "u2"}
    assert _label_starred_urls(PRS, {"urgent", "bug"}) == {"u1", "u2"}


def test_no_starred_labels():
    assert _label_starred_urls(PRS, set()) == set()


def test_unknown_label():
    assert _label_starred_urls(PRS, {"nope"}) == set()
