# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for pages_tab dirty-file tracking and helper functions."""

from __future__ import annotations

import pytest

from personal_assistant_dashboard.pages_tab import (
    _DIRTY_PREFIX,
    _format_age,
    _strip_dirty,
)


# --- _format_age ---


class TestFormatAge:
    def test_seconds(self) -> None:
        assert _format_age(30) == "30s ago"

    def test_minutes(self) -> None:
        assert _format_age(120) == "2m ago"

    def test_hours_and_minutes(self) -> None:
        assert _format_age(3720) == "1h 2m ago"

    def test_days(self) -> None:
        assert _format_age(90000) == "1d ago"

    def test_zero(self) -> None:
        assert _format_age(0) == "0s ago"

    def test_boundary_59(self) -> None:
        assert _format_age(59) == "59s ago"

    def test_boundary_60(self) -> None:
        assert _format_age(60) == "1m ago"


# --- _strip_dirty ---


class TestStripDirty:
    def test_strips_prefix(self) -> None:
        assert _strip_dirty("* plan.html") == "plan.html"

    def test_no_prefix(self) -> None:
        assert _strip_dirty("plan.html") == "plan.html"

    def test_empty_string(self) -> None:
        assert _strip_dirty("") == ""

    def test_only_prefix(self) -> None:
        assert _strip_dirty("* ") == ""

    def test_does_not_strip_single_star(self) -> None:
        assert _strip_dirty("*plan.html") == "*plan.html"

    def test_preserves_inner_star(self) -> None:
        assert _strip_dirty("my * file.html") == "my * file.html"

    def test_prefix_constant_is_star_space(self) -> None:
        assert _DIRTY_PREFIX == "* "


# --- Dirty file display logic ---


class TestDirtyDisplay:
    """Test the display name generation logic used by _refresh_file_list."""

    @staticmethod
    def _make_display(names: list[str], dirty: set[str]) -> list[str]:
        """Replicate the display name logic from _refresh_file_list."""
        return [f"{_DIRTY_PREFIX}{n}" if n in dirty else n for n in names]

    def test_no_dirty_files(self) -> None:
        names = ["a.html", "b.html"]
        assert self._make_display(names, set()) == ["a.html", "b.html"]

    def test_one_dirty_file(self) -> None:
        names = ["a.html", "b.html", "c.html"]
        dirty = {"b.html"}
        result = self._make_display(names, dirty)
        assert result == ["a.html", "* b.html", "c.html"]

    def test_all_dirty(self) -> None:
        names = ["a.html", "b.html"]
        dirty = {"a.html", "b.html"}
        result = self._make_display(names, dirty)
        assert result == ["* a.html", "* b.html"]

    def test_dirty_file_not_in_names(self) -> None:
        names = ["a.html"]
        dirty = {"gone.html"}
        result = self._make_display(names, dirty)
        assert result == ["a.html"]

    def test_round_trip_strip(self) -> None:
        """Display name with prefix round-trips through _strip_dirty."""
        display = f"{_DIRTY_PREFIX}plan.html"
        assert _strip_dirty(display) == "plan.html"


# --- Dirty file set operations ---


class TestDirtyFileTracking:
    """Test the dirty file set operations used by PagesTab."""

    def test_discard_clears_file(self) -> None:
        dirty: set[str] = {"a.html", "b.html"}
        dirty.discard("a.html")
        assert dirty == {"b.html"}

    def test_discard_nonexistent_is_safe(self) -> None:
        dirty: set[str] = {"a.html"}
        dirty.discard("z.html")
        assert dirty == {"a.html"}

    def test_clear_empties_set(self) -> None:
        dirty: set[str] = {"a.html", "b.html", "c.html"}
        dirty.clear()
        assert dirty == set()

    def test_add_on_mtime_change(self) -> None:
        """Simulate _poll_files adding dirty files on mtime change."""
        dirty: set[str] = set()
        old_mtimes = {"a.html": 100.0, "b.html": 200.0}
        new_mtimes = {"a.html": 100.0, "b.html": 300.0}  # b changed

        for name, mtime in new_mtimes.items():
            old = old_mtimes.get(name, 0.0)
            if old != 0.0 and mtime != old:
                dirty.add(name)

        assert dirty == {"b.html"}

    def test_multiple_changes_accumulate(self) -> None:
        """Dirty files accumulate across polls until cleared."""
        dirty: set[str] = set()

        # First poll: b changes
        dirty.add("b.html")
        # Second poll: a changes
        dirty.add("a.html")

        assert dirty == {"a.html", "b.html"}

        # User selects a.html
        dirty.discard("a.html")
        assert dirty == {"b.html"}

        # User selects b.html
        dirty.discard("b.html")
        assert dirty == set()
