# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for calendar_analyzer module."""

import json
from pathlib import Path

import pytest

from personal_assistant.analyzers.calendar_analyzer import (
    CalendarAnalysis,
    CalendarChange,
    Conflict,
    analyze_calendar,
    format_analysis,
    _detect_conflicts,
    _parse_event_time,
    _user_declined,
)
from personal_assistant.state_repo import commit_state, init_repo

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture()
def state_dir(tmp_path: Path) -> Path:
    """Create and initialize a state repo."""
    repo = tmp_path / "pa-state"
    init_repo(path=repo)
    return repo


def _write_events(
    state_dir: Path, events: list, filename: str = "calendar/events.json"
) -> None:
    """Write events to the state repo."""
    filepath = state_dir / filename
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w") as f:
        json.dump(events, f)


def _load_fixture(name: str) -> list:
    """Load a test fixture file."""
    return json.loads((FIXTURES_DIR / name).read_text())


def test_analyze_no_previous(state_dir: Path) -> None:
    after = _load_fixture("calendar_after.json")
    _write_events(state_dir, after)

    analysis = analyze_calendar(repo_path=state_dir)
    # All events are "new" since there's no previous commit
    assert analysis.current_event_count == 3
    assert analysis.previous_event_count == 0
    new_changes = [c for c in analysis.changes if c.change_type == "new"]
    assert len(new_changes) == 3


def test_analyze_detects_new_events(state_dir: Path) -> None:
    before = _load_fixture("calendar_before.json")
    _write_events(state_dir, before)
    commit_state("baseline", repo_path=state_dir)

    after = _load_fixture("calendar_after.json")
    _write_events(state_dir, after)

    analysis = analyze_calendar(repo_path=state_dir)
    new_changes = [c for c in analysis.changes if c.change_type == "new"]
    assert len(new_changes) == 1
    assert new_changes[0].event["id"] == "event-new"


def test_analyze_detects_cancelled_events(state_dir: Path) -> None:
    before = _load_fixture("calendar_before.json")
    _write_events(state_dir, before)
    commit_state("baseline", repo_path=state_dir)

    after = _load_fixture("calendar_after.json")
    _write_events(state_dir, after)

    analysis = analyze_calendar(repo_path=state_dir)
    cancelled = [c for c in analysis.changes if c.change_type == "cancelled"]
    assert len(cancelled) == 1
    assert cancelled[0].event["id"] == "event-old"


def test_analyze_detects_time_change(state_dir: Path) -> None:
    before = _load_fixture("calendar_before.json")
    _write_events(state_dir, before)
    commit_state("baseline", repo_path=state_dir)

    after = _load_fixture("calendar_after.json")
    _write_events(state_dir, after)

    analysis = analyze_calendar(repo_path=state_dir)
    moved = [c for c in analysis.changes if c.change_type == "time_changed"]
    assert len(moved) == 1
    assert moved[0].event["id"] == "event-001"
    assert "09:00" in moved[0].detail
    assert "09:30" in moved[0].detail


def test_analyze_detects_attendee_changes(state_dir: Path) -> None:
    before = _load_fixture("calendar_before.json")
    _write_events(state_dir, before)
    commit_state("baseline", repo_path=state_dir)

    after = _load_fixture("calendar_after.json")
    _write_events(state_dir, after)

    analysis = analyze_calendar(repo_path=state_dir)
    attendee_changes = [
        c for c in analysis.changes if c.change_type == "attendees_changed"
    ]
    assert len(attendee_changes) == 1
    assert "dev2@example.com" in attendee_changes[0].detail


def test_analyze_no_changes(state_dir: Path) -> None:
    events = _load_fixture("calendar_before.json")
    _write_events(state_dir, events)
    commit_state("baseline", repo_path=state_dir)

    # Write same events again
    _write_events(state_dir, events)

    analysis = analyze_calendar(repo_path=state_dir)
    assert len(analysis.changes) == 0


def test_detect_conflicts_overlapping() -> None:
    events = [
        {
            "id": "a",
            "summary": "Meeting A",
            "start": "2026-03-30T09:00:00-04:00",
            "end": "2026-03-30T10:00:00-04:00",
            "status": "confirmed",
            "attendees": [
                {"email": "me@x.com", "self": True, "response_status": "accepted"}
            ],
        },
        {
            "id": "b",
            "summary": "Meeting B",
            "start": "2026-03-30T09:30:00-04:00",
            "end": "2026-03-30T10:30:00-04:00",
            "status": "confirmed",
            "attendees": [
                {"email": "me@x.com", "self": True, "response_status": "accepted"}
            ],
        },
    ]
    conflicts = _detect_conflicts(events)
    assert len(conflicts) == 1


def test_detect_conflicts_no_overlap() -> None:
    events = [
        {
            "id": "a",
            "summary": "Meeting A",
            "start": "2026-03-30T09:00:00-04:00",
            "end": "2026-03-30T10:00:00-04:00",
            "status": "confirmed",
            "attendees": [],
        },
        {
            "id": "b",
            "summary": "Meeting B",
            "start": "2026-03-30T10:00:00-04:00",
            "end": "2026-03-30T11:00:00-04:00",
            "status": "confirmed",
            "attendees": [],
        },
    ]
    conflicts = _detect_conflicts(events)
    assert len(conflicts) == 0


def test_detect_conflicts_declined_excluded() -> None:
    events = [
        {
            "id": "a",
            "summary": "Meeting A",
            "start": "2026-03-30T09:00:00-04:00",
            "end": "2026-03-30T10:00:00-04:00",
            "status": "confirmed",
            "attendees": [
                {"email": "me@x.com", "self": True, "response_status": "accepted"}
            ],
        },
        {
            "id": "b",
            "summary": "Meeting B",
            "start": "2026-03-30T09:30:00-04:00",
            "end": "2026-03-30T10:30:00-04:00",
            "status": "confirmed",
            "attendees": [
                {"email": "me@x.com", "self": True, "response_status": "declined"}
            ],
        },
    ]
    conflicts = _detect_conflicts(events)
    assert len(conflicts) == 0


def test_parse_event_time_datetime() -> None:
    result = _parse_event_time("2026-03-30T09:00:00-04:00")
    assert result is not None
    assert result.hour == 9


def test_parse_event_time_date_only() -> None:
    result = _parse_event_time("2026-03-30")
    assert result is not None
    assert result.year == 2026


def test_parse_event_time_empty() -> None:
    assert _parse_event_time("") is None


def test_format_analysis_no_changes() -> None:
    analysis = CalendarAnalysis(
        calendar_file="calendar/events.json",
        current_event_count=5,
        previous_event_count=5,
    )
    output = format_analysis(analysis)
    assert "No changes detected" in output


def test_format_analysis_with_changes() -> None:
    analysis = CalendarAnalysis(
        calendar_file="calendar/events.json",
        current_event_count=3,
        previous_event_count=2,
        changes=[
            CalendarChange(
                change_type="new",
                event={"summary": "New Meeting", "start": "2026-03-30T10:00:00-04:00"},
                detail="New: New Meeting at 2026-03-30T10:00:00-04:00",
            )
        ],
        conflicts=[
            Conflict(
                event_a={
                    "summary": "A",
                    "start": "2026-03-30T09:00:00-04:00",
                },
                event_b={
                    "summary": "B",
                    "start": "2026-03-30T09:30:00-04:00",
                },
            )
        ],
    )
    output = format_analysis(analysis)
    assert "New Meeting" in output
    assert "Changes" in output
    assert "Conflicts" in output
    assert "overlaps" in output


def test_user_declined_true() -> None:
    event = {
        "attendees": [
            {"email": "me@x.com", "self": True, "response_status": "declined"}
        ]
    }
    assert _user_declined(event) is True


def test_user_declined_false() -> None:
    event = {
        "attendees": [
            {"email": "me@x.com", "self": True, "response_status": "accepted"}
        ]
    }
    assert _user_declined(event) is False


def test_user_declined_no_attendees() -> None:
    assert _user_declined({"attendees": []}) is False
    assert _user_declined({}) is False


def test_analyze_skips_declined_new_events(state_dir: Path) -> None:
    """New events the user declined should not appear as changes."""
    _write_events(state_dir, [])
    commit_state("empty baseline", repo_path=state_dir)

    _write_events(
        state_dir,
        [
            {
                "id": "accepted-event",
                "summary": "Accepted Meeting",
                "start": "2026-03-30T09:00:00-04:00",
                "end": "2026-03-30T10:00:00-04:00",
                "all_day": False,
                "status": "confirmed",
                "attendees": [
                    {
                        "email": "me@x.com",
                        "self": True,
                        "response_status": "accepted",
                    }
                ],
            },
            {
                "id": "declined-event",
                "summary": "Declined Meeting",
                "start": "2026-03-30T11:00:00-04:00",
                "end": "2026-03-30T12:00:00-04:00",
                "all_day": False,
                "status": "confirmed",
                "attendees": [
                    {
                        "email": "me@x.com",
                        "self": True,
                        "response_status": "declined",
                    }
                ],
            },
        ],
    )

    analysis = analyze_calendar(repo_path=state_dir)
    new_changes = [c for c in analysis.changes if c.change_type == "new"]
    assert len(new_changes) == 1
    assert new_changes[0].event["id"] == "accepted-event"


def test_analyze_skips_declined_cancelled_events(state_dir: Path) -> None:
    """Cancellation of a declined event should not appear as a change."""
    before = [
        {
            "id": "declined-event",
            "summary": "Declined Meeting",
            "start": "2026-03-30T11:00:00-04:00",
            "end": "2026-03-30T12:00:00-04:00",
            "all_day": False,
            "status": "confirmed",
            "attendees": [
                {
                    "email": "me@x.com",
                    "self": True,
                    "response_status": "declined",
                }
            ],
        },
    ]
    _write_events(state_dir, before)
    commit_state("baseline", repo_path=state_dir)

    _write_events(state_dir, [])  # event removed

    analysis = analyze_calendar(repo_path=state_dir)
    cancelled = [c for c in analysis.changes if c.change_type == "cancelled"]
    assert len(cancelled) == 0


def test_analyze_skips_declined_time_changes(state_dir: Path) -> None:
    """Time changes on declined events should not appear as changes."""
    before = [
        {
            "id": "declined-event",
            "summary": "Declined Meeting",
            "start": "2026-03-30T11:00:00-04:00",
            "end": "2026-03-30T12:00:00-04:00",
            "all_day": False,
            "status": "confirmed",
            "attendees": [
                {
                    "email": "me@x.com",
                    "self": True,
                    "response_status": "declined",
                }
            ],
        },
    ]
    _write_events(state_dir, before)
    commit_state("baseline", repo_path=state_dir)

    after = [
        {
            "id": "declined-event",
            "summary": "Declined Meeting",
            "start": "2026-03-30T14:00:00-04:00",
            "end": "2026-03-30T15:00:00-04:00",
            "all_day": False,
            "status": "confirmed",
            "attendees": [
                {
                    "email": "me@x.com",
                    "self": True,
                    "response_status": "declined",
                }
            ],
        },
    ]
    _write_events(state_dir, after)

    analysis = analyze_calendar(repo_path=state_dir)
    assert len(analysis.changes) == 0
