# Generated By: Claude Code (Claude Opus 5 (1M context))
"""Tests for the actions.md parser and write-back."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from personal_assistant_dashboard.tasks_md import (
    Task,
    bump_target,
    first_url,
    move_task,
    parse_section_date,
    parse_tasks,
    section_title,
    set_done,
    shift_business_day,
    split_links,
)

SAMPLE = (
    "# Actions\n"
    "\n"
    "## Overdue\n"
    "- [ ] File the expense report\n"
    "\n"
    "## Demos to watch\n"
    "- Watch [Q3 demo](https://drive.example/q3) before Friday\n"
    "  - runs 20 min\n"
    "  - slides attached\n"
    "* [x] Old demo at https://drive.example/old\n"
)


def test_parses_bullets_with_and_without_checkboxes() -> None:
    tasks = parse_tasks(SAMPLE)
    assert [t.text for t in tasks] == [
        "File the expense report",
        "Watch [Q3 demo](https://drive.example/q3) before Friday",
        "Old demo at https://drive.example/old",
    ]
    assert [t.done for t in tasks] == [False, False, True]


def test_sections_come_from_headings() -> None:
    assert [t.section for t in parse_tasks(SAMPLE)] == [
        "Overdue",
        "Demos to watch",
        "Demos to watch",
    ]


def test_indented_bullets_become_detail() -> None:
    tasks = parse_tasks(SAMPLE)
    assert tasks[1].detail == ["runs 20 min", "slides attached"]
    assert tasks[0].detail == []


def test_bullets_before_any_heading_have_empty_section() -> None:
    assert parse_tasks("- lone item\n")[0].section == ""


def test_key_ignores_section_so_moved_tasks_do_not_realert() -> None:
    overdue = parse_tasks("## Overdue\n- Ping Bob\n")[0]
    today = parse_tasks("## 2026-08-21 (TODAY)\n- Ping Bob\n")[0]
    assert overdue.key == today.key


def test_split_links_handles_markdown_and_bare_urls() -> None:
    assert split_links("see [demo](https://a/b) now") == [
        ("see ", ""),
        ("demo", "https://a/b"),
        (" now", ""),
    ]
    assert split_links("go to https://a/b now") == [
        ("go to ", ""),
        ("https://a/b", "https://a/b"),
        (" now", ""),
    ]
    assert split_links("no links here") == [("no links here", "")]


def test_first_url_falls_back_to_detail_lines() -> None:
    task = Task(line=0, text="Watch it", done=False, section="", detail=["https://a/b"])
    assert first_url(task) == "https://a/b"
    assert first_url(Task(line=0, text="plain", done=False, section="")) == ""


def test_set_done_rewrites_only_the_target_line(tmp_path: Path) -> None:
    path = tmp_path / "actions.md"
    path.write_text(SAMPLE, encoding="utf-8")
    tasks = parse_tasks(SAMPLE)

    assert set_done(path, tasks[1], True)
    after = path.read_text(encoding="utf-8")
    assert "- [x] Watch [Q3 demo](https://drive.example/q3) before Friday" in after
    # Every other line survives untouched.
    assert after.splitlines()[3] == "- [ ] File the expense report"
    assert after.splitlines()[7] == "  - runs 20 min"
    assert after.endswith("\n")


def test_set_done_preserves_bullet_marker(tmp_path: Path) -> None:
    path = tmp_path / "actions.md"
    path.write_text(SAMPLE, encoding="utf-8")
    tasks = parse_tasks(SAMPLE)
    assert set_done(path, tasks[2], False)
    assert "* [ ] Old demo at https://drive.example/old" in path.read_text(
        encoding="utf-8"
    )


def test_set_done_refuses_when_the_line_moved(tmp_path: Path) -> None:
    path = tmp_path / "actions.md"
    path.write_text(SAMPLE, encoding="utf-8")
    stale = Task(line=3, text="Something the PA deleted", done=False, section="")
    assert not set_done(path, stale, True)
    assert path.read_text(encoding="utf-8") == SAMPLE


def test_set_done_refuses_past_end_of_file(tmp_path: Path) -> None:
    path = tmp_path / "actions.md"
    path.write_text(SAMPLE, encoding="utf-8")
    stale = Task(line=999, text="gone", done=False, section="")
    assert not set_done(path, stale, True)


# --- date bumping -------------------------------------------------------

DATED = (
    "# Actions\n"
    "\n"
    "## Overdue\n"
    "\n"
    "- [ ] File the expense report\n"
    "\n"
    "## 2026-08-21 (TODAY)\n"
    "\n"
    "- [ ] Prep talking points\n"
    "\n"
    "## 2026-08-25\n"
    "\n"
    "- [ ] Ship the thing\n"
    "\n"
    "## Unscheduled\n"
    "\n"
    "- [ ] Draft the rotation proposal\n"
)
FRIDAY = date(2026, 8, 21)


def test_parse_section_date_ignores_today_marker() -> None:
    assert parse_section_date("2026-08-21 (TODAY)") == date(2026, 8, 21)
    assert parse_section_date("2026-08-25") == date(2026, 8, 25)
    assert parse_section_date("Overdue") is None
    assert parse_section_date("Demos to watch") is None
    assert parse_section_date("2026-13-45") is None


def test_shift_business_day_skips_the_weekend() -> None:
    assert shift_business_day(date(2026, 8, 21), 1) == date(2026, 8, 24)  # Fri->Mon
    assert shift_business_day(date(2026, 8, 24), -1) == date(2026, 8, 21)  # Mon->Fri
    assert shift_business_day(date(2026, 8, 20), 1) == date(2026, 8, 21)  # Thu->Fri


def test_bump_target_named_bucket_can_only_go_to_today() -> None:
    assert bump_target("Overdue", 1, FRIDAY) == FRIDAY
    assert bump_target("Overdue", -1, FRIDAY) is None
    assert bump_target("Demos to watch", 1, FRIDAY) == FRIDAY
    assert bump_target("Demos to watch", -1, FRIDAY) is None


def test_bump_target_floors_at_today() -> None:
    assert bump_target("2026-08-21 (TODAY)", -1, FRIDAY) is None
    assert bump_target("2026-08-24", -1, FRIDAY) == FRIDAY
    # A stale past date behaves like Overdue.
    assert bump_target("2026-08-19", -1, FRIDAY) is None
    assert bump_target("2026-08-19", 1, FRIDAY) == FRIDAY


def test_bump_target_down_walks_business_days() -> None:
    assert bump_target("2026-08-21 (TODAY)", 1, FRIDAY) == date(2026, 8, 24)
    assert bump_target("2026-08-25", 1, FRIDAY) == date(2026, 8, 26)


def test_section_title_marks_today() -> None:
    assert section_title(FRIDAY, FRIDAY) == "2026-08-21 (TODAY)"
    assert section_title(date(2026, 8, 25), FRIDAY) == "2026-08-25"


def _write(tmp_path: Path, content: str) -> Path:
    path = tmp_path / "actions.md"
    path.write_text(content, encoding="utf-8")
    return path


def test_move_into_an_existing_section(tmp_path: Path) -> None:
    path = _write(tmp_path, DATED)
    task = parse_tasks(DATED)[0]  # the Overdue one
    assert move_task(path, task, FRIDAY, today=FRIDAY)
    moved = parse_tasks(path.read_text(encoding="utf-8"))
    assert [(t.text, t.section) for t in moved] == [
        ("Prep talking points", "2026-08-21 (TODAY)"),
        ("File the expense report", "2026-08-21 (TODAY)"),
        ("Ship the thing", "2026-08-25"),
        ("Draft the rotation proposal", "Unscheduled"),
    ]
    # Overdue is a named bucket — it stays even when emptied.
    assert "## Overdue" in path.read_text(encoding="utf-8")


def test_move_creates_the_section_in_date_order(tmp_path: Path) -> None:
    path = _write(tmp_path, DATED)
    task = parse_tasks(DATED)[1]  # today's task
    assert move_task(path, task, date(2026, 8, 24), today=FRIDAY)
    after = path.read_text(encoding="utf-8")
    headings = [ln for ln in after.splitlines() if ln.startswith("## ")]
    assert headings == [
        "## Overdue",
        "## 2026-08-24",
        "## 2026-08-25",
        "## Unscheduled",
    ], headings
    # The emptied date section is gone, the named ones are not.
    assert "2026-08-21" not in after


def test_new_section_sorts_above_named_buckets(tmp_path: Path) -> None:
    path = _write(tmp_path, DATED)
    task = parse_tasks(DATED)[3]  # Unscheduled
    assert move_task(path, task, date(2026, 8, 28), today=FRIDAY)
    headings = [
        ln
        for ln in path.read_text(encoding="utf-8").splitlines()
        if ln.startswith("## ")
    ]
    assert headings == [
        "## Overdue",
        "## 2026-08-21 (TODAY)",
        "## 2026-08-25",
        "## 2026-08-28",
        "## Unscheduled",
    ], headings


def test_move_carries_detail_lines(tmp_path: Path) -> None:
    content = (
        "## Overdue\n"
        "\n"
        "- Watch the demo\n"
        "  - runs 20 min\n"
        "  - skip to 04:30\n"
        "- Something else\n"
    )
    path = _write(tmp_path, content)
    task = parse_tasks(content)[0]
    assert move_task(path, task, FRIDAY, today=FRIDAY)
    moved = parse_tasks(path.read_text(encoding="utf-8"))
    watch = next(t for t in moved if t.text == "Watch the demo")
    assert watch.section == "2026-08-21 (TODAY)"
    assert watch.detail == ["runs 20 min", "skip to 04:30"]
    assert next(t for t in moved if t.text == "Something else").section == "Overdue"


def test_move_marks_todays_new_section(tmp_path: Path) -> None:
    content = "## Unscheduled\n\n- Draft the proposal\n"
    path = _write(tmp_path, content)
    assert move_task(path, parse_tasks(content)[0], FRIDAY, today=FRIDAY)
    assert "## 2026-08-21 (TODAY)" in path.read_text(encoding="utf-8")


def test_move_refuses_when_the_line_moved(tmp_path: Path) -> None:
    path = _write(tmp_path, DATED)
    stale = Task(line=4, text="Not this task", done=False, section="Overdue")
    assert not move_task(path, stale, FRIDAY, today=FRIDAY)
    assert path.read_text(encoding="utf-8") == DATED


def test_move_keeps_the_file_reparseable(tmp_path: Path) -> None:
    """Repeated bumps must not corrupt structure or duplicate lines."""
    path = _write(tmp_path, DATED)
    for target in (date(2026, 8, 24), date(2026, 8, 25), FRIDAY, date(2026, 8, 26)):
        task = parse_tasks(path.read_text(encoding="utf-8"))[0]
        assert move_task(path, task, target, today=FRIDAY)
    texts = sorted(t.text for t in parse_tasks(path.read_text(encoding="utf-8")))
    assert texts == [
        "Draft the rotation proposal",
        "File the expense report",
        "Prep talking points",
        "Ship the thing",
    ], texts
    assert "\n\n\n" not in path.read_text(encoding="utf-8")
