# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for calendar_collector module."""

import json
from pathlib import Path
from unittest.mock import patch

import pytest

from personal_assistant.collectors.calendar_collector import (
    CalendarCollectorError,
    collect_all_calendars,
    collect_events,
    format_calendar_list,
    list_available_calendars,
    _normalize_event,
    _output_path,
)
from personal_assistant.state_repo import init_repo

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture()
def state_dir(tmp_path: Path) -> Path:
    """Create and initialize a state repo."""
    repo = tmp_path / "pa-state"
    init_repo(path=repo)
    return repo


@pytest.fixture()
def gws_response() -> str:
    """Load the sample GWS calendar response."""
    return (FIXTURES_DIR / "gws_calendar_response.json").read_text()


def _mock_run_success(gws_response: str):
    """Create a mock subprocess.run that returns the GWS response."""
    from unittest.mock import MagicMock

    result = MagicMock()
    result.returncode = 0
    result.stdout = gws_response
    result.stderr = ""
    return result


def test_collect_events_writes_json(state_dir: Path, gws_response: str) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        mock_run.return_value = _mock_run_success(gws_response)
        events = collect_events("primary", repo_path=state_dir)

    assert len(events) == 3
    output_file = state_dir / "calendar" / "events.json"
    assert output_file.exists()
    written = json.loads(output_file.read_text())
    assert len(written) == 3


def test_collect_events_normalizes_fields(state_dir: Path, gws_response: str) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        mock_run.return_value = _mock_run_success(gws_response)
        events = collect_events("primary", repo_path=state_dir)

    event = events[0]
    assert event["id"] == "event-001"
    assert event["summary"] == "Team Standup"
    assert event["start"] == "2026-03-30T09:00:00-04:00"
    assert event["all_day"] is False
    assert event["organizer_email"] == "boss@example.com"
    assert len(event["attendees"]) == 2


def test_collect_events_handles_all_day(state_dir: Path, gws_response: str) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        mock_run.return_value = _mock_run_success(gws_response)
        events = collect_events("primary", repo_path=state_dir)

    all_day = events[2]
    assert all_day["all_day"] is True
    assert all_day["start"] == "2026-04-01"


def test_collect_events_gws_not_found(state_dir: Path) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run",
        side_effect=FileNotFoundError(),
    ):
        with pytest.raises(CalendarCollectorError, match="not found"):
            collect_events("primary", repo_path=state_dir)


def test_collect_events_gws_failure(state_dir: Path) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        from unittest.mock import MagicMock

        result = MagicMock()
        result.returncode = 1
        result.stdout = ""
        result.stderr = "auth expired"
        mock_run.return_value = result

        with pytest.raises(CalendarCollectorError, match="exit 1"):
            collect_events("primary", repo_path=state_dir)


def test_collect_events_bad_json(state_dir: Path) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        from unittest.mock import MagicMock

        result = MagicMock()
        result.returncode = 0
        result.stdout = "not json"
        result.stderr = ""
        mock_run.return_value = result

        with pytest.raises(CalendarCollectorError, match="parse"):
            collect_events("primary", repo_path=state_dir)


def test_collect_all_calendars(state_dir: Path, gws_response: str) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        mock_run.return_value = _mock_run_success(gws_response)
        results = collect_all_calendars(
            ["primary", "shared@group.calendar.google.com"],
            repo_path=state_dir,
        )

    assert len(results) == 2
    assert "primary" in results
    assert "shared@group.calendar.google.com" in results


def test_collect_all_calendars_handles_failure(
    state_dir: Path, gws_response: str
) -> None:
    call_count = 0

    def side_effect(*args, **kwargs):
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            return _mock_run_success(gws_response)
        from unittest.mock import MagicMock

        result = MagicMock()
        result.returncode = 1
        result.stdout = ""
        result.stderr = "not found"
        return result

    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run",
        side_effect=side_effect,
    ):
        results = collect_all_calendars(
            ["primary", "bad@calendar"], repo_path=state_dir
        )

    assert len(results["primary"]) == 3
    assert results["bad@calendar"] == []


def test_normalize_event_minimal() -> None:
    raw = {"id": "x", "start": {}, "end": {}}
    normalized = _normalize_event(raw)
    assert normalized["id"] == "x"
    assert normalized["summary"] == "(no title)"
    assert normalized["attendees"] == []
    assert normalized["all_day"] is False


def test_output_path_primary(tmp_path: Path) -> None:
    path = _output_path("primary", repo_path=tmp_path)
    assert path == tmp_path / "calendar" / "events.json"


def test_output_path_shared(tmp_path: Path) -> None:
    path = _output_path("eng@group.calendar.google.com", repo_path=tmp_path)
    assert "eng_at_group_calendar_google_com" in path.name


def test_normalize_event_new_fields() -> None:
    raw = {
        "id": "x",
        "start": {"dateTime": "2026-03-30T09:00:00-04:00"},
        "end": {"dateTime": "2026-03-30T10:00:00-04:00"},
        "description": "Test description",
        "location": "Room 42",
        "htmlLink": "https://calendar.google.com/event/x",
        "attachments": [
            {
                "title": "Doc",
                "fileUrl": "https://docs.google.com/d/123",
            }
        ],
    }
    normalized = _normalize_event(raw)
    assert normalized["description"] == "Test description"
    assert normalized["location"] == "Room 42"
    assert normalized["html_link"] == "https://calendar.google.com/event/x"
    assert len(normalized["attachments"]) == 1
    assert normalized["attachments"][0]["title"] == "Doc"


def test_list_available_calendars() -> None:
    page_json = json.dumps(
        {
            "items": [
                {
                    "id": "primary@test.com",
                    "summary": "Main",
                    "accessRole": "owner",
                    "primary": True,
                },
                {
                    "id": "shared@group.calendar.google.com",
                    "summary": "Shared",
                    "accessRole": "reader",
                },
            ]
        }
    )
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        from unittest.mock import MagicMock

        result = MagicMock()
        result.returncode = 0
        result.stdout = page_json
        result.stderr = ""
        mock_run.return_value = result
        calendars = list_available_calendars()

    assert len(calendars) == 2
    assert calendars[0]["id"] == "primary@test.com"
    assert calendars[0]["primary"] == "yes"
    assert calendars[1]["primary"] == "no"


def test_list_available_calendars_failure() -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector.subprocess.run"
    ) as mock_run:
        from unittest.mock import MagicMock

        result = MagicMock()
        result.returncode = 1
        result.stdout = ""
        result.stderr = "auth error"
        mock_run.return_value = result

        with pytest.raises(CalendarCollectorError):
            list_available_calendars()


def test_format_calendar_list_empty() -> None:
    assert "No calendars" in format_calendar_list([])


def test_format_calendar_list() -> None:
    calendars = [
        {
            "id": "x@test.com",
            "summary": "Test",
            "access_role": "owner",
            "primary": "yes",
        }
    ]
    output = format_calendar_list(calendars)
    assert "Test" in output
    assert "x@test.com" in output
