# Generated By: Claude Code (claude-opus-5[1m])
"""Tests for ChatTab message handling (no agent, no SDK)."""

from __future__ import annotations

from unittest.mock import MagicMock

from personal_assistant_dashboard.chat_tab import UNSUPPORTED_MESSAGE, ChatTab


def test_send_message_reports_unsupported() -> None:
    tab = MagicMock()
    ChatTab.send_message(tab, "what is on my calendar?", displayed=True)
    tab._append_system.assert_called_once_with(UNSUPPORTED_MESSAGE)
    tab._append_user.assert_not_called()


def test_send_message_displays_text_not_already_shown() -> None:
    tab = MagicMock()
    ChatTab.send_message(tab, "hello")
    tab._append_user.assert_called_once_with("hello")
    tab._append_system.assert_called_once_with(UNSUPPORTED_MESSAGE)


def test_empty_text_is_ignored() -> None:
    tab = MagicMock()
    ChatTab.send_message(tab, "")
    tab._append_system.assert_not_called()
