# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for info_tab filtering logic."""

from __future__ import annotations

import time
from datetime import datetime

from personal_assistant_dashboard.info_tab import InfoTab


class TestActiveToday:
    """Test InfoTab._active_today static method."""

    def _today_start_ms(self) -> int:
        return int(
            datetime.now()
            .replace(hour=0, minute=0, second=0, microsecond=0)
            .timestamp()
            * 1000
        )

    def test_active_sessions_always_included(self) -> None:
        yesterday_ms = self._today_start_ms() - 86_400_000
        sessions = [{"session_id": "s1", "is_active": True, "started_at": yesterday_ms}]
        result = InfoTab._active_today(sessions)
        assert len(result) == 1

    def test_closed_started_today_included(self) -> None:
        now_ms = int(time.time() * 1000)
        sessions = [
            {
                "session_id": "s1",
                "is_active": False,
                "started_at": now_ms,
                "ended_at": 0,
            }
        ]
        result = InfoTab._active_today(sessions)
        assert len(result) == 1

    def test_closed_started_yesterday_excluded(self) -> None:
        yesterday_ms = self._today_start_ms() - 86_400_000
        sessions = [
            {
                "session_id": "s1",
                "is_active": False,
                "started_at": yesterday_ms,
                "ended_at": 0,
            }
        ]
        result = InfoTab._active_today(sessions)
        assert len(result) == 0

    def test_closed_started_yesterday_ended_today_included(self) -> None:
        yesterday_ms = self._today_start_ms() - 86_400_000
        now_ms = int(time.time() * 1000)
        sessions = [
            {
                "session_id": "s1",
                "is_active": False,
                "started_at": yesterday_ms,
                "ended_at": now_ms,
            }
        ]
        result = InfoTab._active_today(sessions)
        assert len(result) == 1

    def test_closed_started_and_ended_yesterday_excluded(self) -> None:
        yesterday_ms = self._today_start_ms() - 86_400_000
        sessions = [
            {
                "session_id": "s1",
                "is_active": False,
                "started_at": yesterday_ms - 3600_000,
                "ended_at": yesterday_ms,
            }
        ]
        result = InfoTab._active_today(sessions)
        assert len(result) == 0
