# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for _find_active_meetings in dashboard module."""

from datetime import datetime, timedelta, timezone

from personal_assistant_dashboard.dashboard import _find_active_meetings


def _make_event(
    *,
    start: datetime,
    end: datetime,
    status: str = "confirmed",
    response_status: str = "accepted",
    all_day: bool = False,
    event_type: str = "default",
    event_id: str = "evt1",
    summary: str = "Meeting",
    hangout_link: str | None = "https://meet.google.com/abc-defg-hij",
) -> dict:
    attendees = [
        {"email": "me@example.com", "self": True, "response_status": response_status}
    ]
    return {
        "id": event_id,
        "summary": summary,
        "start": start.isoformat() if not all_day else start.strftime("%Y-%m-%d"),
        "end": end.isoformat() if not all_day else end.strftime("%Y-%m-%d"),
        "all_day": all_day,
        "status": status,
        "attendees": attendees,
        "event_type": event_type,
        "hangout_link": hangout_link,
    }


def test_active_meeting_detected():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10), end=now + timedelta(minutes=20)
    )
    result = _find_active_meetings([event])
    assert len(result) == 1
    assert result[0]["id"] == "evt1"


def test_future_meeting_not_detected():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now + timedelta(minutes=10), end=now + timedelta(minutes=40)
    )
    assert _find_active_meetings([event]) == []


def test_past_meeting_not_detected():
    now = datetime.now(timezone.utc)
    event = _make_event(start=now - timedelta(hours=2), end=now - timedelta(hours=1))
    assert _find_active_meetings([event]) == []


def test_declined_meeting_excluded():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
        response_status="declined",
    )
    assert _find_active_meetings([event]) == []


def test_needs_action_excluded():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
        response_status="needsAction",
    )
    assert _find_active_meetings([event]) == []


def test_tentative_included():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
        response_status="tentative",
    )
    assert len(_find_active_meetings([event])) == 1


def test_all_day_excluded():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(hours=1),
        end=now + timedelta(hours=23),
        all_day=True,
    )
    assert _find_active_meetings([event]) == []


def test_cancelled_excluded():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
        status="cancelled",
    )
    assert _find_active_meetings([event]) == []


def test_working_location_excluded():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
        event_type="workingLocation",
    )
    assert _find_active_meetings([event]) == []


def test_out_of_office_excluded():
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
        event_type="outOfOffice",
    )
    assert _find_active_meetings([event]) == []


def test_no_attendees_no_meet_code_excluded():
    """Solo event with no meeting code should not trigger alert."""
    now = datetime.now(timezone.utc)
    event = {
        "id": "own",
        "summary": "Focus time",
        "start": (now - timedelta(minutes=5)).isoformat(),
        "end": (now + timedelta(minutes=25)).isoformat(),
        "all_day": False,
        "status": "confirmed",
        "attendees": [],
        "event_type": "default",
        "hangout_link": None,
    }
    assert _find_active_meetings([event]) == []


def test_no_attendees_with_meet_code_included():
    """Solo event with a meeting code should still trigger alert."""
    now = datetime.now(timezone.utc)
    event = {
        "id": "own",
        "summary": "Recording session",
        "start": (now - timedelta(minutes=5)).isoformat(),
        "end": (now + timedelta(minutes=25)).isoformat(),
        "all_day": False,
        "status": "confirmed",
        "attendees": [],
        "event_type": "default",
        "hangout_link": "https://meet.google.com/abc-defg-hij",
    }
    assert len(_find_active_meetings([event])) == 1


def test_self_only_attendee_no_meet_code_excluded():
    """Event where user is sole attendee with no meeting code → no alert."""
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
    )
    event["hangout_link"] = None
    assert _find_active_meetings([event]) == []


def test_multiple_attendees_no_meet_code_excluded():
    """No meet link → no way to assess join state → no alert."""
    now = datetime.now(timezone.utc)
    event = _make_event(
        start=now - timedelta(minutes=10),
        end=now + timedelta(minutes=20),
    )
    event["hangout_link"] = None
    event["attendees"].append(
        {"email": "other@example.com", "self": False, "response_status": "accepted"}
    )
    assert _find_active_meetings([event]) == []
