# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for state_repo module.

These tests use real git commands via subprocess and are marked as integration tests.
"""

import subprocess
from pathlib import Path

import pytest

from personal_assistant.state_repo import (
    StateRepoError,
    commit_state,
    get_changes,
    get_file_at_last_commit,
    get_last_commit_time,
    init_repo,
    status_summary,
)

pytestmark = pytest.mark.integration


@pytest.fixture()
def state_dir(tmp_path: Path) -> Path:
    """Create a temporary directory for a state repo."""
    return tmp_path / "pa-state"


@pytest.fixture()
def initialized_repo(state_dir: Path) -> Path:
    """Create and initialize a state repo."""
    init_repo(path=state_dir)
    return state_dir


def test_init_creates_repo(state_dir: Path) -> None:
    path = init_repo(path=state_dir)
    assert path == state_dir
    assert (state_dir / ".git").is_dir()


def test_init_creates_subdirectories(state_dir: Path) -> None:
    init_repo(path=state_dir)
    assert (state_dir / "calendar").is_dir()
    assert (state_dir / "jira" / "snapshots").is_dir()
    assert (state_dir / "github" / "prs").is_dir()
    assert (state_dir / "config").is_dir()
    assert (state_dir / "digests").is_dir()


def test_init_creates_initial_commit(state_dir: Path) -> None:
    init_repo(path=state_dir)
    result = subprocess.run(
        ["git", "-C", str(state_dir), "log", "--oneline"],
        capture_output=True,
        text=True,
    )
    assert "Initialize state repo" in result.stdout


def test_init_is_idempotent(state_dir: Path) -> None:
    init_repo(path=state_dir)
    init_repo(path=state_dir)
    result = subprocess.run(
        ["git", "-C", str(state_dir), "log", "--oneline"],
        capture_output=True,
        text=True,
    )
    assert result.stdout.strip().count("\n") == 0  # still just one commit


def test_get_changes_empty_after_init(initialized_repo: Path) -> None:
    changes = get_changes(repo_path=initialized_repo)
    assert changes == []


def test_get_changes_detects_new_file(initialized_repo: Path) -> None:
    (initialized_repo / "calendar" / "events.json").write_text("{}")
    changes = get_changes(repo_path=initialized_repo)
    assert len(changes) == 1
    assert changes[0].path == "calendar/events.json"
    assert changes[0].change_type == "untracked"


def test_get_changes_detects_modified_file(initialized_repo: Path) -> None:
    test_file = initialized_repo / "calendar" / ".gitkeep"
    test_file.write_text("modified")
    changes = get_changes(repo_path=initialized_repo)
    modified = [c for c in changes if c.change_type == "modified"]
    assert len(modified) == 1


def test_commit_state_creates_commit(initialized_repo: Path) -> None:
    (initialized_repo / "calendar" / "events.json").write_text("{}")
    created = commit_state("test commit", repo_path=initialized_repo)
    assert created is True


def test_commit_state_returns_false_when_empty(
    initialized_repo: Path,
) -> None:
    created = commit_state("empty", repo_path=initialized_repo)
    assert created is False


def test_get_last_commit_time(initialized_repo: Path) -> None:
    timestamp = get_last_commit_time(repo_path=initialized_repo)
    assert timestamp is not None


def test_get_file_at_last_commit(initialized_repo: Path) -> None:
    # Write and commit a file
    (initialized_repo / "calendar" / "events.json").write_text('{"v": 1}')
    commit_state("v1", repo_path=initialized_repo)

    # Modify the file on disk
    (initialized_repo / "calendar" / "events.json").write_text('{"v": 2}')

    # Should return the committed version
    content = get_file_at_last_commit(
        "calendar/events.json", repo_path=initialized_repo
    )
    assert content == '{"v": 1}'


def test_get_file_at_last_commit_missing_file(
    initialized_repo: Path,
) -> None:
    content = get_file_at_last_commit("nonexistent.json", repo_path=initialized_repo)
    assert content is None


def test_status_summary_shows_path(initialized_repo: Path) -> None:
    summary = status_summary(repo_path=initialized_repo)
    assert str(initialized_repo) in summary
    assert "No uncommitted changes" in summary


def test_status_summary_shows_changes(initialized_repo: Path) -> None:
    (initialized_repo / "calendar" / "events.json").write_text("{}")
    summary = status_summary(repo_path=initialized_repo)
    assert "1 uncommitted change(s)" in summary
    assert "events.json" in summary


def test_operations_fail_without_init(tmp_path: Path) -> None:
    bad_path = tmp_path / "nonexistent"
    with pytest.raises(StateRepoError, match="not found"):
        get_changes(repo_path=bad_path)
