# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for CLI dispatch in __main__.py."""

import sys
from io import StringIO
from pathlib import Path
from unittest.mock import patch

import pytest

# state_dir fixture provided by conftest.py


def _run_cli(*args: str) -> tuple[str, int]:
    """Run the CLI with the given args, capture stdout."""
    captured = StringIO()
    exit_code = 0
    with patch.object(sys, "argv", ["pa", *args]):
        with patch("sys.stdout", captured):
            try:
                from personal_assistant.__main__ import main

                main()
            except SystemExit as e:
                exit_code = e.code if isinstance(e.code, int) else 1
    return captured.getvalue(), exit_code


@pytest.mark.integration
def test_cli_state_init(tmp_path: Path) -> None:
    state_path = str(tmp_path / "test-state")
    output, code = _run_cli("state", "init", "--state-path", state_path)
    assert code == 0
    assert "initialized" in output.lower()
    assert (Path(state_path) / ".git").exists()


def test_cli_state_status(state_dir: Path) -> None:
    output, code = _run_cli("state", "status", "--state-path", str(state_dir))
    assert code == 0
    assert "No uncommitted changes" in output


def test_cli_state_commit_empty(state_dir: Path) -> None:
    output, code = _run_cli("state", "commit", "--state-path", str(state_dir))
    assert code == 0
    assert "Nothing to commit" in output


def test_cli_track_add(state_dir: Path) -> None:
    output, code = _run_cli(
        "track",
        "add",
        "TEST-123",
        "--tier",
        "active",
        "--state-path",
        str(state_dir),
    )
    assert code == 0
    assert "TEST-123" in output
    # Verify the config file was actually updated
    from personal_assistant.config_manager import load_config

    config = load_config(repo_path=state_dir)
    jira_keys = [e["key"] for e in config.get("jira", [])]
    assert "TEST-123" in jira_keys


def test_cli_track_list(state_dir: Path) -> None:
    output, code = _run_cli("track", "list", "--state-path", str(state_dir))
    assert code == 0
    assert "Jira" in output


def test_cli_track_remove_not_found(state_dir: Path) -> None:
    output, code = _run_cli("track", "remove", "NOPE-1", "--state-path", str(state_dir))
    assert code == 0
    assert "not found" in output


def test_cli_track_repo(state_dir: Path) -> None:
    output, code = _run_cli(
        "track", "repo", "owner/repo", "--state-path", str(state_dir)
    )
    assert code == 0
    assert "owner/repo" in output
    # Verify the config file contains the repo
    from personal_assistant.config_manager import load_config

    config = load_config(repo_path=state_dir)
    repos = config.get("github", {}).get("repos", [])
    assert "owner/repo" in repos


def test_cli_no_args_shows_help() -> None:
    _, code = _run_cli()
    assert code == 1


def test_cli_collect_calendar(state_dir: Path) -> None:
    with patch(
        "personal_assistant.collectors.calendar_collector" ".collect_all_calendars"
    ) as mock_collect:
        mock_collect.return_value = {"primary": [{"id": "1"}]}
        output, code = _run_cli(
            "collect",
            "calendar",
            "--state-path",
            str(state_dir),
        )
    assert code == 0
    assert "Collected" in output


def test_cli_analyze_no_data(state_dir: Path) -> None:
    output, code = _run_cli("analyze", "calendar", "--state-path", str(state_dir))
    assert code == 0
    assert "No calendar data" in output
