# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for chat_client module."""

from __future__ import annotations

import asyncio
import time
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from personal_assistant_dashboard.chat_client import (
    SYSTEM_PROMPT,
    ChatClient,
    _deny_unapproved,
    extract_model_name,
    lookup_context_window,
)

# -- _deny_unapproved --------------------------------------------------------


def test_deny_unapproved_returns_deny():
    result = asyncio.run(_deny_unapproved("Bash", {"command": "ls"}, MagicMock()))
    assert result.behavior == "deny"
    assert "Bash" in result.message


def test_deny_unapproved_any_tool():
    result = asyncio.run(
        _deny_unapproved(
            "mcp__plugin_atlassian__searchJiraIssuesUsingJql",
            {"jql": "project = TEST"},
            MagicMock(),
        )
    )
    assert result.behavior == "deny"
    assert "not in the allowed" in result.message


# -- lookup_context_window ---------------------------------------------------


def test_lookup_context_window_base_model():
    assert lookup_context_window("claude-opus-4-7") == 200_000


def test_lookup_context_window_1m_variant():
    assert lookup_context_window("claude-opus-4-7[1m]") == 1_000_000


def test_lookup_context_window_empty():
    assert lookup_context_window("") == 200_000


# -- extract_model_name ------------------------------------------------------


def test_extract_model_name_empty():
    assert extract_model_name(None) == ""
    assert extract_model_name({}) == ""


def test_extract_model_name_single_key():
    assert extract_model_name({"claude-opus-4-7": {}}) == "claude-opus-4-7"


def test_extract_model_name_multi_picks_highest_output():
    usage = {
        "claude-haiku-4-5": {"outputTokens": 10},
        "claude-opus-4-7": {"outputTokens": 500},
    }
    assert extract_model_name(usage) == "claude-opus-4-7"


# -- _handle_message ---------------------------------------------------------

_MODEL = "claude-sonnet-4-5-20250514"


def _make_client(**overrides: object) -> ChatClient:
    """Create a ChatClient with mock callbacks, without starting it."""
    defaults = {
        "on_text": MagicMock(),
        "on_tool_use": MagicMock(),
        "on_done": MagicMock(),
        "on_error": MagicMock(),
        "on_usage": MagicMock(),
    }
    defaults.update(overrides)
    client = ChatClient(**defaults)  # type: ignore[arg-type]
    return client


def test_handle_assistant_message_text_block_skipped():
    """Text in AssistantMessage is skipped — displayed via StreamEvent instead."""
    from claude_agent_sdk import AssistantMessage, TextBlock

    client = _make_client()
    msg = AssistantMessage(content=[TextBlock(text="hello")], model=_MODEL)
    client._handle_message(msg)
    client._on_text.assert_not_called()


def test_handle_assistant_message_tool_use_block():
    from claude_agent_sdk import AssistantMessage, ToolUseBlock

    client = _make_client()
    msg = AssistantMessage(
        content=[ToolUseBlock(id="t1", name="Bash", input={"command": "ls"})],
        model=_MODEL,
    )
    client._handle_message(msg)
    client._on_tool_use.assert_called_once_with("Bash")


def test_handle_assistant_message_mixed_blocks():
    """Only ToolUseBlock is handled — TextBlock is skipped (dedup with StreamEvent)."""
    from claude_agent_sdk import AssistantMessage, TextBlock, ToolUseBlock

    client = _make_client()
    msg = AssistantMessage(
        content=[
            TextBlock(text="running command"),
            ToolUseBlock(id="t1", name="Grep", input={"pattern": "foo"}),
            TextBlock(text="found it"),
        ],
        model=_MODEL,
    )
    client._handle_message(msg)
    client._on_text.assert_not_called()
    client._on_tool_use.assert_called_once_with("Grep")


def test_handle_stream_event_text_delta():
    from claude_agent_sdk import StreamEvent

    client = _make_client()
    msg = StreamEvent(
        uuid="u1",
        session_id="s1",
        event={
            "type": "content_block_delta",
            "delta": {"type": "text_delta", "text": "chunk"},
        },
    )
    client._handle_message(msg)
    client._on_text.assert_called_once_with("chunk")


def test_handle_stream_event_empty_text_ignored():
    from claude_agent_sdk import StreamEvent

    client = _make_client()
    msg = StreamEvent(
        uuid="u1",
        session_id="s1",
        event={
            "type": "content_block_delta",
            "delta": {"type": "text_delta", "text": ""},
        },
    )
    client._handle_message(msg)
    client._on_text.assert_not_called()


def test_handle_stream_event_non_text_delta_ignored():
    from claude_agent_sdk import StreamEvent

    client = _make_client()
    msg = StreamEvent(
        uuid="u1",
        session_id="s1",
        event={
            "type": "content_block_delta",
            "delta": {"type": "thinking_delta", "thinking": "hmm"},
        },
    )
    client._handle_message(msg)
    client._on_text.assert_not_called()


def test_handle_stream_event_non_delta_type_ignored():
    from claude_agent_sdk import StreamEvent

    client = _make_client()
    msg = StreamEvent(
        uuid="u1",
        session_id="s1",
        event={"type": "content_block_start"},
    )
    client._handle_message(msg)
    client._on_text.assert_not_called()
    client._on_done.assert_not_called()


def test_handle_result_message_success():
    from claude_agent_sdk import ResultMessage

    client = _make_client()
    msg = ResultMessage(
        subtype="result",
        duration_ms=100,
        duration_api_ms=80,
        is_error=False,
        num_turns=1,
        session_id="s1",
    )
    client._handle_message(msg)
    client._on_done.assert_called_once()
    client._on_error.assert_not_called()


def test_handle_result_message_error_with_details():
    from claude_agent_sdk import ResultMessage

    client = _make_client()
    msg = ResultMessage(
        subtype="result",
        duration_ms=100,
        duration_api_ms=80,
        is_error=True,
        num_turns=1,
        session_id="s1",
        errors=["rate limited", "try again"],
    )
    client._handle_message(msg)
    client._on_error.assert_called_once_with("rate limited; try again")
    client._on_done.assert_not_called()


def test_handle_result_message_error_no_details():
    from claude_agent_sdk import ResultMessage

    client = _make_client()
    msg = ResultMessage(
        subtype="result",
        duration_ms=100,
        duration_api_ms=80,
        is_error=True,
        num_turns=1,
        session_id="s1",
        errors=None,
    )
    client._handle_message(msg)
    client._on_error.assert_called_once_with("Unknown error")


def test_handle_system_message_logged_only():
    from claude_agent_sdk import SystemMessage

    client = _make_client()
    msg = SystemMessage(subtype="system", data={"info": "connected"})
    client._handle_message(msg)
    client._on_text.assert_not_called()
    client._on_done.assert_not_called()
    client._on_error.assert_not_called()


def test_handle_unknown_message_type_ignored():
    client = _make_client()
    client._handle_message("unexpected")
    client._on_text.assert_not_called()
    client._on_done.assert_not_called()
    client._on_error.assert_not_called()


# -- send without connection --------------------------------------------------


def test_send_without_connection_calls_on_error():
    client = _make_client()
    client.send("hello")
    client._on_error.assert_called_once_with("Chat client not connected")


# -- clear without loop -------------------------------------------------------


def test_clear_without_loop_is_noop():
    client = _make_client()
    client.clear()  # should not raise


# -- lifecycle guards ----------------------------------------------------------


def test_start_when_already_started_is_noop():
    client = _make_client()
    client._running = True
    client._loop = MagicMock()
    client.start()  # should not raise or create duplicate thread
    assert client._running is True


def test_stop_when_not_started_is_noop():
    client = _make_client()
    client.stop()  # should not raise


# -- system prompt ------------------------------------------------------------


def test_system_prompt_uses_claude_code_preset():
    assert SYSTEM_PROMPT["type"] == "preset"
    assert SYSTEM_PROMPT["preset"] == "claude_code"
    assert "append" in SYSTEM_PROMPT


# -- assistant usage snapshot -------------------------------------------------


def _make_result_msg(
    *,
    session_id: str = "s1",
    total_cost_usd: float = 0.05,
    input_tokens: int = 100,
    output_tokens: int = 50,
    model: str = "claude-sonnet-4-6",
    is_error: bool = False,
):
    from claude_agent_sdk import ResultMessage

    return ResultMessage(
        subtype="result",
        duration_ms=1000,
        duration_api_ms=800,
        is_error=is_error,
        num_turns=1,
        session_id=session_id,
        total_cost_usd=total_cost_usd,
        usage={"input_tokens": input_tokens, "output_tokens": output_tokens},
        model_usage={model: {"outputTokens": output_tokens}},
    )


def test_subagent_assistant_message_usage_ignored():
    """AssistantMessages from subagents don't update the main-turn snapshot."""
    from claude_agent_sdk import AssistantMessage, TextBlock

    client = _make_client()
    client._handle_message(
        AssistantMessage(
            content=[TextBlock(text="")],
            model="claude-opus-4-7",
            usage={"input_tokens": 1, "cache_read_input_tokens": 100},
        )
    )
    client._handle_message(
        AssistantMessage(
            content=[TextBlock(text="")],
            model="claude-opus-4-7",
            parent_tool_use_id="task-123",
            usage={"input_tokens": 999, "cache_read_input_tokens": 999_999},
        )
    )
    assert client._last_assistant_usage == {
        "input_tokens": 1,
        "cache_read_input_tokens": 100,
    }


def test_assistant_message_without_usage_leaves_snapshot_untouched():
    """Early/text-only assistant messages with no usage don't overwrite."""
    from claude_agent_sdk import AssistantMessage, TextBlock

    client = _make_client()
    client._handle_message(
        AssistantMessage(
            content=[TextBlock(text="")],
            model="claude-opus-4-7",
            usage={"input_tokens": 42, "cache_read_input_tokens": 4242},
        )
    )
    client._handle_message(
        AssistantMessage(
            content=[TextBlock(text="")],
            model="claude-opus-4-7",
            usage=None,
        )
    )
    assert client._last_assistant_usage == {
        "input_tokens": 42,
        "cache_read_input_tokens": 4242,
    }


# -- on_usage callback -------------------------------------------------------


def test_usage_callback_fires_per_turn():
    """on_usage fires once per turn."""
    client = _make_client()
    client._handle_message(_make_result_msg(total_cost_usd=0.05))
    client._handle_message(_make_result_msg(total_cost_usd=0.03))
    assert client._on_usage.call_count == 2


def test_usage_callback_fires_with_context_pct():
    """on_usage receives context % from the turn's assistant usage snapshot."""
    from claude_agent_sdk import AssistantMessage, TextBlock

    client = _make_client()
    client._handle_message(
        AssistantMessage(
            content=[TextBlock(text="")],
            model="claude-opus-4-7",
            usage={
                "input_tokens": 10,
                "cache_read_input_tokens": 50_000,
                "cache_creation_input_tokens": 2_000,
            },
        )
    )
    client._handle_message(_make_result_msg(model="claude-opus-4-7"))
    _model, pct = client._on_usage.call_args.args
    # (10 + 50_000 + 2_000) / 200_000 * 100 = 26.005 → 26.0
    assert pct == pytest.approx(26.0)


def test_usage_callback_respects_1m_context_window():
    """on_usage computes context % against the correct window size."""
    from claude_agent_sdk import AssistantMessage, TextBlock

    client = _make_client()
    client._handle_message(
        AssistantMessage(
            content=[TextBlock(text="")],
            model="claude-opus-4-7[1m]",
            usage={
                "input_tokens": 100_000,
                "cache_read_input_tokens": 0,
                "cache_creation_input_tokens": 0,
            },
        )
    )
    client._handle_message(_make_result_msg(model="claude-opus-4-7[1m]"))
    _model, pct = client._on_usage.call_args.args
    # 100_000 / 1_000_000 * 100 = 10.0
    assert pct == pytest.approx(10.0)


def test_usage_callback_not_fired_on_error_result():
    """Error results skip the usage callback."""
    client = _make_client()
    client._handle_message(_make_result_msg(is_error=True))
    client._on_usage.assert_not_called()


def test_usage_callback_passes_model_name():
    """on_usage passes the model name from the ResultMessage."""
    client = _make_client()
    client._handle_message(_make_result_msg(model="claude-opus-4-7[1m]"))
    model, _pct = client._on_usage.call_args.args
    assert model == "claude-opus-4-7[1m]"


def test_usage_callback_preserves_pct_when_no_snapshot():
    """Context % stays at prior value when no assistant usage snapshot exists."""
    from claude_agent_sdk import AssistantMessage, TextBlock

    client = _make_client()
    client._handle_message(
        AssistantMessage(
            content=[TextBlock(text="")],
            model="claude-sonnet-4-6",
            usage={
                "input_tokens": 40_000,
                "cache_read_input_tokens": 0,
                "cache_creation_input_tokens": 0,
            },
        )
    )
    client._handle_message(_make_result_msg(total_cost_usd=0.05))
    _model1, pct1 = client._on_usage.call_args.args
    assert pct1 == pytest.approx(20.0)

    # Second turn with no assistant usage snapshot
    client._handle_message(_make_result_msg(total_cost_usd=0.03))
    _model2, pct2 = client._on_usage.call_args.args
    assert pct2 == pytest.approx(20.0)  # unchanged


# -- lazy SDK connect / new clear semantics ----------------------------------


def test_has_resume_target_true_when_id_set_and_disconnected():
    """Pre-connect with a prior session id → UI shows Cont."""
    client = _make_client()
    client._next_resume_id = "session-abc"
    assert client.has_resume_target() is True


def test_has_resume_target_false_when_no_id():
    """Fresh PA, no prior session → UI shows Send."""
    client = _make_client()
    client._next_resume_id = None
    assert client.has_resume_target() is False


def test_has_resume_target_false_after_connect():
    """Once connected, resume target is consumed → UI shows Send."""
    client = _make_client()
    client._next_resume_id = "session-abc"
    client._client = MagicMock()
    assert client.has_resume_target() is False


def test_start_does_not_connect_sdk():
    """start() spins up the loop but does NOT spawn the SDK subprocess."""
    client = _make_client()
    with (
        patch.object(ChatClient, "_find_last_session", return_value=None),
        patch(
            "personal_assistant_dashboard.chat_client.ClaudeSDKClient"
        ) as mock_sdk_cls,
    ):
        try:
            client.start()
            time.sleep(0.05)
            assert client._client is None
            assert mock_sdk_cls.call_count == 0
        finally:
            client.stop()


def test_start_captures_resume_id_for_button_label():
    """start() reads the last session id so the UI knows to show Cont."""
    client = _make_client()
    with (
        patch.object(ChatClient, "_find_last_session", return_value="session-xyz"),
        patch("personal_assistant_dashboard.chat_client.ClaudeSDKClient"),
    ):
        try:
            client.start()
            time.sleep(0.05)
            assert client._next_resume_id == "session-xyz"
        finally:
            client.stop()


def _make_sdk_mock() -> AsyncMock:
    """AsyncMock for ClaudeSDKClient with empty receive_messages."""
    sdk = AsyncMock()

    async def _empty_messages():  # pragma: no cover - awaited but yields nothing
        return
        yield  # noqa

    sdk.receive_messages = MagicMock(side_effect=_empty_messages)
    return sdk


def test_connect_uses_next_resume_id_and_clears_it():
    """_connect reads _next_resume_id and consumes it after success."""
    client = _make_client()
    client._next_resume_id = "session-abc"
    sdk = _make_sdk_mock()

    with patch(
        "personal_assistant_dashboard.chat_client.ClaudeSDKClient",
        return_value=sdk,
    ) as mock_cls:
        asyncio.run(client._connect())

    options = mock_cls.call_args.kwargs["options"]
    assert options.resume == "session-abc"
    assert client._next_resume_id is None
    assert client._client is sdk


def test_connect_with_none_resume_starts_fresh_session():
    """_connect with no resume id passes resume=None (fresh CLI session)."""
    client = _make_client()
    client._next_resume_id = None
    sdk = _make_sdk_mock()

    with patch(
        "personal_assistant_dashboard.chat_client.ClaudeSDKClient",
        return_value=sdk,
    ) as mock_cls:
        asyncio.run(client._connect())

    options = mock_cls.call_args.kwargs["options"]
    assert options.resume is None


def test_clear_drops_resume_id_synchronously():
    """Sync clear() drops the resume target immediately for UI updates."""
    client = _make_client()
    client._next_resume_id = "session-abc"
    assert client._client is None

    client.clear()

    assert client._next_resume_id is None
    assert client._client is None


def test_clear_async_disconnects_when_connected():
    """_clear (async) tears down the SDK."""
    client = _make_client()
    sdk = _make_sdk_mock()
    client._client = sdk
    client._next_resume_id = None

    asyncio.run(client._clear())

    sdk.disconnect.assert_awaited_once()
    assert client._client is None


def test_clear_resets_ui_context_pct():
    """UI-side context % resets on clear and fires the callback with zero."""
    client = _make_client()
    sdk = _make_sdk_mock()
    client._client = sdk
    client._ui_context_pct = 55.0

    asyncio.run(client._clear())

    assert client._ui_context_pct == 0.0
    client._on_usage.assert_called_once_with(client._ui_model_name, 0.0)


def test_send_after_clear_starts_fresh_session():
    """End-to-end: clear() then send → SDK constructed with resume=None."""
    client = _make_client()
    client._next_resume_id = "session-abc"

    client.clear()
    assert client._next_resume_id is None

    sdk = _make_sdk_mock()
    with (
        patch(
            "personal_assistant_dashboard.chat_client.ClaudeSDKClient",
            return_value=sdk,
        ) as mock_cls,
        patch.object(client, "_receive_loop", AsyncMock()),
    ):
        asyncio.run(client._send("hello"))

    options = mock_cls.call_args.kwargs["options"]
    assert options.resume is None
    sdk.query.assert_awaited_once_with("hello")


def test_send_lazy_connects_with_pending_resume():
    """End-to-end: pending resume id → SDK constructed with that id."""
    client = _make_client()
    client._next_resume_id = "session-abc"

    sdk = _make_sdk_mock()
    with (
        patch(
            "personal_assistant_dashboard.chat_client.ClaudeSDKClient",
            return_value=sdk,
        ) as mock_cls,
        patch.object(client, "_receive_loop", AsyncMock()),
    ):
        asyncio.run(client._send("hello"))

    options = mock_cls.call_args.kwargs["options"]
    assert options.resume == "session-abc"
    sdk.query.assert_awaited_once_with("hello")
