# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for session_tracker module."""

from __future__ import annotations

import json
import time
from datetime import date
from pathlib import Path

import pytest

from personal_assistant_dashboard.session_tracker import (
    SessionData,
    aggregate,
    format_cost,
    format_duration_compact,
    format_reset_time,
    format_tokens,
    load_sessions,
    parse_session_file,
)

SAMPLE_SESSION = {
    "session_id": "abc-123",
    "cwd": "C:\\Users\\test\\source\\project",
    "model": {"id": "claude-opus-4-6[1m]", "display_name": "Opus 4.6 (1M context)"},
    "cost": {
        "total_cost_usd": 0.334,
        "total_duration_ms": 657847,
        "total_api_duration_ms": 77681,
        "total_lines_added": 68,
        "total_lines_removed": 1,
    },
    "context_window": {
        "total_input_tokens": 359,
        "total_output_tokens": 2447,
        "context_window_size": 1000000,
        "current_usage": {
            "input_tokens": 1,
            "output_tokens": 5,
            "cache_creation_input_tokens": 406,
            "cache_read_input_tokens": 35798,
        },
        "used_percentage": 4,
        "remaining_percentage": 96,
    },
    "rate_limits": {
        "five_hour": {"used_percentage": 47, "resets_at": 1775797200},
        "seven_day": {"used_percentage": 70, "resets_at": 1775858400},
    },
}


class TestParseSessionFile:
    def test_valid_session(self, tmp_path: Path) -> None:
        f = tmp_path / "session.json"
        f.write_text(json.dumps(SAMPLE_SESSION), encoding="utf-8")
        result = parse_session_file(f)
        assert result is not None
        assert result.session_id == "abc-123"
        assert result.model_display_name == "Opus 4.6 (1M context)"
        assert result.total_cost_usd == 0.334
        assert result.total_input_tokens == 359
        assert result.total_output_tokens == 2447
        assert result.context_used_pct == 4
        assert result.five_hour_pct == 47
        assert result.seven_day_pct == 70
        assert result.five_hour_resets_at == 1775797200
        assert result.seven_day_resets_at == 1775858400
        assert result.total_duration_ms == 657847
        assert result.lines_added == 68
        assert result.lines_removed == 1
        assert result.cwd == "C:\\Users\\test\\source\\project"

    def test_missing_fields_get_defaults(self, tmp_path: Path) -> None:
        f = tmp_path / "minimal.json"
        f.write_text(json.dumps({"session_id": "min-1"}), encoding="utf-8")
        result = parse_session_file(f)
        assert result is not None
        assert result.session_id == "min-1"
        assert result.total_cost_usd == 0.0
        assert result.total_input_tokens == 0
        assert result.model_display_name == "unknown"
        assert result.five_hour_pct == 0
        assert result.seven_day_pct == 0

    def test_explicit_none_values_default_to_zero(self, tmp_path: Path) -> None:
        data = {
            "session_id": "null-vals",
            "rate_limits": {
                "five_hour": {"used_percentage": None, "resets_at": None},
                "seven_day": {"used_percentage": None, "resets_at": None},
            },
            "context_window": {"used_percentage": None},
            "cost": {"total_cost_usd": None},
        }
        f = tmp_path / "nulls.json"
        f.write_text(json.dumps(data), encoding="utf-8")
        result = parse_session_file(f)
        assert result is not None
        assert result.five_hour_pct == 0
        assert result.seven_day_pct == 0
        assert result.context_used_pct == 0
        assert result.total_cost_usd == 0.0

    def test_malformed_json_returns_none(self, tmp_path: Path) -> None:
        f = tmp_path / "bad.json"
        f.write_text("not json", encoding="utf-8")
        assert parse_session_file(f) is None

    def test_nonexistent_file_returns_none(self, tmp_path: Path) -> None:
        assert parse_session_file(tmp_path / "nope.json") is None


class TestLoadSessions:
    def _write_session(
        self, base: Path, session_id: str, cwd: str = "C:\\project"
    ) -> None:
        data = {**SAMPLE_SESSION, "session_id": session_id, "cwd": cwd}
        (base / f"{session_id}.json").write_text(json.dumps(data), encoding="utf-8")

    def test_loads_all_sessions_from_date_dir(self, tmp_path: Path) -> None:
        day_dir = tmp_path / "2026-04-09"
        day_dir.mkdir()
        self._write_session(day_dir, "s1")
        self._write_session(day_dir, "s2")
        sessions = load_sessions(date(2026, 4, 9), tracker_root=tmp_path)
        assert len(sessions) == 2
        ids = {s.session_id for s in sessions}
        assert ids == {"s1", "s2"}

    def test_filters_by_cwd(self, tmp_path: Path) -> None:
        day_dir = tmp_path / "2026-04-09"
        day_dir.mkdir()
        self._write_session(day_dir, "s1", cwd="C:\\project-a")
        self._write_session(day_dir, "s2", cwd="C:\\project-b")
        sessions = load_sessions(
            date(2026, 4, 9), tracker_root=tmp_path, cwd_filter="C:\\project-a"
        )
        assert len(sessions) == 1
        assert sessions[0].session_id == "s1"

    def test_cwd_filter_normalizes_separators(self, tmp_path: Path) -> None:
        day_dir = tmp_path / "2026-04-09"
        day_dir.mkdir()
        self._write_session(day_dir, "s1", cwd="C:\\Users\\test\\project")
        sessions = load_sessions(
            date(2026, 4, 9), tracker_root=tmp_path, cwd_filter="C:/Users/test/project"
        )
        assert len(sessions) == 1

    def test_missing_date_dir_returns_empty(self, tmp_path: Path) -> None:
        sessions = load_sessions(date(2026, 4, 9), tracker_root=tmp_path)
        assert sessions == []

    def test_skips_malformed_files(self, tmp_path: Path) -> None:
        day_dir = tmp_path / "2026-04-09"
        day_dir.mkdir()
        self._write_session(day_dir, "s1")
        (day_dir / "bad.json").write_text("not json", encoding="utf-8")
        sessions = load_sessions(date(2026, 4, 9), tracker_root=tmp_path)
        assert len(sessions) == 1
        assert sessions[0].session_id == "s1"

    def test_sorted_by_session_id(self, tmp_path: Path) -> None:
        day_dir = tmp_path / "2026-04-09"
        day_dir.mkdir()
        self._write_session(day_dir, "zzz")
        self._write_session(day_dir, "aaa")
        sessions = load_sessions(date(2026, 4, 9), tracker_root=tmp_path)
        assert [s.session_id for s in sessions] == ["aaa", "zzz"]


class TestAggregate:
    def _make_session(self, **overrides: object) -> SessionData:
        defaults = {
            "session_id": "s1",
            "cwd": "",
            "model_id": "opus",
            "model_display_name": "Opus",
            "total_cost_usd": 0.10,
            "total_duration_ms": 1000,
            "total_api_duration_ms": 500,
            "lines_added": 10,
            "lines_removed": 2,
            "total_input_tokens": 100,
            "total_output_tokens": 50,
            "context_used_pct": 5,
            "five_hour_pct": 30,
            "five_hour_resets_at": 1775797200,
            "seven_day_pct": 60,
            "seven_day_resets_at": 1775858400,
            "mtime": 1000.0,
        }
        defaults.update(overrides)
        return SessionData(**defaults)  # type: ignore[arg-type]

    def test_empty_list(self) -> None:
        result = aggregate([])
        assert result.session_count == 0
        assert result.total_cost_usd == 0.0
        assert result.total_input_tokens == 0

    def test_single_session(self) -> None:
        s = self._make_session()
        result = aggregate([s])
        assert result.session_count == 1
        assert result.total_cost_usd == 0.10
        assert result.total_input_tokens == 100
        assert result.total_output_tokens == 50
        assert result.total_lines_added == 10
        assert result.total_lines_removed == 2
        assert result.current_context_pct == 5
        assert result.current_five_hour_pct == 30
        assert result.current_seven_day_pct == 60
        assert result.current_five_hour_reset == 1775797200
        assert result.current_seven_day_reset == 1775858400

    def test_rate_limits_come_from_newest_session(self) -> None:
        """Rate limits should come from the latest-mtime session, not max.

        An older session can show higher percentages from before a window
        reset. The newest file represents the current state.
        """
        old = self._make_session(
            session_id="old",
            total_cost_usd=0.10,
            total_input_tokens=100,
            total_output_tokens=50,
            lines_added=10,
            lines_removed=2,
            context_used_pct=40,
            five_hour_pct=95,  # pre-reset, near full
            seven_day_pct=80,
            five_hour_resets_at=1775797200,
            seven_day_resets_at=1775858400,
            mtime=1000.0,
        )
        new = self._make_session(
            session_id="new",
            total_cost_usd=0.25,
            total_input_tokens=200,
            total_output_tokens=100,
            lines_added=5,
            lines_removed=3,
            context_used_pct=15,
            five_hour_pct=20,  # fresh window
            seven_day_pct=40,
            five_hour_resets_at=1775815200,
            seven_day_resets_at=1775876400,
            mtime=2000.0,
        )
        result = aggregate([old, new])
        # Sums are cumulative across all sessions
        assert result.session_count == 2
        assert result.total_cost_usd == pytest.approx(0.35)
        assert result.total_input_tokens == 300
        assert result.total_output_tokens == 150
        assert result.total_lines_added == 15
        assert result.total_lines_removed == 5
        # Rate limits come from the newest session, not the max
        assert result.current_context_pct == 15
        assert result.current_five_hour_pct == 20
        assert result.current_seven_day_pct == 40
        assert result.current_five_hour_reset == 1775815200
        assert result.current_seven_day_reset == 1775876400

    def test_none_resets_at_preserved(self) -> None:
        s = self._make_session(five_hour_resets_at=None, seven_day_resets_at=None)
        result = aggregate([s])
        assert result.current_five_hour_reset is None
        assert result.current_seven_day_reset is None


class TestFormatHelpers:
    def test_format_cost_small(self) -> None:
        assert format_cost(0.00456) == "$0.005"

    def test_format_cost_normal(self) -> None:
        assert format_cost(0.334) == "$0.33"

    def test_format_cost_large(self) -> None:
        assert format_cost(12.5) == "$12.50"

    def test_format_cost_zero(self) -> None:
        assert format_cost(0.0) == "$0.00"

    def test_format_tokens_small(self) -> None:
        assert format_tokens(359) == "359"

    def test_format_tokens_thousands(self) -> None:
        assert format_tokens(2447) == "2.4K"

    def test_format_tokens_large(self) -> None:
        assert format_tokens(135000) == "135K"

    def test_format_tokens_millions(self) -> None:
        assert format_tokens(1_500_000) == "1.5M"

    def test_format_tokens_zero(self) -> None:
        assert format_tokens(0) == "0"

    def test_format_duration_seconds(self) -> None:
        assert format_duration_compact(45_000) == "45s"

    def test_format_duration_minutes(self) -> None:
        assert format_duration_compact(657_847) == "10m"

    def test_format_duration_hours(self) -> None:
        assert format_duration_compact(7_200_000) == "2h0m"

    def test_format_duration_zero(self) -> None:
        assert format_duration_compact(0) == "0s"

    def test_format_reset_time_none(self) -> None:
        assert format_reset_time(None) == ""

    def test_format_reset_time_future(self) -> None:
        future = int(time.time()) + 7200  # 2 hours from now
        result = format_reset_time(future)
        assert "h" in result or "m" in result

    def test_format_reset_time_past(self) -> None:
        result = format_reset_time(1000)
        assert result == "0s"

    def test_format_reset_time_under_hour_has_seconds(self) -> None:
        future = int(time.time()) + 1213  # 20m13s
        result = format_reset_time(future)
        assert "m" in result and result.endswith("s")
        assert "h" not in result

    def test_format_reset_time_over_hour_no_seconds(self) -> None:
        future = int(time.time()) + 3700  # 1h1m
        result = format_reset_time(future)
        assert "h" in result and result.endswith("m")
