# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for info_tab filtering logic."""

from __future__ import annotations

from personal_assistant_dashboard.info_tab import (
    InfoTab,
    _session_key,
    short_model_name,
)


class TestDropEmptyInactive:
    """Test InfoTab._drop_empty_inactive static method."""

    def test_drops_inactive_with_all_zero_metrics(self) -> None:
        sessions = [
            {
                "session_id": "empty",
                "is_active": False,
                "today_cost_usd": 0.0,
                "total_input_tokens": 0,
                "total_output_tokens": 0,
                "lines_added": 0,
                "lines_removed": 0,
            }
        ]
        assert InfoTab._drop_empty_inactive(sessions) == []

    def test_keeps_active_even_when_empty(self) -> None:
        """Active sessions are always shown — they may still be warming up."""
        sessions = [
            {
                "session_id": "warming",
                "is_active": True,
                "today_cost_usd": 0.0,
                "total_input_tokens": 0,
                "total_output_tokens": 0,
                "lines_added": 0,
                "lines_removed": 0,
            }
        ]
        assert len(InfoTab._drop_empty_inactive(sessions)) == 1

    def test_keeps_inactive_with_cost(self) -> None:
        sessions = [
            {"session_id": "s", "is_active": False, "today_cost_usd": 0.01},
        ]
        assert len(InfoTab._drop_empty_inactive(sessions)) == 1

    def test_keeps_inactive_with_input_tokens(self) -> None:
        sessions = [
            {"session_id": "s", "is_active": False, "total_input_tokens": 100},
        ]
        assert len(InfoTab._drop_empty_inactive(sessions)) == 1

    def test_keeps_inactive_with_output_tokens(self) -> None:
        sessions = [
            {"session_id": "s", "is_active": False, "total_output_tokens": 50},
        ]
        assert len(InfoTab._drop_empty_inactive(sessions)) == 1

    def test_context_pct_alone_is_not_enough(self) -> None:
        """Context % is not a data-bearing metric — inactive row still drops."""
        sessions = [
            {
                "session_id": "ctx-only",
                "is_active": False,
                "context_used_pct": 42,
                "today_cost_usd": 0.0,
                "total_input_tokens": 0,
                "total_output_tokens": 0,
                "lines_added": 0,
                "lines_removed": 0,
            }
        ]
        assert InfoTab._drop_empty_inactive(sessions) == []


class TestOrderSessions:
    """Test InfoTab._order_sessions: active rows always above inactive."""

    def test_active_always_above_inactive(self) -> None:
        sessions = [
            {"session_id": "inactive-cheap", "is_active": False, "today_cost_usd": 0.1},
            {
                "session_id": "active-expensive",
                "is_active": True,
                "today_cost_usd": 5.0,
            },
            {
                "session_id": "inactive-expensive",
                "is_active": False,
                "today_cost_usd": 9.0,
            },
            {"session_id": "active-cheap", "is_active": True, "today_cost_usd": 0.5},
        ]
        # Sort by cost descending — active group sits on top even though the
        # single most expensive row is inactive.
        result = InfoTab._order_sessions(sessions, "cost", reverse=True)
        ids = [s["session_id"] for s in result]
        assert ids == [
            "active-expensive",
            "active-cheap",
            "inactive-expensive",
            "inactive-cheap",
        ]

    def test_secondary_sort_applies_within_each_group(self) -> None:
        sessions = [
            {"session_id": "a-low", "is_active": True, "today_cost_usd": 1.0},
            {"session_id": "a-high", "is_active": True, "today_cost_usd": 3.0},
            {"session_id": "i-low", "is_active": False, "today_cost_usd": 0.5},
            {"session_id": "i-high", "is_active": False, "today_cost_usd": 10.0},
        ]
        result = InfoTab._order_sessions(sessions, "cost", reverse=False)
        ids = [s["session_id"] for s in result]
        assert ids == ["a-low", "a-high", "i-low", "i-high"]

    def test_no_sort_column_still_groups_active_first(self) -> None:
        sessions = [
            {"session_id": "i1", "is_active": False},
            {"session_id": "a1", "is_active": True},
            {"session_id": "i2", "is_active": False},
            {"session_id": "a2", "is_active": True},
        ]
        result = InfoTab._order_sessions(sessions, None, reverse=False)
        ids = [s["session_id"] for s in result]
        # Relative order within each group preserved (stable sort)
        assert ids == ["a1", "a2", "i1", "i2"]


class TestSessionKey:
    """Test _session_key helper used by the Session column."""

    def test_first_segment_with_double_dot(self) -> None:
        assert (
            _session_key({"session_id": "32beeba5-c9b0-4981-9b8f-acb1b572ae1e"})
            == "32beeba5.."
        )

    def test_short_session_id_uses_full_value(self) -> None:
        assert _session_key({"session_id": "abc"}) == "abc.."

    def test_em_dash_when_session_id_missing(self) -> None:
        assert _session_key({}) == "—"
        assert _session_key({"session_id": ""}) == "—"


class TestShortModelName:
    """Test short_model_name normalizes all source formats consistently."""

    # SDK format: claude-<family>-<major>-<minor>[<ctx>][-<date>]
    def test_sdk_opus_1m(self) -> None:
        assert short_model_name("claude-opus-4-7[1m]") == "opus-4.7-1m"

    def test_sdk_sonnet(self) -> None:
        assert short_model_name("claude-sonnet-4-6") == "sonnet-4.6"

    def test_sdk_haiku(self) -> None:
        assert short_model_name("claude-haiku-4-5") == "haiku-4.5"

    def test_sdk_dated_variant_stripped(self) -> None:
        assert short_model_name("claude-opus-4-7-20260401") == "opus-4.7"

    def test_sdk_dated_1m_variant(self) -> None:
        assert short_model_name("claude-opus-4-7[1m]-20260401") == "opus-4.7-1m"

    # CLI hook format: "Opus 4.6 (1M)" and "opus 4.6 (1m context)"
    def test_cli_opus_1m(self) -> None:
        assert short_model_name("Opus 4.6 (1M)") == "opus-4.6-1m"

    def test_cli_opus_1m_context(self) -> None:
        assert short_model_name("opus 4.6 (1m context)") == "opus-4.6-1m"

    def test_cli_sonnet(self) -> None:
        assert short_model_name("Sonnet 4.6") == "sonnet-4.6"

    # Raw/dash format: "opus-4.6-1m"
    def test_raw_opus_1m(self) -> None:
        assert short_model_name("opus-4.6-1m") == "opus-4.6-1m"

    def test_raw_sonnet(self) -> None:
        assert short_model_name("sonnet-4-6") == "sonnet-4.6"

    # All formats produce identical output
    def test_all_formats_converge(self) -> None:
        expected = "opus-4.6-1m"
        assert short_model_name("claude-opus-4-6[1m]") == expected
        assert short_model_name("Opus 4.6 (1M)") == expected
        assert short_model_name("opus 4.6 (1m context)") == expected
        assert short_model_name("opus-4.6-1m") == expected

    def test_empty_returns_em_dash(self) -> None:
        assert short_model_name("") == "—"
