# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for meet_collector module."""

from __future__ import annotations

import json
from unittest.mock import patch

import pytest

from personal_assistant_dashboard.collectors import meet_collector
from personal_assistant_dashboard.collectors.meet_collector import (
    _extract_meeting_code,
    _find_conference_names,
    _get_user_resource_id,
    _parse_ndjson,
    _user_in_conference,
    find_attended_event_ids,
)


@pytest.fixture(autouse=True)
def _clear_cache():
    """Reset cached user ID between tests."""
    meet_collector._cached_user_id = None
    yield
    meet_collector._cached_user_id = None


def _mock_result(stdout: str = "", stderr: str = "", returncode: int = 0):
    """Create a mock CompletedProcess."""
    from subprocess import CompletedProcess

    return CompletedProcess(
        args=[], returncode=returncode, stdout=stdout, stderr=stderr
    )


class TestParseNdjson:
    def test_single_json(self):
        stdout = json.dumps({"items": [{"id": 1}, {"id": 2}]})
        assert _parse_ndjson(stdout, "items") == [{"id": 1}, {"id": 2}]

    def test_ndjson_multiple_pages(self):
        page1 = json.dumps({"items": [{"id": 1}]})
        page2 = json.dumps({"items": [{"id": 2}, {"id": 3}]})
        stdout = f"{page1}\n{page2}"
        assert _parse_ndjson(stdout, "items") == [{"id": 1}, {"id": 2}, {"id": 3}]

    def test_empty_string(self):
        assert _parse_ndjson("", "items") == []

    def test_missing_key(self):
        stdout = json.dumps({"other": [1]})
        assert _parse_ndjson(stdout, "items") == []


class TestExtractMeetingCode:
    def test_standard_meet_url(self):
        assert (
            _extract_meeting_code("https://meet.google.com/abc-defg-hij")
            == "abc-defg-hij"
        )

    def test_no_match(self):
        assert _extract_meeting_code("https://zoom.us/j/123456") is None

    def test_empty_string(self):
        assert _extract_meeting_code("") is None

    def test_invalid_url(self):
        assert _extract_meeting_code("not a url") is None


class TestGetUserResourceId:
    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_returns_id(self, mock_cmd):
        mock_cmd.return_value = _mock_result(
            stdout=json.dumps(
                {
                    "resourceName": "people/12345",
                    "metadata": {},
                }
            )
        )
        assert _get_user_resource_id() == "12345"

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_caches_result(self, mock_cmd):
        mock_cmd.return_value = _mock_result(
            stdout=json.dumps({"resourceName": "people/99999"})
        )
        _get_user_resource_id()
        _get_user_resource_id()
        assert mock_cmd.call_count == 1

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_failure_returns_none(self, mock_cmd):
        mock_cmd.return_value = _mock_result(returncode=1)
        assert _get_user_resource_id() is None


class TestFindConferenceNames:
    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_returns_all_records(self, mock_cmd):
        mock_cmd.return_value = _mock_result(
            stdout=json.dumps(
                {
                    "conferenceRecords": [
                        {
                            "name": "conferenceRecords/active",
                            "startTime": "2026-04-07T10:00:00Z",
                        },
                        {
                            "name": "conferenceRecords/ended",
                            "startTime": "2026-04-07T09:00:00Z",
                            "endTime": "2026-04-07T09:30:00Z",
                        },
                    ]
                }
            )
        )
        result = _find_conference_names("abc-defg-hij")
        assert result == [
            "conferenceRecords/active",
            "conferenceRecords/ended",
        ]

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_ended_conference_included(self, mock_cmd):
        """Ended conferences must be included — the user may have left early."""
        mock_cmd.return_value = _mock_result(
            stdout=json.dumps(
                {
                    "conferenceRecords": [
                        {
                            "name": "conferenceRecords/ended",
                            "startTime": "2026-04-07T10:00:00Z",
                            "endTime": "2026-04-07T10:30:00Z",
                        },
                    ]
                }
            )
        )
        result = _find_conference_names("abc-defg-hij")
        assert result == ["conferenceRecords/ended"]

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_no_records(self, mock_cmd):
        mock_cmd.return_value = _mock_result(stdout=json.dumps({}))
        assert _find_conference_names("abc-defg-hij") == []

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_api_failure(self, mock_cmd):
        mock_cmd.return_value = _mock_result(returncode=1, stderr="error")
        assert _find_conference_names("abc-defg-hij") == []

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_page_all_flag_passed(self, mock_cmd):
        mock_cmd.return_value = _mock_result(stdout=json.dumps({}))
        _find_conference_names("abc-defg-hij")
        cmd_args = mock_cmd.call_args[0][0]
        assert "--page-all" in cmd_args

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_ndjson_multiple_pages(self, mock_cmd):
        page1 = json.dumps({"conferenceRecords": [{"name": "conferenceRecords/a"}]})
        page2 = json.dumps({"conferenceRecords": [{"name": "conferenceRecords/b"}]})
        mock_cmd.return_value = _mock_result(stdout=f"{page1}\n{page2}")
        result = _find_conference_names("abc-defg-hij")
        assert result == ["conferenceRecords/a", "conferenceRecords/b"]


class TestUserInConference:
    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_user_present(self, mock_cmd):
        mock_cmd.return_value = _mock_result(
            stdout=json.dumps(
                {
                    "participants": [
                        {
                            "signedinUser": {
                                "user": "users/12345",
                                "displayName": "Test User",
                            },
                            "earliestStartTime": "2026-04-07T10:00:00Z",
                        },
                    ]
                }
            )
        )
        assert _user_in_conference("conferenceRecords/abc", "12345") is True

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_user_not_present(self, mock_cmd):
        mock_cmd.return_value = _mock_result(
            stdout=json.dumps(
                {
                    "participants": [
                        {
                            "signedinUser": {
                                "user": "users/99999",
                                "displayName": "Other",
                            },
                        },
                    ]
                }
            )
        )
        assert _user_in_conference("conferenceRecords/abc", "12345") is False

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_empty_participants(self, mock_cmd):
        mock_cmd.return_value = _mock_result(stdout=json.dumps({}))
        assert _user_in_conference("conferenceRecords/abc", "12345") is False

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_page_all_flag_passed(self, mock_cmd):
        mock_cmd.return_value = _mock_result(stdout=json.dumps({}))
        _user_in_conference("conferenceRecords/abc", "12345")
        cmd_args = mock_cmd.call_args[0][0]
        assert "--page-all" in cmd_args

    @patch("personal_assistant_dashboard.collectors.meet_collector.run_cmd")
    def test_ndjson_user_on_second_page(self, mock_cmd):
        page1 = json.dumps(
            {
                "participants": [
                    {"signedinUser": {"user": "users/99999"}},
                ]
            }
        )
        page2 = json.dumps(
            {
                "participants": [
                    {"signedinUser": {"user": "users/12345"}},
                ]
            }
        )
        mock_cmd.return_value = _mock_result(stdout=f"{page1}\n{page2}")
        assert _user_in_conference("conferenceRecords/abc", "12345") is True


class TestFindAttendedEventIds:
    """End-to-end tests for the missed-meeting suppression logic.

    These mock the internal helpers to verify the orchestration in
    find_attended_event_ids — particularly that ended conferences
    are checked and that attendance in ANY record suppresses the alert.
    """

    @patch("personal_assistant_dashboard.collectors.meet_collector._user_in_conference")
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._find_conference_names"
    )
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._get_user_resource_id"
    )
    def test_attended_active_conference(self, mock_user_id, mock_confs, mock_in_conf):
        mock_user_id.return_value = "12345"
        mock_confs.return_value = ["conferenceRecords/abc"]
        mock_in_conf.return_value = True
        events = [
            {
                "id": "evt1",
                "summary": "Standup",
                "hangout_link": "https://meet.google.com/abc-defg-hij",
            }
        ]
        assert find_attended_event_ids(events) == {"evt1"}

    @patch("personal_assistant_dashboard.collectors.meet_collector._user_in_conference")
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._find_conference_names"
    )
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._get_user_resource_id"
    )
    def test_attended_ended_conference(self, mock_user_id, mock_confs, mock_in_conf):
        """User left early — conference ended but user was a participant."""
        mock_user_id.return_value = "12345"
        mock_confs.return_value = ["conferenceRecords/ended"]
        mock_in_conf.return_value = True
        events = [
            {
                "id": "evt1",
                "summary": "Standup",
                "hangout_link": "https://meet.google.com/abc-defg-hij",
            }
        ]
        assert find_attended_event_ids(events) == {"evt1"}

    @patch("personal_assistant_dashboard.collectors.meet_collector._user_in_conference")
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._find_conference_names"
    )
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._get_user_resource_id"
    )
    def test_attended_second_conference_record(
        self, mock_user_id, mock_confs, mock_in_conf
    ):
        """User wasn't in first record but was in second — still suppressed."""
        mock_user_id.return_value = "12345"
        mock_confs.return_value = [
            "conferenceRecords/first",
            "conferenceRecords/second",
        ]
        mock_in_conf.side_effect = [False, True]
        events = [
            {
                "id": "evt1",
                "hangout_link": "https://meet.google.com/abc-defg-hij",
            }
        ]
        assert find_attended_event_ids(events) == {"evt1"}

    @patch("personal_assistant_dashboard.collectors.meet_collector._user_in_conference")
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._find_conference_names"
    )
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._get_user_resource_id"
    )
    def test_not_in_any_conference(self, mock_user_id, mock_confs, mock_in_conf):
        """User never joined — alert should fire."""
        mock_user_id.return_value = "12345"
        mock_confs.return_value = [
            "conferenceRecords/first",
            "conferenceRecords/second",
        ]
        mock_in_conf.return_value = False
        events = [
            {
                "id": "evt1",
                "hangout_link": "https://meet.google.com/abc-defg-hij",
            }
        ]
        assert find_attended_event_ids(events) == set()

    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._get_user_resource_id"
    )
    def test_no_meet_links(self, mock_user_id):
        events = [{"id": "evt1", "summary": "No meet"}]
        assert find_attended_event_ids(events) == set()
        mock_user_id.assert_not_called()

    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._find_conference_names"
    )
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._get_user_resource_id"
    )
    def test_no_conference_records(self, mock_user_id, mock_confs):
        """No conference records at all — meeting never started on Meet."""
        mock_user_id.return_value = "12345"
        mock_confs.return_value = []
        events = [
            {
                "id": "evt1",
                "hangout_link": "https://meet.google.com/abc-defg-hij",
            }
        ]
        assert find_attended_event_ids(events) == set()

    @patch("personal_assistant_dashboard.collectors.meet_collector._user_in_conference")
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._find_conference_names"
    )
    @patch(
        "personal_assistant_dashboard.collectors.meet_collector._get_user_resource_id"
    )
    def test_stops_checking_after_first_match(
        self, mock_user_id, mock_confs, mock_in_conf
    ):
        """Once attendance is found, skip remaining conference records."""
        mock_user_id.return_value = "12345"
        mock_confs.return_value = [
            "conferenceRecords/first",
            "conferenceRecords/second",
            "conferenceRecords/third",
        ]
        mock_in_conf.return_value = True
        events = [
            {
                "id": "evt1",
                "hangout_link": "https://meet.google.com/abc-defg-hij",
            }
        ]
        find_attended_event_ids(events)
        # Should only check the first record then break
        mock_in_conf.assert_called_once_with("conferenceRecords/first", "12345")
