# Generated By: Claude Code (claude-opus-5-5[1m])
"""Tests for the `pa show` socket."""

from __future__ import annotations

import sys
import threading
from io import StringIO
from pathlib import Path
from unittest.mock import patch

import pytest

from personal_assistant_dashboard import ipc


def test_parse_request() -> None:
    assert ipc.parse_request("show") is None
    assert ipc.parse_request("show 1\n") == 1
    for bad in ["", "hide 1", "show x", "show 1 2"]:
        with pytest.raises(ValueError):
            ipc.parse_request(bad)


def test_round_trip(tmp_path: Path) -> None:
    path = tmp_path / "pa.sock"
    received: list[int | None] = []
    done = threading.Event()

    def on_show(tab: int | None) -> None:
        received.append(tab)
        done.set()

    server = ipc.serve(on_show, path)
    try:
        assert ipc.send_show(1, path) == "ok"
        assert done.wait(2)
        assert ipc.send_show(None, path) == "ok"
        assert received == [1, None]
    finally:
        ipc.close(server, path)
    assert not path.exists()


def test_serve_replaces_stale_socket(tmp_path: Path) -> None:
    path = tmp_path / "pa.sock"
    path.write_text("stale")
    server = ipc.serve(lambda tab: None, path)
    try:
        assert ipc.send_show(0, path) == "ok"
    finally:
        ipc.close(server, path)


def test_survives_client_that_hangs_up(tmp_path: Path) -> None:
    import socket

    path = tmp_path / "pa.sock"
    server = ipc.serve(lambda tab: None, path)
    try:
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as rude:
            rude.connect(str(path))
            rude.sendall(b"show 1")
        assert ipc.send_show(2, path) == "ok"
    finally:
        ipc.close(server, path)


def test_send_show_not_running(tmp_path: Path) -> None:
    with pytest.raises(OSError):
        ipc.send_show(1, tmp_path / "missing.sock")


def test_cli_show_not_running(tmp_path: Path) -> None:
    from personal_assistant_dashboard.__main__ import main

    err = StringIO()
    with (
        patch.object(ipc, "SOCKET_PATH", tmp_path / "missing.sock"),
        patch.object(sys, "argv", ["pa", "show", "1"]),
        patch("sys.stderr", err),
        pytest.raises(SystemExit) as exc,
    ):
        main()
    assert exc.value.code == 1
    assert "not running" in err.getvalue()


def _completed(stdout: str = "", returncode: int = 0) -> object:
    import subprocess

    return subprocess.CompletedProcess([], returncode, stdout=stdout, stderr="")


_LISTED = (
    '(\'[{"id":7,"pid":99,"title":"Bob\\\'s terminal"},'
    '{"id":42,"pid":123,"title":"PA — Dashboard"}]\',)'
)


def test_activate_window_activates_matching_id() -> None:
    with patch.object(
        ipc, "run_cmd", side_effect=[_completed(_LISTED), _completed()]
    ) as run:
        assert ipc.activate_window("PA — Dashboard")
    assert run.call_args_list[1].args[0][-2:] == [
        "org.gnome.Shell.Extensions.Windows.Activate",
        "42",
    ]


def test_activate_window_double_quoted_gvariant() -> None:
    listed = '("[{\\"id\\":42,\\"pid\\":123,\\"title\\":\\"PA — Dashboard\\"}]",)'
    with patch.object(ipc, "run_cmd", side_effect=[_completed(listed), _completed()]):
        assert ipc.activate_window("PA — Dashboard")


def test_activate_window_no_match() -> None:
    with patch.object(ipc, "run_cmd", return_value=_completed(_LISTED)) as run:
        assert not ipc.activate_window("Other")
    assert run.call_count == 1  # List only, never Activate


def test_activate_window_unavailable() -> None:
    with patch.object(ipc, "run_cmd", side_effect=FileNotFoundError("gdbus")):
        assert not ipc.activate_window("PA — Dashboard")
    with patch.object(ipc, "run_cmd", return_value=_completed(returncode=1)):
        assert not ipc.activate_window("PA — Dashboard")
    with patch.object(ipc, "run_cmd", return_value=_completed("garbage")):
        assert not ipc.activate_window("PA — Dashboard")
