# Generated By: Claude Code (Claude Opus 4.6)
"""CLI entry point for the personal assistant.

Dispatches to subcommands: state, track, collect, analyze, digest, gui.
"""

from __future__ import annotations

import argparse
import logging
import logging.handlers
import os
import sys
from pathlib import Path
from typing import Any

from personal_assistant_dashboard import state_repo, config_manager
from personal_assistant_dashboard.collectors import calendar_collector
from personal_assistant_dashboard.analyzers import calendar_analyzer
from personal_assistant_dashboard.config import SCOPE_CHECK_DELAY_MS


def _add_repo_path_arg(parser: argparse.ArgumentParser) -> None:
    """Add the --state-path argument to a parser."""
    parser.add_argument(
        "--state-path",
        type=Path,
        default=state_repo.DEFAULT_STATE_PATH,
        help="path to the state repo (default: %(default)s)",
    )


def _cmd_state_init(args: argparse.Namespace) -> None:
    path = state_repo.init_repo(path=args.state_path)
    print(f"State repo initialized at {path}")


def _cmd_state_status(args: argparse.Namespace) -> None:
    print(state_repo.status_summary(repo_path=args.state_path))


def _cmd_state_commit(args: argparse.Namespace) -> None:
    message = args.message or "manual checkpoint"
    created = state_repo.commit_state(message, repo_path=args.state_path)
    if created:
        print(f"Committed: {message}")
    else:
        print("Nothing to commit")


def _cmd_track_add(args: argparse.Namespace) -> None:
    config_manager.add_jira_tracking(
        args.key, tier=args.tier, repo_path=args.state_path
    )
    print(f"Tracking {args.key} (tier={args.tier})")


def _cmd_track_remove(args: argparse.Namespace) -> None:
    removed = config_manager.remove_jira_tracking(args.key, repo_path=args.state_path)
    if removed:
        print(f"Removed {args.key}")
    else:
        print(f"{args.key} not found in tracking config")


def _cmd_track_repo(args: argparse.Namespace) -> None:
    config_manager.add_github_repo(args.repo, repo_path=args.state_path)
    print(f"Tracking GitHub repo: {args.repo}")


def _cmd_track_list(args: argparse.Namespace) -> None:
    print(config_manager.format_tracking_list(repo_path=args.state_path))


def _cmd_track_calendars(args: argparse.Namespace) -> None:
    calendars = calendar_collector.list_available_calendars()
    print(calendar_collector.format_calendar_list(calendars))
    print()
    print("To add a calendar: pa track calendar <calendar-id>")
    print('The "primary" keyword refers to your main calendar.')


def _cmd_track_calendar_add(args: argparse.Namespace) -> None:
    config_manager.add_calendar(args.calendar_id, repo_path=args.state_path)
    print(f"Added calendar: {args.calendar_id}")


def _cmd_track_calendar_remove(args: argparse.Namespace) -> None:
    removed = config_manager.remove_calendar(
        args.calendar_id, repo_path=args.state_path
    )
    if removed:
        print(f"Removed calendar: {args.calendar_id}")
    else:
        print(f"{args.calendar_id} not found in tracking config")


def _cmd_collect_calendar(args: argparse.Namespace) -> None:
    config = config_manager.load_config(repo_path=args.state_path)
    calendar_ids = config.get("calendars", ["primary"])
    results = calendar_collector.collect_all_calendars(
        calendar_ids, days_ahead=args.days, repo_path=args.state_path
    )
    total = sum(len(events) for events in results.values())
    print(f"Collected {total} events from {len(results)} calendar(s)")


def _cmd_analyze_calendar(args: argparse.Namespace) -> None:
    analyses = calendar_analyzer.analyze_all_calendars(repo_path=args.state_path)
    if not analyses:
        print("No calendar data found. Run 'pa collect calendar' first.")
        return
    for analysis in analyses:
        print(calendar_analyzer.format_analysis(analysis))
        print()


def _cmd_gui(args: argparse.Namespace) -> None:
    # Windows DPI awareness — must be called before Tk() is created
    if sys.platform == "win32":
        try:
            import ctypes

            ctypes.windll.shcore.SetProcessDpiAwareness(1)
        except Exception:
            pass

    import tkinter as tk
    from personal_assistant_dashboard.dashboard import Dashboard

    state_path = getattr(args, "state_path", state_repo.DEFAULT_STATE_PATH)

    root = tk.Tk()
    root.withdraw()

    dashboard = Dashboard(root, state_path=state_path, on_quit=root.quit)
    dashboard.show()

    # Auto-refresh and scope check on launch
    root.after(100, dashboard.refresh)
    root.after(SCOPE_CHECK_DELAY_MS, dashboard._check_scopes)

    root.mainloop()


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="pa",
        description="Personal Assistant — context-aware state monitor",
    )
    parser.add_argument("--debug", action="store_true", help="enable debug logging")
    subparsers = parser.add_subparsers(dest="command")

    # --- state ---
    state_parser = subparsers.add_parser("state", help="manage the state repo")
    state_sub = state_parser.add_subparsers(dest="state_command")

    state_init = state_sub.add_parser("init", help="initialize the state repo")
    _add_repo_path_arg(state_init)
    state_init.set_defaults(func=_cmd_state_init)

    state_status = state_sub.add_parser("status", help="show state repo status")
    _add_repo_path_arg(state_status)
    state_status.set_defaults(func=_cmd_state_status)

    state_commit = state_sub.add_parser("commit", help="commit current state")
    state_commit.add_argument("-m", "--message", help="commit message")
    _add_repo_path_arg(state_commit)
    state_commit.set_defaults(func=_cmd_state_commit)

    # --- track ---
    track_parser = subparsers.add_parser("track", help="manage what to track")
    track_sub = track_parser.add_subparsers(dest="track_command")

    track_add = track_sub.add_parser("add", help="track a Jira epic")
    track_add.add_argument("key", help="Jira issue key (e.g., ANSTRAT-1900)")
    track_add.add_argument(
        "--tier",
        choices=["awareness", "active"],
        default="awareness",
        help="tracking depth (default: awareness)",
    )
    _add_repo_path_arg(track_add)
    track_add.set_defaults(func=_cmd_track_add)

    track_remove = track_sub.add_parser("remove", help="stop tracking a Jira epic")
    track_remove.add_argument("key", help="Jira issue key")
    _add_repo_path_arg(track_remove)
    track_remove.set_defaults(func=_cmd_track_remove)

    track_repo_cmd = track_sub.add_parser("repo", help="track a GitHub repo")
    track_repo_cmd.add_argument("repo", help="GitHub repo (e.g., owner/repo-name)")
    _add_repo_path_arg(track_repo_cmd)
    track_repo_cmd.set_defaults(func=_cmd_track_repo)

    track_list = track_sub.add_parser("list", help="show tracked items")
    _add_repo_path_arg(track_list)
    track_list.set_defaults(func=_cmd_track_list)

    track_calendars = track_sub.add_parser(
        "calendars", help="list available Google calendars"
    )
    track_calendars.set_defaults(func=_cmd_track_calendars)

    track_cal_add = track_sub.add_parser("calendar", help="add a calendar to track")
    track_cal_add.add_argument(
        "calendar_id", help="calendar ID (use 'pa track calendars' to discover)"
    )
    _add_repo_path_arg(track_cal_add)
    track_cal_add.set_defaults(func=_cmd_track_calendar_add)

    track_cal_remove = track_sub.add_parser(
        "uncalendar", help="remove a tracked calendar"
    )
    track_cal_remove.add_argument("calendar_id", help="calendar ID to remove")
    _add_repo_path_arg(track_cal_remove)
    track_cal_remove.set_defaults(func=_cmd_track_calendar_remove)

    # --- collect ---
    collect_parser = subparsers.add_parser("collect", help="collect data from sources")
    collect_sub = collect_parser.add_subparsers(dest="collect_command")

    collect_cal = collect_sub.add_parser("calendar", help="collect calendar events")
    collect_cal.add_argument(
        "--days", type=int, default=7, help="days ahead to fetch (default: 7)"
    )
    _add_repo_path_arg(collect_cal)
    collect_cal.set_defaults(func=_cmd_collect_calendar)

    # --- analyze ---
    analyze_parser = subparsers.add_parser("analyze", help="analyze collected data")
    analyze_sub = analyze_parser.add_subparsers(dest="analyze_command")

    analyze_cal = analyze_sub.add_parser("calendar", help="analyze calendar changes")
    _add_repo_path_arg(analyze_cal)
    analyze_cal.set_defaults(func=_cmd_analyze_calendar)

    # --- gui ---
    gui_parser = subparsers.add_parser("gui", help="launch the dashboard")
    gui_parser.add_argument(
        "--log-file", type=str, default=None, help="write log output to file"
    )
    _add_repo_path_arg(gui_parser)
    gui_parser.set_defaults(func=_cmd_gui)

    # --- parse and dispatch ---
    args = parser.parse_args()

    level = logging.DEBUG if args.debug else logging.INFO
    log_fmt = "%(asctime)s %(levelname)s %(name)s: %(message)s"
    log_file = getattr(args, "log_file", None)
    if log_file:
        os.makedirs(os.path.dirname(os.path.abspath(log_file)), exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            log_file,
            maxBytes=2 * 1024 * 1024,
            backupCount=1,
            encoding="utf-8",
        )
        handler.setFormatter(logging.Formatter(log_fmt))
        logging.basicConfig(level=level, handlers=[handler])
    else:
        logging.basicConfig(level=level, format=log_fmt, stream=sys.stderr)

    # Route uncaught exceptions to log file
    if log_file:
        _logger = logging.getLogger("personal_assistant_dashboard")

        def _excepthook(
            exc_type: type[BaseException],
            exc_value: BaseException,
            exc_tb: Any,
        ) -> None:
            if issubclass(exc_type, KeyboardInterrupt):
                sys.__excepthook__(exc_type, exc_value, exc_tb)
                return
            _logger.critical(
                "uncaught exception", exc_info=(exc_type, exc_value, exc_tb)
            )

        sys.excepthook = _excepthook

    if not hasattr(args, "func"):
        parser.print_help()
        sys.exit(1)

    args.func(args)


if __name__ == "__main__":
    main()
