# Generated By: Claude Code (Claude Opus 4.7)
"""Forward SDK chat session usage to AgentPulse's statusline endpoint.

Claude Agent SDK ``ResultMessage`` payloads are per-query, but
AgentPulse's ``/statusline/claude`` endpoint expects session-cumulative
totals in the same nested shape the Claude Code CLI's statusline hook
emits. ``SessionAccumulator`` sums per-query values across a session;
``build_payload`` produces the dict to POST; ``post_statusline`` does
the HTTP POST with errors swallowed so a down AgentPulse never breaks
the chat flow.
"""

from __future__ import annotations

import json
import logging
import re
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from personal_assistant_dashboard.agentpulse_config import (
    CONFIG_PATH,
    HTTP_TIMEOUT_S,
    load_agentpulse_config,
)

logger = logging.getLogger(__name__)

DEFAULT_CONTEXT_WINDOW = 200_000
_1M_CONTEXT_WINDOW = 1_000_000

# Matches any Claude model id containing a ``[1m]`` context-window tag,
# with optional dated suffix. Structural — no per-model enumeration.
_1M_RE = re.compile(r"\[1m\]")


def lookup_context_window(model_name: str) -> int:
    """Return the context window size for a Claude model.

    Any model whose id contains ``[1m]`` gets 1M; all others get 200k.
    Unknown or empty names fall back to ``DEFAULT_CONTEXT_WINDOW`` and
    emit a warning so the lookup table can be updated.
    """
    if not model_name:
        return DEFAULT_CONTEXT_WINDOW
    if _1M_RE.search(model_name):
        return _1M_CONTEXT_WINDOW
    if re.match(r"^claude-", model_name):
        return DEFAULT_CONTEXT_WINDOW
    logger.warning(
        "unknown Claude model %r; defaulting context window to %d",
        model_name,
        DEFAULT_CONTEXT_WINDOW,
    )
    return DEFAULT_CONTEXT_WINDOW


def extract_model_name(model_usage: dict[str, Any] | None) -> str:
    """Pull the model identifier out of a ``ResultMessage.model_usage`` dict.

    The SDK forwards the CLI's ``model_usage`` map keyed by model id.
    When multiple models appear (rare), the one with the most output
    tokens wins. Model id is used as the deterministic tiebreaker when
    token counts are equal (or absent) so the result doesn't depend on
    dict iteration order.
    """
    if not model_usage:
        return ""
    if len(model_usage) == 1:
        return next(iter(model_usage))

    def _output_tokens(value: Any) -> int:
        if isinstance(value, dict):
            return int(value.get("outputTokens") or 0)
        return 0

    # Sort by output tokens descending; tiebreak on model id ascending so
    # the winner is deterministic when outputs tie (e.g. both zero).
    return sorted(
        model_usage.items(),
        key=lambda kv: (-_output_tokens(kv[1]), kv[0]),
    )[
        0
    ][0]


class SessionAccumulator:
    """Accumulate per-query usage into session-scoped totals.

    Counters grow monotonically within a session. Unlike the CLI (where
    ``/clear`` preserves process-scoped totals because the subprocess
    stays alive), the dashboard's clear tears down the SDK subprocess
    and spawns a new one — a new PID, a new process from AgentPulse's
    perspective. Call ``reset()`` on clear so each session starts fresh.
    """

    def __init__(self) -> None:
        self.session_id: str = ""
        self.total_cost_usd: float = 0.0
        self.total_input_tokens: int = 0
        self.total_output_tokens: int = 0
        self.total_duration_ms: int = 0
        self.total_api_duration_ms: int = 0
        # Snapshot of the most recent turn's usage — used for
        # ``used_percentage`` which must reflect *current* context size,
        # not lifetime totals. Cumulative counters above grow without
        # bound and can't represent present context window occupancy.
        self.last_input_tokens: int = 0
        self.last_cache_read_tokens: int = 0
        self.last_cache_creation_tokens: int = 0
        self.last_model_name: str = ""

    def record_result(
        self,
        *,
        session_id: str,
        total_cost_usd: float | None,
        usage: dict[str, Any] | None,
        duration_ms: int,
        duration_api_ms: int,
        model_name: str = "",
    ) -> None:
        """Accumulate lifetime counters from a ``ResultMessage``.

        The CLI's ``ResultMessage.usage`` is aggregated across every API
        call in the turn (tool loops produce many calls), so its token
        counts are sums — appropriate for lifetime totals but NOT for
        representing current context size. Use ``record_turn_snapshot``
        for the per-call snapshot that feeds ``used_percentage``.
        """
        self.session_id = session_id
        if total_cost_usd is not None:
            self.total_cost_usd += float(total_cost_usd)
        self.total_duration_ms += int(duration_ms or 0)
        self.total_api_duration_ms += int(duration_api_ms or 0)
        if usage:
            self.total_input_tokens += int(usage.get("input_tokens") or 0)
            self.total_output_tokens += int(usage.get("output_tokens") or 0)
        if model_name:
            self.last_model_name = model_name

    def reset(self) -> None:
        """Zero all counters — call on clear (new subprocess = new process)."""
        self.session_id = ""
        self.total_cost_usd = 0.0
        self.total_input_tokens = 0
        self.total_output_tokens = 0
        self.total_duration_ms = 0
        self.total_api_duration_ms = 0
        self.reset_snapshot()

    def reset_snapshot(self) -> None:
        """Zero the per-turn snapshot so context % reads 0 until the next turn."""
        logger.debug("snapshot reset to zero")
        self.last_input_tokens = 0
        self.last_cache_read_tokens = 0
        self.last_cache_creation_tokens = 0

    def record_turn_snapshot(self, usage: dict[str, Any] | None) -> None:
        """Record per-API-call usage from the turn's last AssistantMessage.

        This is the single-call view — input + cache_read + cache_creation
        from one API request — so it cannot exceed the context window and
        correctly represents present context occupancy.
        """
        if not usage:
            logger.debug("snapshot: no usage provided, keeping previous values")
            return
        self.last_input_tokens = int(usage.get("input_tokens") or 0)
        self.last_cache_read_tokens = int(usage.get("cache_read_input_tokens") or 0)
        self.last_cache_creation_tokens = int(
            usage.get("cache_creation_input_tokens") or 0
        )
        logger.debug(
            "snapshot: input=%d cache_read=%d cache_create=%d",
            self.last_input_tokens,
            self.last_cache_read_tokens,
            self.last_cache_creation_tokens,
        )


def build_payload(
    acc: SessionAccumulator,
    *,
    pid: int,
    cwd: str,
    source_system: str,
) -> dict[str, Any]:
    """Build the statusline JSON body AgentPulse expects.

    Leaves ``cost.total_lines_added`` and ``cost.total_lines_removed``
    unset — the SDK doesn't expose tool-result diff counts.
    """
    window_size = lookup_context_window(acc.last_model_name)
    # ``used_percentage`` reflects the most recent turn's context size,
    # matching the CLI statusline hook's semantics. Using cumulative
    # ``total_input_tokens`` here would grow without bound and push the
    # percentage past 100% over a long-lived process.
    ctx_used = (
        acc.last_input_tokens
        + acc.last_cache_read_tokens
        + acc.last_cache_creation_tokens
    )
    used_pct = (ctx_used / window_size * 100) if window_size else 0.0
    logger.debug(
        "context %%: model=%s window=%d input=%d cache_read=%d "
        "cache_create=%d total=%d pct=%.1f",
        acc.last_model_name,
        window_size,
        acc.last_input_tokens,
        acc.last_cache_read_tokens,
        acc.last_cache_creation_tokens,
        ctx_used,
        used_pct,
    )
    return {
        "session_id": acc.session_id,
        "pid": pid,
        "source_system": source_system,
        "workspace": {"project_dir": cwd},
        "cost": {
            "total_cost_usd": acc.total_cost_usd,
            "total_duration_ms": acc.total_duration_ms,
            "total_api_duration_ms": acc.total_api_duration_ms,
        },
        "context_window": {
            "total_input_tokens": acc.total_input_tokens,
            "total_output_tokens": acc.total_output_tokens,
            "used_percentage": round(used_pct, 1),
            "context_window_size": window_size,
            "current_usage": {
                "input_tokens": acc.last_input_tokens,
                "cache_read_input_tokens": acc.last_cache_read_tokens,
                "cache_creation_input_tokens": acc.last_cache_creation_tokens,
            },
        },
        "model": {"display_name": acc.last_model_name},
    }


def load_agentpulse_endpoint(
    path: Path = CONFIG_PATH,
) -> tuple[str, int] | None:
    """Read AgentPulse host/port from its config file.

    Thin adapter over ``load_agentpulse_config`` — returns just the
    ``(host, port)`` tuple the statusline forwarder needs. Returns
    ``None`` when the file is missing, malformed, or lacks required
    keys; forwarding is silently skipped in that case.
    """
    config = load_agentpulse_config(path)
    if config is None:
        return None
    return (config.host, config.port)


def post_statusline(host: str, port: int, payload: dict[str, Any]) -> bool:
    """POST a statusline payload to AgentPulse. Returns True on HTTP 200."""
    url = f"http://{host}:{port}/statusline/claude"
    body = json.dumps(payload).encode("utf-8")
    session_id = payload.get("session_id", "?")
    req = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT_S) as resp:
            status = int(resp.status)
            if 200 <= status < 300:
                return True
            _log_post_failure(session_id, f"HTTP {status}", payload)
            return False
    except urllib.error.HTTPError as exc:
        _log_post_failure(session_id, f"HTTPError {exc.code}: {exc}", payload)
        return False
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        _log_post_failure(session_id, f"{url} failed: {exc}", payload)
        return False


def _log_post_failure(session_id: str, reason: str, payload: dict[str, Any]) -> None:
    """Emit DEBUG logs for a failed statusline POST.

    Two records: one summarising the failure, one dumping the payload
    that was sent. Splitting them keeps the primary log line short while
    still preserving the full payload for post-mortem analysis when
    DEBUG is enabled.
    """
    logger.debug("statusline POST session=%s failed: %s", session_id, reason)
    logger.debug("statusline POST session=%s payload=%s", session_id, payload)


class SeedResult:
    """Outcome of a one-shot seed attempt against AgentPulse.

    ``ok`` is True when the accumulator may now be POSTed. This covers
    two sub-cases:

    - ``merged=True``: AgentPulse returned a record for this session.
      Any non-null stored totals were *added* to the accumulator's
      local values so the resulting counters represent (prior persisted)
      + (locally accumulated while offline). A response with every
      numeric field null still reports ``merged=True`` — AgentPulse had
      the session but had nothing to contribute.
    - ``merged=False``: AgentPulse was reachable but had no record of
      this session (HTTP 404, or an unexpected response body). The
      accumulator is left untouched — its local values are already
      authoritative.

    ``ok`` is False only when AgentPulse was unreachable or returned an
    unexpected error (5xx, connection refused, timeout, malformed body,
    non-numeric totals). The caller must not POST in that state; the
    accumulator keeps growing locally until a later seed attempt
    succeeds.
    """

    __slots__ = ("ok", "merged")

    def __init__(self, *, ok: bool, merged: bool) -> None:
        self.ok = ok
        self.merged = merged


def merge_agentpulse_seed(
    acc: SessionAccumulator,
    host: str,
    port: int,
    session_id: str,
) -> SeedResult:
    """Add AgentPulse's stored session totals to ``acc`` (one-shot).

    Designed to run exactly once per process lifetime, the first time
    AgentPulse is reachable after startup. The accumulator may already
    contain local counters from ResultMessages received while AgentPulse
    was offline; those counters are preserved and the stored totals are
    *added* so no data is lost in either direction.

    Fields merged (all additive):
    - ``total_cost_usd``
    - ``total_input_tokens``
    - ``total_output_tokens``

    Fields AgentPulse does not track at session level are left alone:
    ``total_duration_ms``, ``total_api_duration_ms``, cache tokens.

    ``last_model_name`` is populated from AgentPulse only if the
    accumulator hasn't seen one yet (local takes precedence because it
    came from an actual SDK message).
    """
    url = f"http://{host}:{port}/api/v1/sessions/{session_id}"
    req = urllib.request.Request(url, method="GET")
    try:
        # urlopen raises HTTPError for 4xx/5xx and auto-follows 3xx, so a
        # successful return guarantees 2xx — no explicit status check needed.
        with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT_S) as resp:
            data = json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return SeedResult(ok=True, merged=False)
        logger.debug("seed GET session=%s HTTPError %d: %s", session_id, exc.code, exc)
        return SeedResult(ok=False, merged=False)
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError) as exc:
        logger.debug("seed GET session=%s to %s failed: %s", session_id, url, exc)
        return SeedResult(ok=False, merged=False)

    if not isinstance(data, dict):
        # Unexpected response shape — treat as no-data rather than error
        return SeedResult(ok=True, merged=False)

    # Guard the numeric coercions — a malformed AgentPulse response (non-
    # numeric strings, NaN/Inf sneaking through json) would otherwise raise
    # ValueError out of this function. Treat as no-data rather than error.
    try:
        acc.session_id = session_id
        cost = data.get("cost_usd")
        if cost is not None:
            acc.total_cost_usd += float(cost)
        in_tokens = data.get("total_input_tokens")
        if in_tokens is not None:
            acc.total_input_tokens += int(in_tokens)
        out_tokens = data.get("total_output_tokens")
        if out_tokens is not None:
            acc.total_output_tokens += int(out_tokens)
        model_name = data.get("model_name")
        if model_name and not acc.last_model_name:
            acc.last_model_name = str(model_name)
    except (TypeError, ValueError):
        logger.debug("seed GET %s returned non-numeric totals", url)
        return SeedResult(ok=False, merged=False)
    # ``merged=True`` means AgentPulse returned a record for this session —
    # even if every numeric field was null. The caller only branches on
    # ``ok``, so the distinction is informational.
    return SeedResult(ok=True, merged=True)
