# Generated By: Claude Code (Claude Opus 4.6)
"""Background client for AgentPulse REST + WebSocket API.

Reads config from ~/.claude/agentpulse/config.json, bootstraps session
state via GET /api/v1/sessions, then streams updates via WebSocket.
Runs entirely in a daemon thread with its own asyncio event loop.
"""

from __future__ import annotations

import asyncio
import json
import logging
import threading
import time
import tkinter as tk
import urllib.request
from collections.abc import Callable
from typing import Any

from personal_assistant_dashboard.agentpulse_config import (
    HTTP_TIMEOUT_S,
    load_agentpulse_config,
)

logger = logging.getLogger(__name__)

_BACKOFF_CAP = 30.0
_INITIAL_BACKOFF = 1.0


def _session_response_to_row(
    resp: dict[str, Any], *, is_active: bool = True
) -> dict[str, Any]:
    """Convert an AgentPulse SessionResponse dict to an info-tab row.

    Reads available fields from the response; falls back to zero/empty
    defaults for fields that are null or absent.

    ``total_cost_usd`` is reported as ``cost_usd - prior_cost_usd`` so
    the InfoTab shows what the current dashboard run has spent.
    AgentPulse's stored ``cost_usd`` is lifetime-cumulative (includes
    the seed merged from prior runs at restart); ``prior_cost_usd`` is
    the portion AgentPulse had before the current process first
    contacted it. Clamped to zero in case the server ever reports a
    prior greater than total.
    """
    started_at = resp.get("started_at", 0)
    # AgentPulse reports started_at in epoch milliseconds
    started_at_s = started_at / 1000.0 if started_at else 0
    elapsed_ms = max(0, int((time.time() - started_at_s) * 1000)) if started_at else 0
    # ended_at comes from API in epoch seconds; convert to ms for consistency
    ended_at_s = resp.get("ended_at") or 0
    ended_at_ms = int(ended_at_s * 1000) if ended_at_s else 0
    cost_usd = resp.get("cost_usd") or 0.0
    prior_cost_usd = resp.get("prior_cost_usd") or 0.0
    current_cost = max(0.0, cost_usd - prior_cost_usd)
    return {
        "session_id": resp.get("session_id", ""),
        "cwd": resp.get("cwd", ""),
        "pid": resp.get("pid") or 0,
        "source_system": resp.get("source_system") or "",
        "model_display_name": resp.get("model_name") or "",
        "total_cost_usd": current_cost,
        "total_input_tokens": resp.get("total_input_tokens") or 0,
        "total_output_tokens": resp.get("total_output_tokens") or 0,
        "context_used_pct": resp.get("context_used_pct") or 0,
        "total_duration_ms": elapsed_ms,
        "lines_added": resp.get("lines_added") or 0,
        "lines_removed": resp.get("lines_removed") or 0,
        "started_at": started_at,
        "ended_at": ended_at_ms,
        "last_event_at": resp.get("last_event_at") or 0.0,
        "is_active": is_active,
    }


def _next_backoff(current: float) -> float:
    """Compute next exponential backoff delay, capped at _BACKOFF_CAP."""
    return min(current * 2, _BACKOFF_CAP)


class AgentPulseClient:
    """Background client that streams AgentPulse session data.

    Call ``start()`` to launch the daemon thread and ``stop()`` to shut
    it down. The ``on_update`` callback is scheduled on the Tkinter main
    thread whenever session data changes.
    """

    def __init__(self, root: tk.Tk, on_update: Callable[[], None]) -> None:
        self._root = root
        self._on_update = on_update
        self._sessions: dict[str, dict[str, Any]] = {}
        self._limits: dict[str, Any] = {}
        self._lock = threading.Lock()
        self._stop_event = threading.Event()
        self._loop: asyncio.AbstractEventLoop | None = None

        config = load_agentpulse_config()
        if config is None:
            self._host: str | None = None
            self._port: int | None = None
            self.fetch_limits_enabled: bool = False
        else:
            self._host = config.host
            self._port = config.port
            self.fetch_limits_enabled = config.fetch_limits

    def start(self) -> None:
        """Launch the background connection thread."""
        if self._host is None:
            logger.info("AgentPulse config not found; client disabled")
            return
        t = threading.Thread(target=self._run, daemon=True, name="agentpulse")
        t.start()

    def stop(self) -> None:
        """Signal the background thread to shut down."""
        self._stop_event.set()
        if self._loop is not None:
            self._loop.call_soon_threadsafe(self._loop.stop)

    def get_sessions(self) -> list[dict[str, Any]]:
        """Return a snapshot of current sessions."""
        with self._lock:
            return list(self._sessions.values())

    def get_limits(self) -> dict[str, Any]:
        """Return the most recent limits snapshot."""
        with self._lock:
            return dict(self._limits)

    def refresh(self) -> None:
        """Force a REST re-fetch of sessions and limits."""
        if self._host is None:
            return
        threading.Thread(
            target=self._rest_fetch_all, daemon=True, name="agentpulse-refresh"
        ).start()

    def _rest_fetch_all(self) -> None:
        """Fetch both sessions and limits (used by refresh button)."""
        self._rest_fetch()
        self._rest_fetch_limits()

    def _run(self) -> None:
        """Background thread entry point."""
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)
        try:
            self._loop.run_until_complete(self._connect_loop())
        except Exception:
            logger.exception("AgentPulse client crashed")
        finally:
            self._loop.close()

    async def _connect_loop(self) -> None:
        """Bootstrap via REST, then maintain a WebSocket connection."""
        import websockets

        backoff = _INITIAL_BACKOFF
        while not self._stop_event.is_set():
            # REST bootstrap
            self._rest_fetch()
            self._rest_fetch_limits()
            self._notify_ui()

            # WebSocket stream
            uri = f"ws://{self._host}:{self._port}/ws"
            try:
                async with websockets.connect(uri, ping_interval=None) as ws:
                    logger.debug("WS connected to %s", uri)
                    backoff = _INITIAL_BACKOFF
                    async for raw in ws:
                        if self._stop_event.is_set():
                            break
                        try:
                            msg = json.loads(raw)
                        except json.JSONDecodeError:
                            continue
                        logger.debug(
                            "WS recv type=%s sid=%s",
                            msg.get("type", "?"),
                            msg.get("session_id", "?")[:8],
                        )
                        self._handle_ws_message(msg)
            except Exception:
                logger.debug("AgentPulse WS disconnected, retrying in %.0fs", backoff)

            # On disconnect: clear state, notify UI, back off
            with self._lock:
                self._sessions.clear()
                self._limits.clear()
            self._notify_ui()
            if self._stop_event.is_set():
                break
            await asyncio.sleep(backoff)
            backoff = _next_backoff(backoff)

    def _rest_fetch(self) -> None:
        """Fetch active and closed sessions via REST and replace state."""
        active = self._fetch_session_list(active=True)
        closed = self._fetch_session_list(active=False)
        # Merge: active takes precedence over closed
        merged = dict(closed)
        merged.update(active)
        with self._lock:
            self._sessions = merged
        self._notify_ui()

    def _fetch_session_list(self, *, active: bool) -> dict[str, dict[str, Any]]:
        """Fetch sessions by active status. Returns {session_id: row}."""
        param = "true" if active else "false"
        url = f"http://{self._host}:{self._port}" f"/api/v1/sessions?active={param}"
        try:
            with urllib.request.urlopen(url, timeout=HTTP_TIMEOUT_S) as resp:
                data = json.loads(resp.read())
        except Exception:
            logger.debug("AgentPulse REST fetch (active=%s) failed", active)
            return {}
        return {
            s["session_id"]: _session_response_to_row(s, is_active=active)
            for s in data
            if isinstance(s, dict) and "session_id" in s
        }

    def _rest_fetch_limits(self) -> None:
        """Fetch usage limits via REST. Safe to call frequently (server caches)."""
        url = f"http://{self._host}:{self._port}/api/v1/limits"
        try:
            with urllib.request.urlopen(url, timeout=HTTP_TIMEOUT_S) as resp:
                data = json.loads(resp.read())
        except Exception:
            logger.debug("AgentPulse limits fetch failed")
            return
        if isinstance(data, dict):
            with self._lock:
                self._limits = data
            self._notify_ui()

    def _handle_ws_message(self, msg: dict[str, Any]) -> None:
        """Process a single WebSocket message and update state."""
        msg_type = msg.get("type", "")
        session_id = msg.get("session_id", "")

        if msg_type == "session_discovered":
            # Fetch full session from REST to get all fields
            url = f"http://{self._host}:{self._port}" f"/api/v1/sessions/{session_id}"
            try:
                with urllib.request.urlopen(url, timeout=HTTP_TIMEOUT_S) as resp:
                    data = json.loads(resp.read())
                row = _session_response_to_row(data)
                with self._lock:
                    self._sessions[session_id] = row
            except Exception:
                logger.debug("Failed to fetch discovered session %s", session_id)

        elif msg_type == "session_ended":
            with self._lock:
                if session_id in self._sessions:
                    self._sessions[session_id]["is_active"] = False
            # Fetch final state to capture last cost/token values
            url = f"http://{self._host}:{self._port}" f"/api/v1/sessions/{session_id}"
            try:
                with urllib.request.urlopen(url, timeout=HTTP_TIMEOUT_S) as resp:
                    data = json.loads(resp.read())
                row = _session_response_to_row(data, is_active=False)
                with self._lock:
                    self._sessions[session_id] = row
            except Exception:
                logger.debug("Failed to fetch ended session %s", session_id[:8])

        elif msg_type == "hook_event":
            with self._lock:
                if session_id in self._sessions:
                    s = self._sessions[session_id]
                    s["last_event"] = msg.get("event_name")
                    s["last_tool"] = msg.get("tool_name")
                    ts = msg.get("timestamp")
                    if ts is not None:
                        s["last_event_at"] = ts
                    self._apply_statusline_fields(s, msg)

        elif msg_type == "statusline_update":
            with self._lock:
                if session_id in self._sessions:
                    self._apply_statusline_fields(self._sessions[session_id], msg)

        elif msg_type == "limits_updated":
            limits_data = msg.get("limits")
            if isinstance(limits_data, dict):
                with self._lock:
                    self._limits = limits_data

        self._notify_ui()

    @staticmethod
    def _apply_statusline_fields(session: dict[str, Any], msg: dict[str, Any]) -> None:
        """Copy statusline fields from a WS message into a session row.

        ``total_cost_usd`` is stored as ``cost_usd - prior_cost_usd`` so
        the InfoTab displays only the current run's cost (matching the
        REST-fetch path in ``_session_response_to_row``).
        """
        cost_usd = msg.get("cost_usd")
        if cost_usd is not None:
            prior = msg.get("prior_cost_usd") or 0.0
            session["total_cost_usd"] = max(0.0, cost_usd - prior)
        for src, dst in (
            ("context_used_pct", "context_used_pct"),
            ("model_name", "model_display_name"),
            ("total_input_tokens", "total_input_tokens"),
            ("total_output_tokens", "total_output_tokens"),
            ("lines_added", "lines_added"),
            ("lines_removed", "lines_removed"),
        ):
            val = msg.get(src)
            if val is not None:
                session[dst] = val

    def _notify_ui(self) -> None:
        """Schedule the update callback on the Tkinter main thread."""
        try:
            self._root.after(0, self._on_update)
        except (RuntimeError, tk.TclError):
            pass  # Tk destroyed
