# Generated By: Claude Code (Claude Opus 4.6)
"""Chat tab — conversational interface to Claude via the Agent SDK."""

from __future__ import annotations

import logging
import re
import time
import tkinter as tk
from datetime import datetime
from pathlib import Path
from typing import Any

from personal_assistant_dashboard.info_tab import short_model_name
from personal_assistant_dashboard.models import ConsoleLogCallback, NotifyTabCallback
from personal_assistant_dashboard.config import (
    WORK_DIR,
    BG_OUTPUT,
    BORDER_COLOR,
    COLOR_ASSISTANT,
    COLOR_BUTTON,
    COLOR_BUTTON_ACTIVE,
    COLOR_ERROR,
    COLOR_SECTION_HEADER,
    COLOR_STOP_BUTTON,
    COLOR_STOP_BUTTON_ACTIVE,
    COLOR_SUCCESS,
    COLOR_WARNING,
    FG_ACCENT,
    FG_DIM,
    FG_TEXT,
    FONT_NAME_BODY,
    PAD,
)

logger = logging.getLogger(__name__)

CHAT_LOG_DIR = WORK_DIR / "scratch" / "chat-log"
_CHAT_LOG_ENTRY = re.compile(
    r"^## (You|Claude) \(([^)]+)\)\n(.*?)(?=^## |\Z)",
    re.MULTILINE | re.DOTALL,
)
_HISTORY_PAIRS = 5


class ChatTab:
    """Interactive chat tab backed by ClaudeSDKClient."""

    def __init__(
        self,
        parent: tk.Frame,
        root: tk.Tk,
        *,
        console_log: ConsoleLogCallback | None = None,
        notify_tab: NotifyTabCallback | None = None,
        agentpulse_client: Any = None,
    ) -> None:
        self._parent = parent
        self._root = root
        self._console_log = console_log
        self._notify_tab = notify_tab
        self._agentpulse_client = agentpulse_client
        self._on_external_send: Any = None
        self._client: Any = None
        self._streaming = False
        self._started = False
        self._assistant_active = False
        self._send_time = 0.0
        self._status_text = ""
        self._status_timer: str | None = None
        self._pending_messages: list[str] = []
        self._chat_log_path: Path | None = None
        self._current_response: list[str] = []
        self._last_response: str = ""
        self._on_response_done: Any = None  # one-shot callback(response_text)
        self._destroying = False
        self._last_text_time = 0.0
        self._auto_scroll = True
        self._build()

    # -- UI ------------------------------------------------------------------

    def _build(self) -> None:
        # Message display area
        msg_frame = tk.Frame(self._parent, bg=BG_OUTPUT)
        msg_frame.pack(fill=tk.BOTH, expand=True, padx=PAD, pady=(PAD, 0))

        self._messages = tk.Text(
            msg_frame,
            bg=BG_OUTPUT,
            fg=FG_TEXT,
            font=FONT_NAME_BODY,
            wrap=tk.WORD,
            state=tk.DISABLED,
            borderwidth=0,
            highlightthickness=0,
            takefocus=0,
            padx=PAD,
            pady=PAD,
            height=1,
        )
        self._messages.pack(fill=tk.BOTH, expand=True)

        # Detect manual scroll — disable auto-scroll when user scrolls up
        self._messages.bind("<MouseWheel>", self._on_user_scroll)
        self._messages.bind("<Button-4>", self._on_user_scroll)  # Linux scroll up
        self._messages.bind("<Button-5>", self._on_user_scroll)  # Linux scroll down

        # Snap-to-bottom button (hidden initially)
        self._snap_btn = tk.Button(
            msg_frame,
            text="\u25bc",
            font=(FONT_NAME_BODY,),
            bg=COLOR_BUTTON,
            fg=FG_TEXT,
            activebackground=COLOR_BUTTON_ACTIVE,
            activeforeground=FG_TEXT,
            borderwidth=1,
            relief=tk.SOLID,
            cursor="hand2",
            command=self._snap_to_bottom,
        )
        # Place in bottom-right corner of msg_frame, hidden by default
        self._snap_btn_visible = False

        # Tags for message styling
        self._messages.tag_configure("user_name", foreground=FG_ACCENT, justify=tk.LEFT)
        self._messages.tag_configure("user_msg", foreground=FG_TEXT, justify=tk.LEFT)
        self._messages.tag_configure(
            "assistant_name", foreground=COLOR_ASSISTANT, justify=tk.LEFT
        )
        self._messages.tag_configure(
            "assistant_msg", foreground=FG_TEXT, justify=tk.LEFT
        )
        self._messages.tag_configure("thinking_msg", foreground=FG_DIM, justify=tk.LEFT)
        self._messages.tag_configure(
            "error_msg", foreground=COLOR_ERROR, justify=tk.LEFT
        )
        self._messages.tag_configure(
            "separator", foreground=BORDER_COLOR, justify=tk.CENTER
        )
        self._messages.tag_configure("timestamp", foreground=FG_DIM, justify=tk.LEFT)
        self._messages.tag_configure(
            "system_name", foreground=COLOR_SECTION_HEADER, justify=tk.LEFT
        )
        self._messages.tag_configure("system_msg", foreground=FG_DIM, justify=tk.LEFT)

        # Status StringVars — widgets created by Dashboard so they're
        # visible across all tabs.
        self._status_var = tk.StringVar(value="")
        self._usage_var = tk.StringVar(value="")
        self._status_label: tk.Label | None = None

        # Primary action button — labeled Cont/Send/Stop depending on
        # state (see _set_send_btn_label_for_idle / _streaming).
        self._send_btn: tk.Button | None = None
        # Clear button — disabled while a response is streaming so the
        # user can't tear down the SDK mid-receive. They must Stop first.
        self._clear_btn: tk.Button | None = None

    # -- history replay -------------------------------------------------------

    def load_history(self) -> bool:
        """Replay recent messages from the last chat log.

        Returns True if history was replayed, False if none was found.
        """
        messages = self._load_last_chat_log()
        if not messages:
            return False
        for role, ts, text in messages:
            self._display_history_entry(role, ts, text)
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, "── resumed ──\n\n", "separator")
            self._messages.config(state=tk.DISABLED)
            self._messages.see(tk.END)
        except tk.TclError:
            pass
        return True

    def _load_last_chat_log(self) -> list[tuple[str, str, str]]:
        """Parse the last N message pairs from the most recent chat log."""
        if not CHAT_LOG_DIR.is_dir():
            return []
        logs = sorted(CHAT_LOG_DIR.glob("*.md"), key=lambda f: f.name, reverse=True)
        if not logs:
            return []
        try:
            content = logs[0].read_text(encoding="utf-8")
        except OSError:
            return []
        matches = _CHAT_LOG_ENTRY.findall(content)
        if not matches:
            return []
        return matches[-(_HISTORY_PAIRS * 2) :]

    def _display_history_entry(self, role: str, ts: str, text: str) -> None:
        """Display a historical message without logging."""
        text = text.strip()
        try:
            self._messages.config(state=tk.NORMAL)
            if role == "You":
                self._messages.insert(tk.END, "You ", "user_name")
                self._messages.insert(tk.END, f"{ts}\n", "timestamp")
                self._messages.insert(tk.END, text + "\n\n", "user_msg")
            else:
                self._messages.insert(tk.END, "Claude ", "assistant_name")
                self._messages.insert(tk.END, f"{ts}\n", "timestamp")
                self._messages.insert(tk.END, text + "\n\n", "assistant_msg")
            self._messages.config(state=tk.DISABLED)
        except tk.TclError:
            pass

    # -- button control ------------------------------------------------------

    def set_send_button(self, btn: tk.Button) -> None:
        """Attach the external primary action button for this chat session.

        Eagerly constructs the ChatClient so the initial label
        accurately reflects the resume state and pre-send ``clear()``
        works against a real client. ``ChatClient.start()`` is cheap —
        no SDK subprocess is spawned until the first send.
        """
        self._send_btn = btn
        self._ensure_client()
        self._set_send_btn_label_for_idle()

    def set_clear_button(self, btn: tk.Button) -> None:
        """Attach the external Clear button so we can lock it during sends."""
        self._clear_btn = btn

    def _has_resume_target(self) -> bool:
        """True if the next send would resume a prior session."""
        if self._client is None:
            return False
        return bool(self._client.has_resume_target())

    def _set_send_btn_label_for_idle(self) -> None:
        """Restore the primary button to its idle label (Cont or Send)."""
        if self._send_btn is None:
            return
        label = "Cont" if self._has_resume_target() else "Send"
        self._send_btn.config(
            text=label,
            command=self._on_send_click,
            bg=COLOR_BUTTON,
            activebackground=COLOR_BUTTON_ACTIVE,
        )

    def _set_send_btn_label_for_streaming(self) -> None:
        """Switch the primary button to Stop while a response streams."""
        if self._send_btn is None:
            return
        self._send_btn.config(
            text="Stop",
            command=self._stop,
            bg=COLOR_STOP_BUTTON,
            activebackground=COLOR_STOP_BUTTON_ACTIVE,
        )

    def _set_clear_btn_enabled(self, enabled: bool) -> None:
        """Enable or disable the Clear button (no-op if not attached)."""
        if self._clear_btn is None:
            return
        try:
            self._clear_btn.config(state=tk.NORMAL if enabled else tk.DISABLED)
        except tk.TclError:
            pass

    def _set_status(self, text: str) -> None:
        """Update status text and color — green for Ready, yellow otherwise."""
        self._status_var.set(text)
        color = COLOR_SUCCESS if text == "Ready" else COLOR_WARNING
        if self._status_label:
            self._status_label.config(fg=color)

    def _on_usage(self, model: str, cost_usd: float, used_pct: float) -> None:
        """Update the right-side usage display with model, cost, and context %."""
        short = short_model_name(model)
        self._usage_var.set(f"{short}  ${cost_usd:.2f}  {used_pct}%")

    def _stop(self) -> None:
        """Interrupt the current response."""
        if self._client and self._streaming:
            self._client.interrupt()

    # -- scroll lock -----------------------------------------------------------

    def _is_at_bottom(self) -> bool:
        """Check if the messages widget is scrolled to the bottom."""
        try:
            return self._messages.yview()[1] >= 0.99
        except tk.TclError:
            return True

    def _on_user_scroll(self, _event: Any = None) -> None:
        """User scrolled manually — update auto-scroll state."""
        self._root.after(50, self._check_scroll_position)

    def _check_scroll_position(self) -> None:
        """Check position after scroll event settles."""
        at_bottom = self._is_at_bottom()
        if at_bottom:
            self._auto_scroll = True
            self._hide_snap_btn()
        else:
            self._auto_scroll = False
            self._show_snap_btn()

    def _scroll_to_end(self) -> None:
        """Scroll to bottom only if auto-scroll is enabled."""
        if self._auto_scroll:
            self._messages.see(tk.END)

    def _snap_to_bottom(self) -> None:
        """User clicked the snap-to-bottom button."""
        self._auto_scroll = True
        try:
            self._messages.see(tk.END)
        except tk.TclError:
            pass
        self._hide_snap_btn()

    def _show_snap_btn(self) -> None:
        """Show the snap-to-bottom indicator."""
        if not self._snap_btn_visible:
            self._snap_btn.place(relx=1.0, rely=1.0, anchor=tk.SE, x=-8, y=-8)
            self._snap_btn_visible = True

    def _hide_snap_btn(self) -> None:
        """Hide the snap-to-bottom indicator."""
        if self._snap_btn_visible:
            self._snap_btn.place_forget()
            self._snap_btn_visible = False

    # -- send / receive ------------------------------------------------------

    def send_message(self, text: str, *, displayed: bool = False) -> None:
        """Public API: send a message as if the user typed it.

        Args:
            displayed: if True, the user message is already shown in chat.
        """
        if not text:
            return
        if self._streaming:
            self._pending_messages.append(text)
            self._status_text = f"Queued ({len(self._pending_messages)})"
            return
        if not displayed:
            self._append_user(text)
        self._send_now(text)

    def _send_now(self, text: str) -> None:
        """Send a message immediately."""
        self._streaming = True
        self._set_send_btn_label_for_streaming()
        self._set_clear_btn_enabled(False)
        self._assistant_active = False

        self._send_time = time.monotonic()
        self._ensure_client()
        if self._client is None:
            self._on_error("Failed to initialize chat client")
            return
        # SDK subprocess connects lazily on first send; reflect that in
        # the status so the user sees something other than a silent
        # "Waiting for response" during the 1–3s connect.
        self._status_text = (
            "Waiting for response"
            if self._client.is_connected()
            else "Connecting agent"
        )
        self._start_status_timer()
        ts = self._format_timestamp()
        self._client.send(f"[{ts}] {text}")

    def _ensure_client(self) -> None:
        """Lazily create and start the chat client."""
        if self._client is not None:
            return

        from personal_assistant_dashboard.chat_client import ChatClient

        self._client = ChatClient(
            on_text=lambda t: self._schedule(self._on_text, t),
            on_tool_use=lambda t: self._schedule(self._on_tool_use, t),
            on_done=lambda: self._schedule(self._on_done),
            on_error=lambda e: self._schedule(self._on_error, e),
            on_usage=lambda m, c, p: self._schedule(self._on_usage, m, c, p),
            agentpulse_client=self._agentpulse_client,
        )
        self._client.start()

    def _start_status_timer(self) -> None:
        """Start a 1-second timer to update the status with elapsed time."""
        self._tick_status()

    def _stop_status_timer(self) -> None:
        """Cancel the status timer."""
        if self._status_timer is not None:
            self._root.after_cancel(self._status_timer)
            self._status_timer = None

    def _tick_status(self) -> None:
        """Update status bar with current elapsed time."""
        if not self._streaming or self._destroying:
            return
        elapsed = self._format_duration(time.monotonic() - self._send_time)
        self._status_var.set(f"{self._status_text} ({elapsed})")
        if self._status_label:
            self._status_label.config(fg=COLOR_WARNING)
        self._status_timer = self._root.after(1000, self._tick_status)

    def _schedule(self, fn: Any, *args: Any) -> None:
        """Schedule a callback on the TkInter main thread."""
        try:
            if not self._destroying and self._root.winfo_exists():
                self._root.after(0, fn, *args)
        except RuntimeError:
            pass

    # -- UI callbacks (main thread only) -------------------------------------

    def _on_text(self, delta: str) -> None:
        """Append streaming text delta from Claude."""
        self._status_text = "Streaming"
        if not self._assistant_active:
            self._start_assistant()
        now = time.monotonic()
        gap = now - self._last_text_time if self._last_text_time else 0
        self._last_text_time = now
        try:
            self._messages.config(state=tk.NORMAL)
            if gap > 2.0 and self._current_response:
                self._messages.insert(tk.END, "\n", "assistant_msg")
            self._messages.insert(tk.END, delta, "assistant_msg")
            self._messages.config(state=tk.DISABLED)
            self._scroll_to_end()
        except tk.TclError:
            pass
        self._current_response.append(delta)

    def _on_tool_use(self, tool_name: str) -> None:
        """Update status bar with tool name."""
        self._status_text = f"Using {tool_name}"
        if not self._assistant_active:
            self._start_assistant()

    def _on_done(self) -> None:
        """Response complete."""
        self._streaming = False
        self._assistant_active = False
        self._set_send_btn_label_for_idle()
        self._set_clear_btn_enabled(True)
        self._stop_status_timer()
        if self._current_response:
            self._last_response = "".join(self._current_response)
            self._log_assistant(self._last_response)
            self._current_response.clear()
            if self._on_response_done:
                cb = self._on_response_done
                self._on_response_done = None
                cb(self._last_response)
        elapsed = time.monotonic() - self._send_time
        duration = self._format_duration(elapsed)
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, f"\n[success] {duration}\n\n", "thinking_msg")
            self._messages.config(state=tk.DISABLED)
            self._scroll_to_end()
        except tk.TclError:
            pass

        if self._pending_messages:
            next_msg = self._pending_messages.pop(0)
            self._append_user(next_msg)
            self._send_now(next_msg)
            return

        self._set_status("Ready")
        if self._notify_tab:
            self._notify_tab("Chat")

    def _on_send_click(self) -> None:
        """Called by the external Send button — delegates to Dashboard."""
        if self._on_external_send:
            self._on_external_send()

    def _on_error(self, error: str) -> None:
        """Display error inline and re-enable input."""
        self._streaming = False
        self._assistant_active = False
        self._current_response.clear()
        self._set_send_btn_label_for_idle()
        self._set_clear_btn_enabled(True)
        self._stop_status_timer()
        elapsed = time.monotonic() - self._send_time
        duration = self._format_duration(elapsed)
        self._set_status("Error")
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(
                tk.END, f"\n[failure] {error} ({duration})\n\n", "error_msg"
            )
            self._messages.config(state=tk.DISABLED)
            self._scroll_to_end()
        except tk.TclError:
            pass
        self._pending_messages.clear()
        if self._console_log:
            self._console_log(f"Chat error: {error}", "error", "", "")

    @staticmethod
    def _format_duration(seconds: float) -> str:
        """Format elapsed seconds as a human-readable duration."""
        total = int(seconds)
        if total < 60:
            return f"{total}s"
        minutes = total // 60
        secs = total % 60
        return f"{minutes}m {secs}s"

    # -- message formatting --------------------------------------------------

    @staticmethod
    def _format_timestamp() -> str:
        """Format current time for display and agent messages."""
        now = datetime.now().astimezone()
        tz_abbr = now.strftime("%Z")
        if " " in tz_abbr:
            tz_abbr = "".join(w[0] for w in tz_abbr.split())
        day = now.day
        hour = now.hour % 12 or 12
        return now.strftime(f"%a, %b {day}, %Y {hour}:%M %p {tz_abbr}")

    def _append_user(self, text: str, *, log: bool = True) -> None:
        """Insert a user message into the display.

        Set ``log=False`` for inputs handled locally (built-in commands,
        quick-capture) so the chat log only holds messages that had a
        corresponding logged assistant reply.
        """
        ts = self._format_timestamp()
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, "You ", "user_name")
            self._messages.insert(tk.END, f"{ts}\n", "timestamp")
            self._messages.insert(tk.END, text + "\n\n", "user_msg")
            self._messages.config(state=tk.DISABLED)
            self._scroll_to_end()
        except tk.TclError:
            pass
        if log:
            self._log_user(text)

    def _append_system(self, text: str) -> None:
        """Insert a Dashboard message into the display (no logging)."""
        ts = self._format_timestamp()
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, "Dashboard ", "system_name")
            self._messages.insert(tk.END, f"{ts}\n", "timestamp")
            self._messages.insert(tk.END, text + "\n\n", "system_msg")
            self._messages.config(state=tk.DISABLED)
            self._scroll_to_end()
        except tk.TclError:
            pass

    def _start_assistant(self) -> None:
        """Insert the Claude label before streaming text."""
        self._assistant_active = True
        ts = self._format_timestamp()
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, "Claude ", "assistant_name")
            self._messages.insert(tk.END, f"{ts}\n", "timestamp")
            self._messages.config(state=tk.DISABLED)
            self._scroll_to_end()
        except tk.TclError:
            pass

    # -- chat logging ----------------------------------------------------------

    def _ensure_chat_log(self) -> None:
        """Create a chat log file for this session if one doesn't exist."""
        if self._chat_log_path is not None:
            return
        CHAT_LOG_DIR.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
        self._chat_log_path = CHAT_LOG_DIR / f"{timestamp}.md"

    def _log_user(self, text: str) -> None:
        """Append a user message to the chat log."""
        self._ensure_chat_log()
        if not self._chat_log_path:
            return
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        try:
            with open(self._chat_log_path, "a", encoding="utf-8") as f:
                f.write(f"## You ({ts})\n{text}\n\n")
        except (OSError, UnicodeError) as exc:
            logger.warning("failed to write chat log: %s", exc)

    def _log_assistant(self, text: str) -> None:
        """Append an assistant response to the chat log."""
        if not self._chat_log_path:
            return
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        try:
            with open(self._chat_log_path, "a", encoding="utf-8") as f:
                f.write(f"## Claude ({ts})\n{text}\n\n")
        except (OSError, UnicodeError) as exc:
            logger.warning("failed to write chat log: %s", exc)

    # -- clear / refresh -----------------------------------------------------

    def _clear(self) -> None:
        """Clear conversation history and display.

        No-op while streaming — the Clear button is disabled in that
        state, this guard handles the rare case of a programmatic call.
        """
        if self._streaming:
            return
        self._pending_messages.clear()
        # Create a new empty chat log so restart after clear shows help.
        CHAT_LOG_DIR.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
        self._chat_log_path = CHAT_LOG_DIR / f"{timestamp}.md"
        self._chat_log_path.touch()
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.delete("1.0", tk.END)
            self._messages.config(state=tk.DISABLED)
        except tk.TclError:
            pass
        if self._client:
            self._client.clear()
        # Resume target was dropped (or never existed) — refresh the
        # primary button label so it shows Send instead of Cont.
        self._set_send_btn_label_for_idle()

    def refresh(self) -> None:
        """Called when the tab is activated."""
        pass

    def on_destroy(self) -> None:
        """Called during dashboard shutdown to clean up resources."""
        self._destroying = True
        self._stop_status_timer()
        if self._client:
            self._client.stop()
