# Generated By: Claude Code (Claude Opus 4.6)
"""PRs tab — shows open PRs needing review and authored by user."""

from __future__ import annotations

import json
import logging
import threading
import tkinter as tk
import webbrowser
from datetime import datetime, timezone
from pathlib import Path
from tkinter import ttk
from typing import Any, Callable

from personal_assistant_dashboard.config import (
    BG_OUTPUT,
    BG_WINDOW,
    COLOR_BUTTON,
    COLOR_BUTTON_ACTIVE,
    COLOR_DECLINED,
    COLOR_ERROR,
    COLOR_LINK,
    COLOR_NOTIFICATION_BELL,
    COLOR_PROGRESS,
    COLOR_SECTION_HEADER,
    COLOR_WARNING,
    FG_DIM,
    FG_TEXT,
    FONT_FAMILY_MONO,
    FONT_SIZE_BODY,
    PAD,
)
from personal_assistant_dashboard.utils import atomic_write_json, run_cmd

logger = logging.getLogger(__name__)

ScheduleFn = Callable[..., None]


def _age_str(iso_date: str) -> str:
    """Convert ISO datetime to human-readable age in days."""
    try:
        created = datetime.fromisoformat(iso_date.replace("Z", "+00:00"))
        days = (datetime.now(timezone.utc) - created).days
        return f"{days}d" if days > 0 else "<1d"
    except (ValueError, TypeError):
        return ""


def _repo_from_url(repository_url: str) -> str:
    """Extract 'owner/repo' from GitHub API repository_url."""
    # https://api.github.com/repos/owner/repo -> owner/repo
    parts = repository_url.rstrip("/").split("/")
    if len(parts) >= 2:
        return f"{parts[-2]}/{parts[-1]}"
    return repository_url


def _fetch_prs(query: str) -> list[dict[str, Any]]:
    """Run gh api search and return items list."""
    result = run_cmd(
        [
            "gh",
            "api",
            "--paginate",
            f"/search/issues?q={query}&per_page=100",
        ],
        timeout=120,
    )
    if result.returncode != 0:
        logger.warning("gh api failed: %s", result.stderr[:200])
        return []
    # --paginate concatenates JSON objects; parse each one
    all_items: list[dict[str, Any]] = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            all_items.extend(json.loads(line).get("items", []))
        except json.JSONDecodeError:
            continue
    return all_items


_DECISION_STATES = {"APPROVED", "CHANGES_REQUESTED"}


def _fetch_review_counts(
    prs: list[dict[str, Any]],
) -> tuple[dict[str, int], set[str]]:
    """Fetch count of current user's reviews and changes-requested URLs."""
    user_result = run_cmd(["gh", "api", "user"], timeout=30)
    if user_result.returncode != 0:
        return {}, set()
    try:
        login = json.loads(user_result.stdout).get("login", "")
    except json.JSONDecodeError:
        return {}, set()
    if not login:
        return {}, set()

    counts: dict[str, int] = {}
    changes_requested: set[str] = set()
    for pr in prs:
        url = pr.get("html_url", "")
        repo = _repo_from_url(pr.get("repository_url", ""))
        number = pr.get("number", "")
        if not repo or not number:
            counts[url] = 0
            continue
        result = run_cmd(
            ["gh", "api", f"/repos/{repo}/pulls/{number}/reviews"],
            timeout=30,
        )
        if result.returncode != 0:
            counts[url] = 0
            continue
        try:
            reviews = json.loads(result.stdout)
        except json.JSONDecodeError:
            counts[url] = 0
            continue
        my_reviews = [r for r in reviews if r.get("user", {}).get("login") == login]
        counts[url] = len(my_reviews)
        # Latest decision review determines state
        for r in reversed(my_reviews):
            if r.get("state") in _DECISION_STATES:
                if r["state"] == "CHANGES_REQUESTED":
                    changes_requested.add(url)
                break
    return counts, changes_requested


def _fetch_incoming_change_requests(
    prs: list[dict[str, Any]],
) -> dict[str, int]:
    """For authored PRs, count reviewers whose latest decision is CHANGES_REQUESTED."""
    counts: dict[str, int] = {}
    for pr in prs:
        url = pr.get("html_url", "")
        repo = _repo_from_url(pr.get("repository_url", ""))
        number = pr.get("number", "")
        if not repo or not number:
            continue
        result = run_cmd(
            ["gh", "api", f"/repos/{repo}/pulls/{number}/reviews"],
            timeout=30,
        )
        if result.returncode != 0:
            continue
        try:
            reviews = json.loads(result.stdout)
        except json.JSONDecodeError:
            continue
        # Group by reviewer, find latest decision per reviewer
        by_reviewer: dict[str, str] = {}
        for r in reviews:
            login = r.get("user", {}).get("login", "")
            state = r.get("state", "")
            if login and state in _DECISION_STATES:
                by_reviewer[login] = state
        cr_count = sum(1 for s in by_reviewer.values() if s == "CHANGES_REQUESTED")
        counts[url] = cr_count
    return counts


def _fetch_queued_prs(
    prs: list[dict[str, Any]],
) -> set[str]:
    """Return set of html_urls for PRs in a merge queue.

    One GraphQL query per repo using aliases to batch PR lookups.
    Avoids paginating all open PRs — queries only the PRs we have.
    """
    # Group by repo
    by_repo: dict[str, list[dict[str, Any]]] = {}
    for pr in prs:
        repo = _repo_from_url(pr.get("repository_url", ""))
        if repo:
            by_repo.setdefault(repo, []).append(pr)

    queued: set[str] = set()
    for repo, repo_prs in by_repo.items():
        parts = repo.split("/")
        if len(parts) != 2:
            continue
        owner, name = parts
        # Build aliased query for each PR in this repo
        fragments = []
        for i, pr in enumerate(repo_prs):
            n = pr.get("number", 0)
            if not n:
                continue
            fragments.append(
                "pr%d: pullRequest(number: %d)"
                " { number mergeQueueEntry"
                " { position } }" % (i, n)
            )
        if not fragments:
            continue
        body = " ".join(fragments)
        query = '{ repository(owner: "%s", name: "%s")' " { %s } }" % (
            owner,
            name,
            body,
        )
        result = run_cmd(
            ["gh", "api", "graphql", "-f", f"query={query}"],
            timeout=30,
        )
        if result.returncode != 0:
            continue
        try:
            data = json.loads(result.stdout)
            repo_data = data.get("data", {}).get("repository", {})
            for i, pr in enumerate(repo_prs):
                node = repo_data.get(f"pr{i}")
                if node and node.get("mergeQueueEntry"):
                    url = pr.get("html_url", "")
                    if url:
                        queued.add(url)
        except (json.JSONDecodeError, AttributeError):
            continue
    return queued


class PrsTab:
    """PRs tab showing review-requested and authored PRs."""

    def __init__(
        self,
        parent: tk.Frame,
        root: tk.Tk,
        *,
        state_path: Path,
        schedule_fn: ScheduleFn,
        notebook: ttk.Notebook | None = None,
        console_log: Callable[..., None] | None = None,
        notify_tab: Callable[[str], None] | None = None,
    ) -> None:
        self._parent = parent
        self._root = root
        self._state_path = state_path
        self._schedule = schedule_fn
        self._notebook = notebook
        self._console_log = console_log
        self._notify_tab = notify_tab
        self._dismissed: set[str] = set()
        self._priority: set[str] = set()
        self._review_prs: list[dict[str, Any]] = []
        self._my_prs: list[dict[str, Any]] = []
        self._row_widgets: dict[str, tk.Button] = {}
        self._review_counts: dict[str, int] = {}
        self._incoming_cr_counts: dict[str, int] = {}
        self._queued_urls: set[str] = set()
        self._changes_requested_urls: set[str] = set()
        self._newest_first = False
        self._show_drafts_var = tk.BooleanVar(value=False)
        self._show_queued_var = tk.BooleanVar(value=False)
        self._show_dismissed_var = tk.BooleanVar(value=False)
        self._show_changes_requested_var = tk.BooleanVar(value=False)
        self._font_body = "app_body"
        self._font_heading = "app_heading"
        self._auto_refresh_ms = 5 * 60 * 1000
        self._auto_refresh_id: str | None = None
        self._refreshing = False
        self._skipped_refreshes = 0
        self._load_dismissed()
        self._load_priority()
        self._build()
        self.refresh()
        self._schedule_auto_refresh()

    def _build(self) -> None:
        top = tk.Frame(self._parent, bg=BG_WINDOW)
        top.pack(fill=tk.X, pady=(0, PAD))

        self._refresh_btn = tk.Button(
            top,
            text="↻",
            command=self.refresh,
            bg=COLOR_BUTTON,
            fg=FG_TEXT,
            font=self._font_body,
            relief=tk.FLAT,
            activebackground=COLOR_BUTTON_ACTIVE,
            cursor="hand2",
            padx=4,
        )
        self._refresh_btn.pack(side=tk.LEFT, padx=(PAD, 4))

        self._sort_var = tk.StringVar(value="Oldest")

        def _toggle_sort() -> None:
            self._newest_first = not self._newest_first
            self._sort_var.set("Newest" if self._newest_first else "Oldest")
            self._render()

        tk.Button(
            top,
            textvariable=self._sort_var,
            command=_toggle_sort,
            bg=COLOR_BUTTON,
            fg=FG_TEXT,
            font=self._font_body,
            relief=tk.FLAT,
            activebackground=COLOR_BUTTON_ACTIVE,
            cursor="hand2",
            padx=6,
        ).pack(side=tk.LEFT)

        self._filter_buttons: dict[
            str,
            tuple[
                tk.Checkbutton,
                tk.BooleanVar,
                str,
                tk.StringVar,
            ],
        ] = {}

        def _make_filter(
            label: str,
            var: tk.BooleanVar,
            active_fg: str,
        ) -> tk.Checkbutton:
            text_var = tk.StringVar(value=f"{label}:0")

            def _toggle() -> None:
                on = var.get()
                if on:
                    for k, (btn, v, _, _tv) in self._filter_buttons.items():
                        if k != label and v.get():
                            v.set(False)
                            btn.configure(fg=FG_DIM)
                btn_w.configure(fg=active_fg if on else FG_DIM)
                self._render()

            btn_w = tk.Checkbutton(
                top,
                textvariable=text_var,
                variable=var,
                command=_toggle,
                bg=BG_WINDOW,
                fg=FG_DIM,
                selectcolor=BG_WINDOW,
                activebackground=BG_WINDOW,
                activeforeground=FG_TEXT,
                font=self._font_body,
                relief=tk.FLAT,
                cursor="hand2",
                indicatoron=False,
                padx=6,
            )
            btn_w.pack(side=tk.LEFT, padx=(PAD, 0))
            self._filter_buttons[label] = (
                btn_w,
                var,
                active_fg,
                text_var,
            )
            return btn_w

        self._drafts_btn = _make_filter(
            "Drafts",
            self._show_drafts_var,
            COLOR_LINK,
        )
        self._queued_btn = _make_filter(
            "Queued",
            self._show_queued_var,
            COLOR_WARNING,
        )
        self._changes_requested_btn = _make_filter(
            "Chg Req",
            self._show_changes_requested_var,
            COLOR_ERROR,
        )
        self._dismissed_btn = _make_filter(
            "Dismissed",
            self._show_dismissed_var,
            COLOR_DECLINED,
        )

        tk.Button(
            top,
            text="Reset Dismissed",
            command=self._reset_dismissed,
            bg=COLOR_BUTTON,
            fg=FG_TEXT,
            font=self._font_body,
            relief=tk.FLAT,
            activebackground=COLOR_BUTTON_ACTIVE,
            cursor="hand2",
            padx=6,
        ).pack(side=tk.RIGHT, padx=(0, PAD))

        self._status_var = tk.StringVar(value="Loading...")
        tk.Label(
            top,
            textvariable=self._status_var,
            bg=BG_WINDOW,
            fg=FG_DIM,
            font=self._font_body,
        ).pack(side=tk.RIGHT, padx=(0, PAD))

        # Scrollable content — Text widget with native scroll
        container = tk.Frame(self._parent, bg=BG_OUTPUT)
        container.pack(fill=tk.BOTH, expand=True, padx=PAD, pady=(0, PAD))

        self._text = tk.Text(
            container,
            bg=BG_OUTPUT,
            fg=FG_TEXT,
            font=self._font_body,
            wrap=tk.NONE,
            state=tk.DISABLED,
            highlightthickness=0,
            borderwidth=0,
            cursor="arrow",
        )
        scrollbar = tk.Scrollbar(container, command=self._text.yview)
        self._text.configure(yscrollcommand=scrollbar.set)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self._text.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        # Scroll text and stop propagation to Notebook
        def _scroll_text(event: Any) -> str:
            self._text.yview_scroll(-1 if event.num == 4 else 1, "units")
            return "break"

        self._text.bind("<Button-4>", _scroll_text)
        self._text.bind("<Button-5>", _scroll_text)

        self._text.tag_configure(
            "section", foreground=COLOR_SECTION_HEADER, font=self._font_heading
        )
        self._text.tag_configure("dim", foreground=FG_DIM)
        self._text.tag_configure(
            "age",
            foreground=FG_DIM,
            font=(FONT_FAMILY_MONO, FONT_SIZE_BODY),
        )
        self._text.tag_configure(
            "separator",
            foreground=FG_DIM,
            font=(FONT_FAMILY_MONO, -6),
            spacing1=0,
            spacing3=0,
        )
        self._text.tag_configure("review_count", foreground=FG_TEXT)
        self._text.tag_configure("review_zero", foreground=FG_DIM)

    def refresh(self, *, show_status: bool = True) -> None:
        if self._refreshing:
            self._skipped_refreshes += 1
            tag = "error" if self._skipped_refreshes > 6 else "warning"
            n = self._skipped_refreshes
            self._log(
                f"PRs tab: refresh skipped ({n}x)," " previous still running",
                tag,
            )
            return
        self._refreshing = True
        self._refresh_btn.configure(fg=COLOR_PROGRESS)
        if show_status:
            self._status_var.set("Refreshing...")
        thread = threading.Thread(target=self._do_refresh, daemon=True)
        thread.start()

    def _schedule_auto_refresh(self) -> None:
        def _tick() -> None:
            self.refresh(show_status=False)
            self._schedule_auto_refresh()

        self._auto_refresh_id = self._root.after(
            self._auto_refresh_ms,
            _tick,
        )

    def _do_refresh(self) -> None:
        try:
            review = _fetch_prs(
                "is:pr+review-requested:@me+state:open+archived:false+sort:updated-desc"
            )
            my = _fetch_prs(
                "is:pr+author:@me+state:open+archived:false+sort:updated-desc"
            )
            counts, changes_req = _fetch_review_counts(review)
            incoming_cr = _fetch_incoming_change_requests(my)
            all_prs = review + my
            queued = _fetch_queued_prs(all_prs)
            self._schedule(
                self._on_data_loaded,
                review,
                my,
                counts,
                queued,
                changes_req,
                incoming_cr,
            )
        except Exception:
            logger.exception("PR refresh failed")
            self._refreshing = False
            self._schedule(self._refresh_btn.configure, {"fg": FG_TEXT})
            self._schedule(
                self._log, "PRs tab: refresh failed, see logs for details", "error"
            )

    def _log(
        self,
        message: str,
        tag: str = "info",
        link: str = "",
        link_label: str = "",
    ) -> None:
        if self._console_log:
            self._console_log(message, tag, link, link_label)
        else:
            logger.warning(message)

    def _on_data_loaded(
        self,
        review_prs: list[dict[str, Any]],
        my_prs: list[dict[str, Any]],
        review_counts: dict[str, int],
        queued_urls: set[str] | None = None,
        changes_requested_urls: set[str] | None = None,
        incoming_cr_counts: dict[str, int] | None = None,
    ) -> None:
        self._refreshing = False
        self._refresh_btn.configure(fg=FG_TEXT)
        self._skipped_refreshes = 0
        old_urls = {p.get("html_url", "") for p in self._review_prs}
        new_urls = {p.get("html_url", "") for p in review_prs}
        new_review_requests = new_urls - old_urls
        self._review_prs = review_prs
        self._my_prs = my_prs
        self._review_counts = review_counts
        if queued_urls is not None:
            self._queued_urls = queued_urls
        if changes_requested_urls is not None:
            self._changes_requested_urls = changes_requested_urls
        if incoming_cr_counts is not None:
            self._incoming_cr_counts = incoming_cr_counts
        self._render()
        if old_urls and new_review_requests:
            if self._notify_tab:
                self._notify_tab("PR")
            new_prs = [
                p for p in review_prs if p.get("html_url", "") in new_review_requests
            ]
            for p in new_prs:
                url = p.get("html_url", "")
                title = p.get("title", "")
                repo = _repo_from_url(p.get("repository_url", ""))
                self._log(
                    f"[PRs] new review request:" f" {repo} — {title}",
                    "warning",
                    link=url,
                )

    def _render(self) -> None:
        self._text.configure(state=tk.NORMAL)
        self._text.delete("1.0", tk.END)
        self._row_widgets.clear()

        self._render_section("Review Requested", self._review_prs)
        self._render_section("My PRs", self._my_prs)

        self._text.configure(state=tk.DISABLED)
        self._update_status()

    def _update_status(self) -> None:
        all_prs = self._review_prs + self._my_prs
        draft_count = sum(1 for p in all_prs if p.get("draft", False))
        queued_count = sum(
            1 for p in all_prs if p.get("html_url", "") in self._queued_urls
        )
        dismissed_count = sum(
            1 for p in all_prs if p.get("html_url", "") in self._dismissed
        )
        cr_count = sum(
            1 for p in all_prs if p.get("html_url", "") in self._changes_requested_urls
        )
        self._filter_buttons["Drafts"][3].set(f"Drafts:{draft_count}")
        self._filter_buttons["Queued"][3].set(f"Queued:{queued_count}")
        self._filter_buttons["Chg Req"][3].set(f"CR:{cr_count}")
        self._filter_buttons["Dismissed"][3].set(f"Dismissed:{dismissed_count}")
        review_actionable = sum(
            1
            for p in self._review_prs
            if p.get("html_url", "") not in self._dismissed
            and not p.get("draft", False)
            and p.get("html_url", "") not in self._queued_urls
        )
        self._status_var.set(f"{review_actionable} actionable")

        if self._notebook is not None:
            tab_text = f"PR:{review_actionable}"
            try:
                self._notebook.tab(self._parent, text=tab_text)
            except tk.TclError:
                pass

    def _render_section(self, title: str, prs: list[dict[str, Any]]) -> None:
        show_drafts = self._show_drafts_var.get()
        show_queued = self._show_queued_var.get()
        show_dismissed = self._show_dismissed_var.get()
        show_cr = self._show_changes_requested_var.get()
        # Mutually exclusive: if a filter is active, show ONLY that
        exclusive = show_drafts or show_queued or show_dismissed or show_cr

        def _include(p: dict[str, Any]) -> bool:
            url = p.get("html_url", "")
            is_draft = bool(p.get("draft", False))
            is_queued = url in self._queued_urls
            is_dismissed = url in self._dismissed
            is_cr = url in self._changes_requested_urls
            if exclusive:
                if show_drafts:
                    return is_draft
                if show_queued:
                    return is_queued
                if show_cr:
                    return is_cr
                if show_dismissed:
                    return is_dismissed
            # Default: hide drafts, queued, dismissed
            return not is_draft and not is_queued and not is_dismissed

        visible = [p for p in prs if _include(p)]
        active_count = sum(
            1 for p in visible if p.get("html_url", "") not in self._dismissed
        )

        self._text.insert(tk.END, f"{title} ({active_count})\n", "section")

        if not visible:
            self._text.insert(tk.END, "  None\n\n", "dim")
            return

        visible.sort(
            key=lambda p: p.get("created_at", ""),
            reverse=self._newest_first,
        )
        visible.sort(key=lambda p: _repo_from_url(p.get("repository_url", "")))
        # Priority PRs float to top
        visible.sort(
            key=lambda p: p.get("html_url", "") not in self._priority,
        )
        last_repo = ""
        for pr in visible:
            repo = _repo_from_url(pr.get("repository_url", ""))
            if last_repo and repo != last_repo:
                self._text.insert(
                    tk.END,
                    "─" * 120 + "\n",
                    "separator",
                )
            last_repo = repo
            self._render_pr_row(pr)
        self._text.insert(tk.END, "\n")

    def _render_pr_row(self, pr: dict[str, Any]) -> None:
        url = pr.get("html_url", "")
        number = pr.get("number", "")
        title = pr.get("title", "")
        repo = _repo_from_url(pr.get("repository_url", ""))
        age = _age_str(pr.get("created_at", ""))
        draft = pr.get("draft", False)
        is_queued = url in self._queued_urls
        is_dismissed = url in self._dismissed
        is_priority = url in self._priority

        self._text.insert(tk.END, f"{age:>4} ", "age")

        # Priority star toggle
        def _make_toggle_priority(u: str = url) -> None:
            self._toggle_priority(u)

        star_btn = tk.Button(
            self._text,
            text="★" if is_priority else "☆",
            command=_make_toggle_priority,
            bg=BG_OUTPUT,
            fg=COLOR_NOTIFICATION_BELL if is_priority else FG_DIM,
            font=self._font_body,
            relief=tk.FLAT,
            activebackground=COLOR_BUTTON_ACTIVE,
            cursor="hand2",
            padx=1,
            pady=0,
            borderwidth=0,
        )
        self._text.window_create(tk.END, window=star_btn)

        if is_dismissed:

            def _make_restore(u: str = url) -> None:
                self._restore_pr(u)

            btn = tk.Button(
                self._text,
                text="+",
                command=_make_restore,
                bg=BG_OUTPUT,
                fg=COLOR_DECLINED,
                font=self._font_body,
                relief=tk.FLAT,
                activebackground=COLOR_BUTTON_ACTIVE,
                cursor="hand2",
                padx=1,
                pady=0,
                borderwidth=0,
            )
        else:

            def _make_dismiss(u: str = url) -> None:
                self._dismiss_pr(u)

            btn = tk.Button(
                self._text,
                text="×",
                command=_make_dismiss,
                bg=BG_OUTPUT,
                fg=FG_DIM,
                font=self._font_body,
                relief=tk.FLAT,
                activebackground=COLOR_BUTTON_ACTIVE,
                cursor="hand2",
                padx=1,
                pady=0,
                borderwidth=0,
            )
        self._text.window_create(tk.END, window=btn)

        review_count = self._review_counts.get(url)
        if review_count is not None:
            tag = "review_count" if review_count > 0 else "review_zero"
            self._text.insert(tk.END, f" ({review_count})", tag)

        incoming_cr = self._incoming_cr_counts.get(url)
        if incoming_cr is not None:
            tag = "review_count" if incoming_cr > 0 else "review_zero"
            self._text.insert(tk.END, f" ({incoming_cr})", tag)

        comment_count = pr.get("comments", 0)
        comment_tag = "review_count" if comment_count > 0 else "review_zero"
        self._text.insert(tk.END, f" [{comment_count}]", comment_tag)

        pr_text = f" {repo}  #{number} {title}"
        if draft:
            pr_text = f" {repo}  [draft] #{number} {title}"
        elif is_queued:
            pr_text = f" {repo}  [queued] #{number} {title}"
        link_tag = f"link_{id(pr)}"
        self._text.insert(tk.END, pr_text, link_tag)

        if is_dismissed:
            fg = COLOR_DECLINED
        elif draft or is_queued:
            fg = FG_DIM
        else:
            fg = COLOR_LINK
        self._text.tag_configure(link_tag, foreground=fg)

        def _open_pr(e: Any, u: str = url) -> None:
            webbrowser.open(u)

        self._text.tag_bind(link_tag, "<Button-1>", _open_pr)
        self._text.tag_bind(
            link_tag,
            "<Enter>",
            lambda e: self._text.configure(cursor="hand2"),
        )
        self._text.tag_bind(
            link_tag,
            "<Leave>",
            lambda e: self._text.configure(cursor="arrow"),
        )

        self._text.insert(tk.END, "\n")
        self._row_widgets[url] = btn

    def _dismiss_pr(self, url: str) -> None:
        self._dismissed.add(url)
        self._save_dismissed()
        self._render()

    def _restore_pr(self, url: str) -> None:
        self._dismissed.discard(url)
        self._save_dismissed()
        self._render()

    def _reset_dismissed(self) -> None:
        self._dismissed.clear()
        self._save_dismissed()
        self._render()

    def _load_dismissed(self) -> None:
        path = self._state_path / "dismissed_prs.json"
        if not path.exists():
            return
        try:
            with open(path) as f:
                self._dismissed = set(json.load(f))
        except (OSError, json.JSONDecodeError):
            pass

    def _save_dismissed(self) -> None:
        path = self._state_path / "dismissed_prs.json"
        try:
            atomic_write_json(path, sorted(self._dismissed))
        except OSError:
            pass

    def _toggle_priority(self, url: str) -> None:
        if url in self._priority:
            self._priority.discard(url)
        else:
            self._priority.add(url)
        self._save_priority()
        self._render()

    def _load_priority(self) -> None:
        path = self._state_path / "priority_prs.json"
        if not path.exists():
            return
        try:
            with open(path) as f:
                self._priority = set(json.load(f))
        except (OSError, json.JSONDecodeError):
            pass

    def _save_priority(self) -> None:
        path = self._state_path / "priority_prs.json"
        try:
            atomic_write_json(path, sorted(self._priority))
        except OSError:
            pass
