# Generated By: Claude Code (Claude Opus 5 (1M context))
"""Parse and edit ``actions.md`` — the PA's markdown task list.

The file stays plain markdown the PA writes by hand: ``#`` headings are
sections, ``-``/``*`` bullets are tasks, deeper-indented bullets are detail
lines on the task above them. A task is done when it carries an ``[x]``
checkbox; a bullet written without a checkbox at all is an open task, so
nothing the PA already wrote needs migrating.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path

from personal_assistant_dashboard.utils import atomic_write_text

_HEADING = re.compile(r"^(#{1,6})\s+(.*)$")
_BULLET = re.compile(r"^(\s*)([-*])\s+(?:\[([ xX])\]\s*)?(.*)$")
_MD_LINK = re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)")
_BARE_URL = re.compile(r"https?://[^\s<>)\]]+")
# A section heading is a due date when it starts with one. The PA marks
# today's section "YYYY-MM-DD (TODAY)"; the marker goes stale if the
# dashboard runs past midnight, so every decision reads the date instead.
_SECTION_DATE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\b")
TODAY_MARKER = "(TODAY)"


@dataclass
class Task:
    """One bullet in actions.md."""

    line: int  # 0-based index into the file's lines
    text: str  # bullet text, checkbox stripped
    done: bool
    section: str
    detail: list[str] = field(default_factory=list)

    @property
    def key(self) -> str:
        """Identity for new-task detection.

        Text only, deliberately: the PA reorganizes actions.md by due date,
        so a task moving from "2026-08-22" to "(TODAY)" to "Overdue" is the
        same task and must not re-alert.
        """
        return self.text.strip()


def parse_tasks(content: str) -> list[Task]:
    """Extract tasks from markdown, in file order."""
    tasks: list[Task] = []
    section = ""
    top_indent: int | None = None
    for i, line in enumerate(content.splitlines()):
        heading = _HEADING.match(line)
        if heading:
            section = heading.group(2).strip()
            top_indent = None
            continue
        bullet = _BULLET.match(line)
        if not bullet:
            continue
        indent = len(bullet.group(1))
        box = bullet.group(3)
        text = bullet.group(4).strip()
        if not text:
            continue
        if tasks and top_indent is not None and indent > top_indent:
            tasks[-1].detail.append(text)
            continue
        top_indent = indent
        tasks.append(
            Task(
                line=i,
                text=text,
                done=box is not None and box.lower() == "x",
                section=section,
            )
        )
    return tasks


def set_done(path: Path, task: Task, done: bool) -> bool:
    """Rewrite one bullet's checkbox in place.

    Returns False when the line no longer holds that task — the PA edited
    actions.md underneath us, and the caller should reparse instead of
    writing over someone else's change.
    """
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    if task.line >= len(lines):
        return False
    bullet = _BULLET.match(lines[task.line])
    if not bullet or bullet.group(4).strip() != task.text:
        return False
    indent, marker, text = bullet.group(1), bullet.group(2), bullet.group(4)
    box = "[x]" if done else "[ ]"
    lines[task.line] = f"{indent}{marker} {box} {text}"
    out = "\n".join(lines)
    if raw.endswith("\n"):
        out += "\n"
    atomic_write_text(path, out)
    return True


def split_links(text: str) -> list[tuple[str, str]]:
    """Split text into ``(display, url)`` chunks; url is "" for plain text.

    Handles both markdown links and bare URLs so a pasted demo recording
    is clickable without the PA having to wrap it.
    """
    parts: list[tuple[str, str]] = []
    pos = 0
    for match in _MD_LINK.finditer(text):
        parts.extend(_split_bare(text[pos : match.start()]))
        parts.append((match.group(1), match.group(2)))
        pos = match.end()
    parts.extend(_split_bare(text[pos:]))
    return [p for p in parts if p[0]]


def _split_bare(text: str) -> list[tuple[str, str]]:
    parts: list[tuple[str, str]] = []
    pos = 0
    for match in _BARE_URL.finditer(text):
        parts.append((text[pos : match.start()], ""))
        parts.append((match.group(0), match.group(0)))
        pos = match.end()
    parts.append((text[pos:], ""))
    return parts


def first_url(task: Task) -> str:
    """First link on a task, for the Console alert. "" when it has none."""
    for chunk in (task.text, *task.detail):
        for _display, url in split_links(chunk):
            if url:
                return url
    return ""


def parse_section_date(title: str) -> date | None:
    """Due date a heading names, or None when it is a named bucket.

    Reads the leading ``YYYY-MM-DD`` and ignores any ``(TODAY)`` marker.
    """
    match = _SECTION_DATE.match(title.strip())
    if not match:
        return None
    try:
        return date(int(match[1]), int(match[2]), int(match[3]))
    except ValueError:
        return None


def shift_business_day(day: date, step: int) -> date:
    """Move one business day in *step*'s direction, skipping Sat/Sun."""
    day += timedelta(days=step)
    while day.weekday() >= 5:
        day += timedelta(days=step)
    return day


def bump_target(section: str, direction: int, today: date) -> date | None:
    """Date a task should move to, or None when that arrow is disabled.

    Today is the floor in both directions: a named bucket ("Overdue",
    "Demos to watch") can only move down, and it lands on today.
    """
    current = parse_section_date(section)
    if direction > 0:
        if current is None or current < today:
            return today
        return shift_business_day(current, 1)
    if current is None or current <= today:
        return None
    return max(shift_business_day(current, -1), today)


def section_title(day: date, today: date) -> str:
    """Heading text for a date section, marking today's the way the PA does."""
    stamp = day.isoformat()
    return f"{stamp} {TODAY_MARKER}" if day == today else stamp


def move_task(path: Path, task: Task, target: date, *, today: date) -> bool:
    """Move a task (and its detail lines) into *target*'s date section.

    Creates the section in date order when it is missing, and drops the
    source section when moving empties a dated one. Returns False when the
    line no longer holds that task, same guard as :func:`set_done`.
    """
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    if task.line >= len(lines):
        return False
    bullet = _BULLET.match(lines[task.line])
    if not bullet or bullet.group(4).strip() != task.text:
        return False

    end = _block_end(lines, task.line)
    block = lines[task.line : end + 1]
    del lines[task.line : end + 1]
    _collapse_blanks_at(lines, task.line)
    _drop_empty_date_section(lines, task.section)
    _insert_block(lines, block, target, today)

    out = "\n".join(lines)
    if raw.endswith("\n"):
        out += "\n"
    atomic_write_text(path, out)
    return True


def _collapse_blanks_at(lines: list[str], index: int) -> None:
    """Squash a blank-line run left behind at *index* down to one.

    Only at the seam the move opened — the rest of the file keeps whatever
    spacing the PA gave it.
    """
    while 0 < index < len(lines) and not lines[index].strip():
        if lines[index - 1].strip():
            return
        del lines[index]


def _block_end(lines: list[str], start: int) -> int:
    """Index of the task's last detail line, or *start* when it has none."""
    bullet = _BULLET.match(lines[start])
    assert bullet is not None
    base = len(bullet.group(1))
    end = start
    for i in range(start + 1, len(lines)):
        deeper = _BULLET.match(lines[i])
        if deeper and len(deeper.group(1)) > base:
            end = i
        else:
            break
    return end


def _headings(lines: list[str]) -> list[tuple[int, int, str]]:
    """(line index, level, title) for every heading, in file order."""
    out = []
    for i, line in enumerate(lines):
        match = _HEADING.match(line)
        if match:
            out.append((i, len(match.group(1)), match.group(2).strip()))
    return out


def _section_span(lines: list[str], heading_index: int) -> tuple[int, int]:
    """Half-open line range holding a section's body."""
    for i in range(heading_index + 1, len(lines)):
        if _HEADING.match(lines[i]):
            return heading_index + 1, i
    return heading_index + 1, len(lines)


def _drop_empty_date_section(lines: list[str], title: str) -> None:
    """Remove a dated section left with no bullets.

    Named buckets stay: "Demos to watch" is structure the user maintains,
    not a by-product of a due date.
    """
    if parse_section_date(title) is None:
        return
    for index, _level, heading in _headings(lines):
        if heading != title:
            continue
        start, stop = _section_span(lines, index)
        if any(_BULLET.match(line) for line in lines[start:stop]):
            return
        del lines[index:stop]
        return


def _insert_block(
    lines: list[str], block: list[str], target: date, today: date
) -> None:
    """Append *block* to the target date's section, creating it if needed."""
    for index, _level, heading in _headings(lines):
        if parse_section_date(heading) != target:
            continue
        start, stop = _section_span(lines, index)
        at = stop
        while at > start and not lines[at - 1].strip():
            at -= 1
        lines[at:at] = block
        return
    _create_section(lines, block, target, today)


def _create_section(
    lines: list[str], block: list[str], target: date, today: date
) -> None:
    headings = _headings(lines)
    level = Counter(level for _i, level, _t in headings).most_common(1)
    prefix = "#" * (level[0][0] if level else 2)
    at = _new_section_index(lines, headings, target)

    new = [""] if at > 0 and lines[at - 1].strip() else []
    new += [f"{prefix} {section_title(target, today)}", ""]
    new += block
    if at < len(lines) and lines[at].strip():
        new.append("")
    lines[at:at] = new


def _new_section_index(
    lines: list[str], headings: list[tuple[int, int, str]], target: date
) -> int:
    """Line to insert a new date section at, keeping dates in order."""
    seen_date = False
    for index, _level, heading in headings:
        day = parse_section_date(heading)
        if day is not None:
            if day > target:
                return index
            seen_date = True
        elif seen_date:
            # First named bucket after the dates — "Unscheduled" and the
            # like sort below every due date.
            return index
    return len(lines)
