# Generated By: Claude Code (Claude Opus 4.6)
"""Poll Anthropic OAuth usage API for 5-hour quota utilization.

Reads the OAuth token from ~/.claude/.credentials.json and fetches
quota data from the usage API. Results are cached to disk with
exponential backoff on failures.
"""

import json
import logging
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

USAGE_API_URL = "https://api.anthropic.com/api/oauth/usage"
CREDENTIALS_FILE = Path.home() / ".claude" / ".credentials.json"
CACHE_DIR = Path.home() / ".claude" / "pa-dashboard-data"
CACHE_FILE = CACHE_DIR / "usage_cache.json"

CACHE_TTL_SECONDS = 120
MAX_COOLDOWN_SECONDS = 3600
STALE_FAILURE_SECONDS = 21600  # 6 hours

# Color thresholds (fraction 0.0-1.0)
THRESHOLD_MID = 0.6
THRESHOLD_HIGH = 0.9


@dataclass
class UsageInfo:
    """5-hour quota usage information."""

    utilization: float  # percentage, 0-100+
    resets_in: str  # compact duration, e.g. "3h4m"
    is_stale: bool  # True if serving cached data after a fetch failure


def format_duration(seconds: int) -> str:
    """Format seconds as compact duration, max 2 units."""
    seconds = max(0, int(seconds))
    days = seconds // 86400
    hours = (seconds % 86400) // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60

    parts: list[str] = []
    if days:
        parts.append(f"{days}d")
    if hours:
        parts.append(f"{hours}h")
    if minutes:
        parts.append(f"{minutes}m")
    if secs or not parts:
        parts.append(f"{secs}s")
    return "".join(parts[:2])


def _get_oauth_token() -> str | None:
    """Read OAuth access token from Claude credentials file."""
    try:
        data = json.loads(CREDENTIALS_FILE.read_text(encoding="utf-8"))
        token: str = data["claudeAiOauth"]["accessToken"]
        return token
    except (OSError, KeyError, json.JSONDecodeError) as e:
        logger.error("Failed to read OAuth token: %s", e)
        return None


def _fetch_usage() -> dict | None:
    """Fetch usage data from Anthropic OAuth API."""
    token = _get_oauth_token()
    if not token:
        return None

    req = urllib.request.Request(USAGE_API_URL)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("anthropic-beta", "oauth-2025-04-20")

    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            result: dict = json.loads(resp.read())
            return result
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode()[:200]
        except Exception:
            pass
        logger.error("HTTP %d %s: %s", e.code, e.reason, body)
        return None
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as e:
        logger.error("Usage fetch failed: %s: %s", type(e).__name__, e)
        return None


def _read_cache() -> dict | None:
    """Read cached usage data from disk."""
    if not CACHE_FILE.exists():
        return None
    try:
        cached: dict = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
        return cached
    except (json.JSONDecodeError, OSError):
        return None


def _write_cache(cache_dict: dict) -> None:
    """Write usage data to disk cache."""
    try:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        CACHE_FILE.write_text(json.dumps(cache_dict), encoding="utf-8")
    except OSError:
        pass


def _format_remaining(resets_at: str | None) -> str:
    """Parse resets_at ISO timestamp, return compact time remaining."""
    if not resets_at:
        return "5h"
    try:
        reset_dt = datetime.fromisoformat(resets_at)
        now = datetime.now(timezone.utc)
        remaining = int((reset_dt - now).total_seconds())
        if remaining <= 0:
            return "0s"
        return format_duration(remaining)
    except (ValueError, OverflowError):
        return "5h"


def get_usage() -> UsageInfo | None:
    """Get 5-hour quota usage, using cache with exponential backoff.

    Returns UsageInfo or None if no data is available.
    """
    now = time.time()
    cached = _read_cache()

    if cached:
        age = now - cached.get("last_success_at", 0)
        if age < CACHE_TTL_SECONDS:
            entry = cached.get("response_data", {}).get("five_hour", {})
            return UsageInfo(
                utilization=entry.get("utilization", 0),
                resets_in=_format_remaining(entry.get("resets_at")),
                is_stale=False,
            )

        # Check backoff cooldown
        failures = cached.get("consecutive_failures", 0)
        since_last = now - cached.get("last_attempt_at", 0)
        if failures > 0 and since_last >= STALE_FAILURE_SECONDS:
            failures = 0
        if failures > 0:
            cooldown = min(CACHE_TTL_SECONDS * (2**failures), MAX_COOLDOWN_SECONDS)
            if since_last < cooldown:
                entry = cached.get("response_data", {}).get("five_hour", {})
                return UsageInfo(
                    utilization=entry.get("utilization", 0),
                    resets_in=_format_remaining(entry.get("resets_at")),
                    is_stale=True,
                )

    result = _fetch_usage()

    if result is not None:
        _write_cache(
            {
                "response_data": result,
                "last_success_at": now,
                "last_attempt_at": now,
                "consecutive_failures": 0,
            }
        )
        entry = result.get("five_hour", {})
        return UsageInfo(
            utilization=entry.get("utilization", 0),
            resets_in=_format_remaining(entry.get("resets_at")),
            is_stale=False,
        )

    # Fetch failed — update backoff, serve stale
    if cached:
        cached["last_attempt_at"] = now
        cached["consecutive_failures"] = cached.get("consecutive_failures", 0) + 1
        _write_cache(cached)
        entry = cached.get("response_data", {}).get("five_hour", {})
        return UsageInfo(
            utilization=entry.get("utilization", 0),
            resets_in=_format_remaining(entry.get("resets_at")),
            is_stale=True,
        )

    return None
