# Generated By: Claude Code (Claude Opus 4.6)
"""Shared utility functions for personal assistant modules."""

from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from personal_assistant_dashboard.models import CalendarEvent


def run_cmd(
    cmd: list[str],
    *,
    cwd: str | Path | None = None,
    timeout: int | None = None,
    check: bool = False,
) -> subprocess.CompletedProcess[str]:
    """Run a subprocess with UTF-8 encoding and replacement for decode errors.

    All subprocess calls in this project should use this wrapper to avoid
    UnicodeDecodeError on Windows (cp1252 default can't handle all output).
    """
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        cwd=cwd,
        timeout=timeout,
        check=check,
    )


def format_event_time(time_str: str) -> str:
    """Format ISO datetime string to HH:MM.

    Returns empty string for date-only or missing values.
    """
    if not time_str or len(time_str) <= 10:
        return ""
    try:
        return datetime.fromisoformat(time_str).strftime("%H:%M")
    except ValueError:
        return time_str[:5]


def atomic_write_json(path: Path, data: Any, **json_kwargs: Any) -> None:
    """Write JSON data atomically using a temp file + os.replace().

    Prevents file corruption if the process is killed mid-write.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_path = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(data, f, **json_kwargs)
        os.replace(temp_path, path)
    except Exception:
        try:
            os.unlink(temp_path)
        except OSError:
            pass
        raise


def atomic_write_text(path: Path, content: str) -> None:
    """Write text atomically using a temp file + os.replace()."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_path = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(temp_path, path)
    except Exception:
        try:
            os.unlink(temp_path)
        except OSError:
            pass
        raise


_MEETING_URL_PATTERN = re.compile(
    r"https?://(?:meet\.google\.com/[a-z-]+"
    r"|teams\.microsoft\.com/l/meetup-join/[^\s\"]+"
    r"|[\w.]*zoom\.us/j/\d+[^\s\"]*)",
    re.IGNORECASE,
)


def get_meeting_url(event: CalendarEvent) -> str | None:
    """Extract a video conference URL from a calendar event.

    Checks hangout_link first, then falls back to regex-matching
    Meet/Teams/Zoom URLs in location and description fields.
    """
    hangout = event.get("hangout_link")
    if hangout:
        return hangout
    for field in ("location", "description"):
        text = event.get(field, "")
        if isinstance(text, str) and text:
            match = _MEETING_URL_PATTERN.search(text)
            if match:
                return match.group(0)
    return None


def filter_dismissed_missed_meetings(
    missed_meetings: list[CalendarEvent],
    dismissed_ids: set[str],
) -> list[CalendarEvent]:
    """Remove dismissed-conflict events from a missed-meetings list."""
    if not dismissed_ids or not missed_meetings:
        return missed_meetings
    return [e for e in missed_meetings if e.get("id", "") not in dismissed_ids]


_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def _first_sentence(text: str, max_len: int = 120) -> str:
    """Return the first sentence of text, flattened and truncated to max_len."""
    normalized = " ".join(text.split())
    if not normalized:
        return ""
    match = re.search(r"[.!?](?:\s|$)", normalized)
    first = normalized[: match.end()].strip() if match else normalized
    if len(first) > max_len:
        first = first[: max_len - 3].rstrip() + "..."
    return first


def list_local_skills(skills_dir: Path) -> list[tuple[str, str]]:
    """Return (name, first-sentence description) pairs for all SKILL.md files.

    Parses YAML frontmatter from each ``SKILL.md`` under ``skills_dir``. Skips
    files with missing/invalid frontmatter or without a name+description pair.
    Returns an empty list if ``skills_dir`` does not exist.
    """
    if not skills_dir.is_dir():
        return []
    results: list[tuple[str, str]] = []
    for skill_md in sorted(skills_dir.glob("**/SKILL.md")):
        try:
            content = skill_md.read_text(encoding="utf-8")
        except OSError:
            continue
        match = _FRONTMATTER_RE.match(content)
        if not match:
            continue
        try:
            data = yaml.safe_load(match.group(1))
        except yaml.YAMLError:
            continue
        if not isinstance(data, dict):
            continue
        name = str(data.get("name", "") or "").strip()
        desc = str(data.get("description", "") or "").strip()
        if not name or not desc:
            continue
        results.append((name, _first_sentence(desc)))
    return results
