# Generated By: Claude Code (Claude Opus 4.6)
"""Calendar collector — pulls events from Google Calendar via GWS CLI.

Writes normalized event data to the state repo as JSON files.
"""

from __future__ import annotations

import json
import logging
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from personal_assistant_dashboard.config import GWS_BINARY
from personal_assistant_dashboard.state_repo import DEFAULT_STATE_PATH
from personal_assistant_dashboard.models import CalendarEvent
from personal_assistant_dashboard.utils import atomic_write_json, run_cmd

logger = logging.getLogger(__name__)


def collect_events(
    calendar_id: str = "primary",
    *,
    days_ahead: int = 7,
    days_back: int = 0,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> list[CalendarEvent]:
    """Pull events from a calendar and write to the state repo.

    Args:
        calendar_id: Google Calendar ID ("primary" or an email address).
        days_ahead: How many days ahead to fetch.
        days_back: How many days in the past to fetch (0 = start of today).
        repo_path: Path to the state repo.

    Returns:
        List of normalized event dicts.
    """
    now = datetime.now(timezone.utc)
    # Start from beginning of today in LOCAL time (not UTC) to
    # include all events for the user's calendar day
    local_now = datetime.now().astimezone()
    start_of_local_today = local_now.replace(hour=0, minute=0, second=0, microsecond=0)
    time_min = (start_of_local_today - timedelta(days=days_back)).isoformat()
    time_max = (now + timedelta(days=days_ahead)).isoformat()

    logger.debug(
        "Querying %s: time_min=%s time_max=%s days_back=%d days_ahead=%d",
        calendar_id,
        time_min,
        time_max,
        days_back,
        days_ahead,
    )
    raw_events = _fetch_events(calendar_id, time_min=time_min, time_max=time_max)
    normalized = [_normalize_event(e) for e in raw_events]

    output_file = _output_path(calendar_id, repo_path=repo_path)
    atomic_write_json(output_file, normalized, indent=2, sort_keys=False)

    logger.info(
        "Collected %d events from %s -> %s",
        len(normalized),
        calendar_id,
        output_file,
    )
    return normalized


def collect_all_calendars(
    calendar_ids: list[str],
    *,
    days_ahead: int = 7,
    days_back: int = 0,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> dict[str, list[CalendarEvent]]:
    """Collect events from multiple calendars.

    Returns a dict mapping calendar_id to its event list.
    """
    results: dict[str, list[CalendarEvent]] = {}
    for cal_id in calendar_ids:
        try:
            results[cal_id] = collect_events(
                cal_id,
                days_ahead=days_ahead,
                days_back=days_back,
                repo_path=repo_path,
            )
        except CalendarCollectorError as exc:
            logger.error("Failed to collect %s: %s", cal_id, exc)
            results[cal_id] = []
    return results


def list_available_calendars() -> list[dict[str, str]]:
    """List all calendars available to the authenticated user.

    Returns a list of dicts with keys: id, summary, access_role, primary.
    Use this to discover calendar IDs for tracking config.
    """
    try:
        result = run_cmd(
            [
                GWS_BINARY,
                "calendar",
                "calendarList",
                "list",
                "--page-all",
            ],
            timeout=30,
        )
    except FileNotFoundError:
        raise CalendarCollectorError(f"GWS CLI binary not found: {GWS_BINARY}.")

    if result.returncode != 0:
        raise CalendarCollectorError(
            f"GWS CLI failed (exit {result.returncode}): " f"{result.stderr.strip()}"
        )

    calendars: list[dict[str, str]] = []
    for line in result.stdout.strip().splitlines():
        if not line.strip():
            continue
        try:
            page = json.loads(line)
        except json.JSONDecodeError:
            continue
        for item in page.get("items", []):
            calendars.append(
                {
                    "id": item.get("id", ""),
                    "summary": item.get("summary", "(unnamed)"),
                    "access_role": item.get("accessRole", ""),
                    "primary": "yes" if item.get("primary") else "no",
                }
            )
    return calendars


def format_calendar_list(calendars: list[dict[str, str]]) -> str:
    """Format available calendars as a human-readable table."""
    if not calendars:
        return "No calendars found."

    lines = [f"{'Primary':<9} {'Access':<8} {'Name':<40} ID"]
    lines.append("-" * 100)
    for cal in calendars:
        primary_marker = " *" if cal["primary"] == "yes" else ""
        lines.append(
            f"{cal['primary']:<9} {cal['access_role']:<8} "
            f"{cal['summary'][:40]:<40} {cal['id']}{primary_marker}"
        )
    return "\n".join(lines)


class CalendarCollectorError(Exception):
    """Raised when calendar collection fails."""


def _fetch_events(
    calendar_id: str,
    *,
    time_min: str,
    time_max: str,
) -> list[dict[str, Any]]:
    """Call GWS CLI to fetch calendar events."""
    params = json.dumps(
        {
            "calendarId": calendar_id,
            "timeMin": time_min,
            "timeMax": time_max,
            "singleEvents": True,
            "orderBy": "startTime",
        }
    )

    try:
        result = run_cmd(
            [GWS_BINARY, "calendar", "events", "list", "--params", params],
            timeout=30,
        )
    except FileNotFoundError:
        raise CalendarCollectorError(
            f"GWS CLI binary not found: {GWS_BINARY}. "
            "Install it or ensure it is on PATH."
        )
    except subprocess.TimeoutExpired:
        raise CalendarCollectorError("GWS CLI timed out fetching calendar events.")

    if result.returncode != 0:
        raise CalendarCollectorError(
            f"GWS CLI failed (exit {result.returncode}): {result.stderr.strip()}"
        )

    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise CalendarCollectorError(f"Failed to parse GWS CLI output: {exc}")

    items: list[dict[str, Any]] = data.get("items", [])
    return items


def _normalize_event(raw: dict[str, Any]) -> CalendarEvent:
    """Normalize a raw Google Calendar event to a consistent schema."""
    start = raw.get("start", {})
    end = raw.get("end", {})

    organizer = raw.get("organizer", {})
    attendees = raw.get("attendees", [])

    return {
        "id": raw.get("id", ""),
        "summary": raw.get("summary", "(no title)"),
        "start": start.get("dateTime") or start.get("date", ""),
        "end": end.get("dateTime") or end.get("date", ""),
        "all_day": "date" in start and "dateTime" not in start,
        "status": raw.get("status", "confirmed"),
        "organizer_email": organizer.get("email", ""),
        "organizer_self": organizer.get("self", False),
        "attendees": [
            {
                "email": a.get("email", ""),
                "response_status": a.get("responseStatus", "needsAction"),
                "self": a.get("self", False),
                "optional": a.get("optional", False),
            }
            for a in attendees
        ],
        "hangout_link": raw.get("hangoutLink"),
        "html_link": raw.get("htmlLink"),
        "event_type": raw.get("eventType", "default"),
        "recurring_event_id": raw.get("recurringEventId"),
        "description": raw.get("description", ""),
        "location": raw.get("location", ""),
        "attachments": [
            {
                "title": att.get("title", ""),
                "url": att.get("fileUrl", ""),
            }
            for att in raw.get("attachments", [])
        ],
    }


def _output_path(
    calendar_id: str,
    *,
    repo_path: Path,
) -> Path:
    """Determine the output file path for a calendar's events."""
    if calendar_id == "primary":
        return repo_path / "calendar" / "events.json"
    # Shared calendars get their own file, sanitized name
    safe_name = calendar_id.replace("@", "_at_").replace(".", "_")
    safe_name = Path(safe_name).name
    return repo_path / "calendar" / f"events-{safe_name}.json"
