# Generated By: Claude Code (Claude Opus 4.6)
"""Actions tab — surfaces calendar events needing user attention.

Displays alerts (e.g. meetings where all attendees declined) with
recommended actions like opening the event in Google Calendar.
"""

from __future__ import annotations

import tkinter as tk
import webbrowser
from typing import Any, Callable

from personal_assistant.analyzers.actions_analyzer import (
    DeclinedMeetingAlert,
    detect_declined_meetings,
)
from personal_assistant.config import (
    BG_OUTPUT,
    BG_WINDOW,
    FG_ACCENT,
    FG_DIM,
    FG_TEXT,
    FONT_BODY,
    FONT_HEADING,
    PAD,
)
from personal_assistant.utils import format_event_time

COLOR_ALERT_BG = "#3a3520"  # muted amber background for alert rows
COLOR_ALERT_FG = "#e5c07b"  # amber text
COLOR_ALERT_SELECTED = "#4a4530"  # slightly lighter for selection
COLOR_BTN = "#4e4e4e"


class ActionsTab:
    """Actions tab for the PA dashboard."""

    def __init__(
        self,
        parent: tk.Frame,
        events_source: Callable[[], list[dict[str, Any]]],
    ):
        self._parent = parent
        self._events_source = events_source
        self._alerts: list[DeclinedMeetingAlert] = []
        self._build()

    def _build(self) -> None:
        # Header bar
        header = tk.Frame(self._parent, bg=BG_WINDOW)
        header.pack(fill=tk.X, padx=PAD, pady=(PAD, 0))

        tk.Label(
            header,
            text="Actions",
            bg=BG_WINDOW,
            fg=FG_ACCENT,
            font=FONT_HEADING,
        ).pack(side=tk.LEFT)

        self._count_label = tk.Label(
            header,
            text="",
            bg=BG_WINDOW,
            fg=COLOR_ALERT_FG,
            font=FONT_BODY,
        )
        self._count_label.pack(side=tk.LEFT, padx=(8, 0))

        tk.Button(
            header,
            text="Refresh",
            command=self.refresh,
            bg=COLOR_BTN,
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground="#5e5e5e",
            cursor="hand2",
            padx=12,
        ).pack(side=tk.RIGHT)

        # Alert list area
        self._list_frame = tk.Frame(self._parent, bg=BG_WINDOW)
        self._list_frame.pack(fill=tk.BOTH, expand=True, padx=PAD, pady=PAD)

        # Scrollable canvas for alert cards
        self._list_canvas = tk.Canvas(
            self._list_frame,
            bg=BG_OUTPUT,
            highlightthickness=0,
            borderwidth=0,
        )
        self._scrollbar = tk.Scrollbar(
            self._list_frame, command=self._list_canvas.yview
        )
        self._scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self._list_canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        self._list_canvas.configure(yscrollcommand=self._scrollbar.set)

        self._cards_frame = tk.Frame(self._list_canvas, bg=BG_OUTPUT)
        self._cards_window = self._list_canvas.create_window(
            (0, 0), window=self._cards_frame, anchor=tk.NW
        )

        self._cards_frame.bind("<Configure>", self._on_cards_configure)
        self._list_canvas.bind("<Configure>", self._on_canvas_configure)

        # Scroll bindings
        self._list_canvas.bind("<MouseWheel>", self._on_scroll)
        self._list_canvas.bind("<Button-4>", self._on_scroll)
        self._list_canvas.bind("<Button-5>", self._on_scroll)

        # Empty state
        self._empty_label = tk.Label(
            self._cards_frame,
            text="No actions needed",
            bg=BG_OUTPUT,
            fg=FG_DIM,
            font=FONT_HEADING,
        )

    def _on_cards_configure(self, _event: Any) -> None:
        self._list_canvas.configure(scrollregion=self._list_canvas.bbox("all"))

    def _on_canvas_configure(self, event: Any) -> None:
        self._list_canvas.itemconfig(self._cards_window, width=event.width)

    def _on_scroll(self, event: Any) -> None:
        if event.num == 4 or getattr(event, "delta", 0) > 0:
            self._list_canvas.yview_scroll(-3, "units")
        elif event.num == 5 or getattr(event, "delta", 0) < 0:
            self._list_canvas.yview_scroll(3, "units")

    def refresh(self) -> None:
        """Re-scan events and rebuild the alert list."""
        events = self._events_source()
        self._alerts = detect_declined_meetings(events)
        self._render_alerts()

    def _render_alerts(self) -> None:
        """Rebuild the alert card list."""
        # Clear existing cards
        for widget in self._cards_frame.winfo_children():
            widget.destroy()

        if not self._alerts:
            self._count_label.configure(text="")
            self._empty_label = tk.Label(
                self._cards_frame,
                text="No actions needed",
                bg=BG_OUTPUT,
                fg=FG_DIM,
                font=FONT_HEADING,
                pady=40,
            )
            self._empty_label.pack(fill=tk.X)
            return

        count = len(self._alerts)
        self._count_label.configure(text=f"{count} alert{'s' if count != 1 else ''}")

        for alert in self._alerts:
            self._render_alert_card(alert)

    def _render_alert_card(self, alert: DeclinedMeetingAlert) -> None:
        """Render a single alert as a card in the list."""
        event = alert.event
        summary = event.get("summary", "(no title)")
        start = format_event_time(event.get("start", ""))
        end = format_event_time(event.get("end", ""))

        card = tk.Frame(
            self._cards_frame,
            bg=COLOR_ALERT_BG,
            padx=PAD,
            pady=PAD,
            highlightbackground="#5a5030",
            highlightthickness=1,
        )
        card.pack(fill=tk.X, pady=(0, 4))

        # Title row
        title_row = tk.Frame(card, bg=COLOR_ALERT_BG)
        title_row.pack(fill=tk.X)

        tk.Label(
            title_row,
            text=summary,
            bg=COLOR_ALERT_BG,
            fg=FG_TEXT,
            font=FONT_HEADING,
            anchor=tk.W,
        ).pack(side=tk.LEFT, fill=tk.X, expand=True)

        # Open in Calendar button
        html_link = event.get("html_link", "")
        if html_link:

            def _open_link(url: str = html_link) -> None:
                webbrowser.open(url)

            tk.Button(
                title_row,
                text="Open in Calendar",
                command=_open_link,
                bg=COLOR_BTN,
                fg=FG_TEXT,
                font=FONT_BODY,
                relief=tk.FLAT,
                activebackground="#5e5e5e",
                cursor="hand2",
                padx=8,
            ).pack(side=tk.RIGHT)

        # Info row
        info_row = tk.Frame(card, bg=COLOR_ALERT_BG)
        info_row.pack(fill=tk.X, pady=(4, 0))

        time_text = f"{start} - {end}" if start and end else ""
        if time_text:
            tk.Label(
                info_row,
                text=time_text,
                bg=COLOR_ALERT_BG,
                fg=FG_DIM,
                font=FONT_BODY,
                anchor=tk.W,
            ).pack(side=tk.LEFT, padx=(0, 16))

        # Status
        n = alert.total_attendees
        status_text = f"All {n} attendee{'s' if n != 1 else ''} declined"
        tk.Label(
            info_row,
            text=status_text,
            bg=COLOR_ALERT_BG,
            fg=COLOR_ALERT_FG,
            font=FONT_BODY,
            anchor=tk.W,
        ).pack(side=tk.LEFT, padx=(0, 16))

        # Role
        if alert.user_is_organizer:
            role_text = "You organized this"
        else:
            organizer = event.get("organizer_email", "unknown")
            role_text = f"Organized by {organizer}"
        tk.Label(
            info_row,
            text=role_text,
            bg=COLOR_ALERT_BG,
            fg=FG_DIM,
            font=FONT_BODY,
            anchor=tk.W,
        ).pack(side=tk.LEFT)

        # Detail row — declined attendee emails
        detail_row = tk.Frame(card, bg=COLOR_ALERT_BG)
        detail_row.pack(fill=tk.X, pady=(4, 0))

        declined_text = ", ".join(alert.declined_attendees)
        tk.Label(
            detail_row,
            text=f"Declined: {declined_text}",
            bg=COLOR_ALERT_BG,
            fg=FG_DIM,
            font=FONT_BODY,
            anchor=tk.W,
            wraplength=700,
            justify=tk.LEFT,
        ).pack(side=tk.LEFT, fill=tk.X)
