# Generated By: Claude Code (Claude Opus 4.6)
"""Chat tab — conversational interface to Claude via the Agent SDK."""

from __future__ import annotations

import logging
import time
import tkinter as tk
from datetime import datetime
from pathlib import Path
from typing import Any

from personal_assistant.models import ConsoleLogCallback, NotifyTabCallback
from personal_assistant.config import (
    ASSISTANT_DIR,
    BG_INPUT,
    BG_OUTPUT,
    BG_WINDOW,
    BORDER_COLOR,
    COLOR_ASSISTANT,
    COLOR_BUTTON,
    COLOR_BUTTON_ACTIVE,
    COLOR_ERROR,
    COLOR_STOP_BUTTON,
    COLOR_STOP_BUTTON_ACTIVE,
    FG_ACCENT,
    FG_DIM,
    FG_TEXT,
    FONT_BODY,
    FONT_INPUT,
    PAD,
)

logger = logging.getLogger(__name__)

CHAT_LOG_DIR = ASSISTANT_DIR / "scratch" / "chat-log"


class ChatTab:
    """Interactive chat tab backed by ClaudeSDKClient."""

    def __init__(
        self,
        parent: tk.Frame,
        root: tk.Tk,
        *,
        console_log: ConsoleLogCallback | None = None,
        notify_tab: NotifyTabCallback | None = None,
    ) -> None:
        self._parent = parent
        self._root = root
        self._console_log = console_log
        self._notify_tab = notify_tab
        self._client: Any = None
        self._streaming = False
        self._started = False
        self._assistant_active = False
        self._send_time = 0.0
        self._status_text = ""
        self._status_timer: str | None = None
        self._pending_messages: list[str] = []
        self._chat_log_path: Path | None = None
        self._current_response: list[str] = []
        self._destroying = False
        self._last_text_time = 0.0
        self._build()

    # -- UI ------------------------------------------------------------------

    def _build(self) -> None:
        # Message display area
        msg_frame = tk.Frame(self._parent, bg=BG_OUTPUT)
        msg_frame.pack(fill=tk.BOTH, expand=True, padx=PAD, pady=(PAD, 0))

        scrollbar = tk.Scrollbar(msg_frame)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        self._messages = tk.Text(
            msg_frame,
            bg=BG_OUTPUT,
            fg=FG_TEXT,
            font=FONT_BODY,
            wrap=tk.WORD,
            state=tk.DISABLED,
            borderwidth=0,
            highlightthickness=0,
            takefocus=0,
            padx=PAD,
            pady=PAD,
            yscrollcommand=scrollbar.set,
        )
        self._messages.pack(fill=tk.BOTH, expand=True)
        scrollbar.config(command=self._messages.yview)

        # Tags for message styling
        self._messages.tag_configure("user_name", foreground=FG_ACCENT, justify=tk.LEFT)
        self._messages.tag_configure("user_msg", foreground=FG_TEXT, justify=tk.LEFT)
        self._messages.tag_configure(
            "assistant_name", foreground=COLOR_ASSISTANT, justify=tk.LEFT
        )
        self._messages.tag_configure(
            "assistant_msg", foreground=FG_TEXT, justify=tk.LEFT
        )
        self._messages.tag_configure("thinking_msg", foreground=FG_DIM, justify=tk.LEFT)
        self._messages.tag_configure(
            "error_msg", foreground=COLOR_ERROR, justify=tk.LEFT
        )
        self._messages.tag_configure(
            "separator", foreground=BORDER_COLOR, justify=tk.CENTER
        )

        # Status label
        self._status_var = tk.StringVar(value="")
        self._status_label = tk.Label(
            self._parent,
            textvariable=self._status_var,
            bg=BG_WINDOW,
            fg=FG_DIM,
            font=FONT_BODY,
            anchor=tk.W,
        )
        self._status_label.pack(fill=tk.X, padx=PAD, pady=(0, 0))

        # Input bar
        input_bar = tk.Frame(self._parent, bg=BG_WINDOW)
        input_bar.pack(fill=tk.X, padx=PAD, pady=(0, PAD))

        self._input = tk.Text(
            input_bar,
            bg=BG_INPUT,
            fg=FG_TEXT,
            font=FONT_INPUT,
            wrap=tk.WORD,
            height=3,
            insertbackground=FG_TEXT,
            relief=tk.FLAT,
            borderwidth=0,
            highlightthickness=0,
            padx=PAD,
            pady=PAD,
        )
        self._input.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=(0, PAD))
        self._input.bind("<Return>", self._on_enter)
        self._input.bind("<Shift-Return>", lambda e: None)
        self._input.bind("<Control-BackSpace>", self._on_ctrl_backspace)

        btn_frame = tk.Frame(input_bar, bg=BG_WINDOW)
        btn_frame.pack(side=tk.RIGHT, fill=tk.Y, padx=(PAD, 0))

        self._send_btn = tk.Button(
            btn_frame,
            text="Send",
            command=self._send,
            bg=COLOR_BUTTON,
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground=COLOR_BUTTON_ACTIVE,
            cursor="hand2",
            padx=8,
        )
        self._send_btn.pack(side=tk.TOP, pady=(0, 4))

        tk.Button(
            btn_frame,
            text="Clear",
            command=self._clear,
            bg=COLOR_BUTTON,
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground=COLOR_BUTTON_ACTIVE,
            cursor="hand2",
            padx=8,
        ).pack(side=tk.TOP)

    # -- key bindings --------------------------------------------------------

    def _stop(self) -> None:
        """Interrupt the current response."""
        if self._client and self._streaming:
            self._client.interrupt()

    def _on_enter(self, event: tk.Event) -> str:  # type: ignore[type-arg]
        """Enter sends the message."""
        self._send()
        return "break"

    def _on_ctrl_backspace(self, event: tk.Event) -> str:  # type: ignore[type-arg]
        """Delete the word before the cursor."""
        self._input.delete("insert -1c wordstart", tk.INSERT)
        return "break"

    # -- send / receive ------------------------------------------------------

    def send_message(self, text: str) -> None:
        """Public API: send a message as if the user typed it."""
        if not text:
            return
        if self._streaming:
            self._pending_messages.append(text)
            self._status_text = f"Queued ({len(self._pending_messages)})"
            return
        self._append_user(text)
        self._send_now(text)

    def _send(self) -> None:
        """Send the current input text to Claude, or queue if busy."""
        text = self._input.get("1.0", tk.END).strip()
        if not text:
            return

        self._input.delete("1.0", tk.END)

        if self._streaming:
            self._pending_messages.append(text)
            self._status_text = f"Queued ({len(self._pending_messages)})"
            return

        self._append_user(text)
        self._send_now(text)

    def _send_now(self, text: str) -> None:
        """Send a message immediately."""
        self._streaming = True
        self._send_btn.config(
            text="Stop",
            command=self._stop,
            bg=COLOR_STOP_BUTTON,
            activebackground=COLOR_STOP_BUTTON_ACTIVE,
        )
        self._assistant_active = False

        self._send_time = time.monotonic()
        self._status_text = (
            "Connecting" if self._client is None else "Waiting for response"
        )
        self._start_status_timer()
        self._ensure_client()
        self._status_text = "Waiting for response"

        if self._client is None:
            self._on_error("Failed to initialize chat client")
            return
        self._client.send(text)

    def _ensure_client(self) -> None:
        """Lazily create and start the chat client."""
        if self._client is not None:
            return

        from personal_assistant.chat_client import ChatClient

        self._client = ChatClient(
            on_text=lambda t: self._schedule(self._on_text, t),
            on_tool_use=lambda t: self._schedule(self._on_tool_use, t),
            on_done=lambda: self._schedule(self._on_done),
            on_error=lambda e: self._schedule(self._on_error, e),
        )
        self._client.start()

    def _start_status_timer(self) -> None:
        """Start a 1-second timer to update the status with elapsed time."""
        self._tick_status()

    def _stop_status_timer(self) -> None:
        """Cancel the status timer."""
        if self._status_timer is not None:
            self._root.after_cancel(self._status_timer)
            self._status_timer = None

    def _tick_status(self) -> None:
        """Update status bar with current elapsed time."""
        if not self._streaming or self._destroying:
            return
        elapsed = self._format_duration(time.monotonic() - self._send_time)
        self._status_var.set(f"{self._status_text} ({elapsed})")
        self._status_timer = self._root.after(1000, self._tick_status)

    def _schedule(self, fn: Any, *args: Any) -> None:
        """Schedule a callback on the TkInter main thread."""
        if not self._destroying and self._root.winfo_exists():
            self._root.after(0, fn, *args)

    # -- UI callbacks (main thread only) -------------------------------------

    def _on_text(self, delta: str) -> None:
        """Append streaming text delta from Claude."""
        self._status_text = "Streaming"
        if not self._assistant_active:
            self._start_assistant()
        now = time.monotonic()
        gap = now - self._last_text_time if self._last_text_time else 0
        self._last_text_time = now
        try:
            self._messages.config(state=tk.NORMAL)
            if gap > 2.0 and self._current_response:
                self._messages.insert(tk.END, "\n", "assistant_msg")
            self._messages.insert(tk.END, delta, "assistant_msg")
            self._messages.config(state=tk.DISABLED)
            self._messages.see(tk.END)
        except tk.TclError:
            pass
        self._current_response.append(delta)

    def _on_tool_use(self, tool_name: str) -> None:
        """Update status bar with tool name."""
        self._status_text = f"Using {tool_name}"
        if not self._assistant_active:
            self._start_assistant()

    def _on_done(self) -> None:
        """Response complete."""
        self._streaming = False
        self._assistant_active = False
        self._send_btn.config(
            text="Send",
            command=self._send,
            bg=COLOR_BUTTON,
            activebackground=COLOR_BUTTON_ACTIVE,
        )
        self._stop_status_timer()
        if self._current_response:
            self._log_assistant("".join(self._current_response))
            self._current_response.clear()
        elapsed = time.monotonic() - self._send_time
        duration = self._format_duration(elapsed)
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, f"\n[success] {duration}\n\n", "thinking_msg")
            self._messages.config(state=tk.DISABLED)
            self._messages.see(tk.END)
        except tk.TclError:
            pass

        if self._pending_messages:
            next_msg = self._pending_messages.pop(0)
            self._append_user(next_msg)
            self._send_now(next_msg)
            return

        self._status_var.set("Ready")
        self._input.focus_set()
        if self._notify_tab:
            self._notify_tab("Chat")

    def _on_error(self, error: str) -> None:
        """Display error inline and re-enable input."""
        self._streaming = False
        self._assistant_active = False
        self._current_response.clear()
        self._send_btn.config(
            text="Send",
            command=self._send,
            bg=COLOR_BUTTON,
            activebackground=COLOR_BUTTON_ACTIVE,
        )
        self._stop_status_timer()
        elapsed = time.monotonic() - self._send_time
        duration = self._format_duration(elapsed)
        self._status_var.set("Error")
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(
                tk.END, f"\n[failure] {error} ({duration})\n\n", "error_msg"
            )
            self._messages.config(state=tk.DISABLED)
            self._messages.see(tk.END)
        except tk.TclError:
            pass
        self._input.focus_set()
        self._pending_messages.clear()
        if self._console_log:
            self._console_log(f"Chat error: {error}", "error", "", "")

    @staticmethod
    def _format_duration(seconds: float) -> str:
        """Format elapsed seconds as a human-readable duration."""
        total = int(seconds)
        if total < 60:
            return f"{total}s"
        minutes = total // 60
        secs = total % 60
        return f"{minutes}m {secs}s"

    # -- message formatting --------------------------------------------------

    def _append_user(self, text: str) -> None:
        """Insert a user message into the display."""
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, "You\n", "user_name")
            self._messages.insert(tk.END, text + "\n\n", "user_msg")
            self._messages.config(state=tk.DISABLED)
            self._messages.see(tk.END)
        except tk.TclError:
            pass
        self._log_user(text)

    def _start_assistant(self) -> None:
        """Insert the Claude label before streaming text."""
        self._assistant_active = True
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.insert(tk.END, "Claude\n", "assistant_name")
            self._messages.config(state=tk.DISABLED)
            self._messages.see(tk.END)
        except tk.TclError:
            pass

    # -- chat logging ----------------------------------------------------------

    def _ensure_chat_log(self) -> None:
        """Create a chat log file for this session if one doesn't exist."""
        if self._chat_log_path is not None:
            return
        CHAT_LOG_DIR.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
        self._chat_log_path = CHAT_LOG_DIR / f"{timestamp}.md"

    def _log_user(self, text: str) -> None:
        """Append a user message to the chat log."""
        self._ensure_chat_log()
        if not self._chat_log_path:
            return
        try:
            with open(self._chat_log_path, "a") as f:
                f.write(f"## You\n{text}\n\n")
        except OSError as exc:
            logger.warning("failed to write chat log: %s", exc)

    def _log_assistant(self, text: str) -> None:
        """Append an assistant response to the chat log."""
        if not self._chat_log_path:
            return
        try:
            with open(self._chat_log_path, "a") as f:
                f.write(f"## Claude\n{text}\n\n")
        except OSError as exc:
            logger.warning("failed to write chat log: %s", exc)

    # -- clear / refresh -----------------------------------------------------

    def _clear(self) -> None:
        """Clear conversation history and display."""
        self._pending_messages.clear()
        self._chat_log_path = None
        try:
            self._messages.config(state=tk.NORMAL)
            self._messages.delete("1.0", tk.END)
            self._messages.config(state=tk.DISABLED)
        except tk.TclError:
            pass
        if self._client:
            self._client.clear()

    def refresh(self) -> None:
        """Called when the tab is activated."""
        self._input.focus_set()

    def on_destroy(self) -> None:
        """Called during dashboard shutdown to clean up resources."""
        self._destroying = True
        self._stop_status_timer()
        if self._client:
            self._client.stop()
