# Generated By: Claude Code (Claude Opus 4.6)
"""Configuration constants for the personal assistant GUI."""

import platform as _plat

# Fonts — negative sizes = pixels (DPI-independent)
if _plat.system() == "Windows":
    FONT_FAMILY = "Segoe UI"
else:
    FONT_FAMILY = "Noto Sans"

FONT_BODY = (FONT_FAMILY, -13)
FONT_HEADING = (FONT_FAMILY, -15, "bold")
FONT_INPUT = (FONT_FAMILY, -14)

# Colors — dark theme
BG_WINDOW = "#1e1e1e"
BG_INPUT = "#2d2d2d"
BG_OUTPUT = "#252525"
FG_TEXT = "#cccccc"
FG_DIM = "#888888"
FG_ACCENT = "#569cd6"
BORDER_COLOR = "#3c3c3c"

# Layout
WINDOW_WIDTH = 700
WINDOW_HEIGHT = 500
PAD = 8
