# Generated By: Claude Code (Claude Opus 4.6)
"""Tracking configuration manager for the personal assistant.

Manages tracking.yaml in the state repo — what Jira epics, GitHub repos,
and calendars the PA monitors.
"""

import logging
from pathlib import Path
from typing import Any

import yaml

from personal_assistant.state_repo import DEFAULT_STATE_PATH

logger = logging.getLogger(__name__)

_CONFIG_REL_PATH = "config/tracking.yaml"


def _config_path(repo_path: Path) -> Path:
    return repo_path / _CONFIG_REL_PATH


def _empty_config() -> dict[str, Any]:
    return {
        "jira": [],
        "github": {"repos": []},
        "calendars": ["primary"],
    }


def load_config(
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> dict[str, Any]:
    """Load tracking config from the state repo.

    Returns a default config if the file doesn't exist yet.
    """
    config_file = _config_path(repo_path)
    if not config_file.exists():
        return _empty_config()

    with open(config_file) as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict):
        return _empty_config()
    return data


def save_config(
    config: dict[str, Any],
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> None:
    """Write tracking config to the state repo."""
    config_file = _config_path(repo_path)
    config_file.parent.mkdir(parents=True, exist_ok=True)

    with open(config_file, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    logger.info("Saved tracking config to %s", config_file)


def add_jira_tracking(
    key: str,
    *,
    tier: str = "awareness",
    repo_path: Path = DEFAULT_STATE_PATH,
) -> None:
    """Add a Jira epic to track.

    Args:
        key: Jira issue key (e.g., "ANSTRAT-1900")
        tier: "awareness" (summary only) or "active" (full depth)
    """
    if tier not in ("awareness", "active"):
        raise ValueError(f"Invalid tier: {tier!r}. Must be 'awareness' or 'active'.")

    config = load_config(repo_path=repo_path)
    jira_entries = config.setdefault("jira", [])

    for entry in jira_entries:
        if entry.get("key") == key:
            entry["tier"] = tier
            logger.info("Updated %s to tier=%s", key, tier)
            save_config(config, repo_path=repo_path)
            return

    jira_entries.append({"key": key, "tier": tier})
    logger.info("Added Jira tracking: %s (tier=%s)", key, tier)
    save_config(config, repo_path=repo_path)


def remove_jira_tracking(
    key: str,
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> bool:
    """Remove a Jira epic from tracking. Returns True if found and removed."""
    config = load_config(repo_path=repo_path)
    jira_entries = config.get("jira", [])
    original_len = len(jira_entries)
    config["jira"] = [e for e in jira_entries if e.get("key") != key]

    if len(config["jira"]) < original_len:
        save_config(config, repo_path=repo_path)
        logger.info("Removed Jira tracking: %s", key)
        return True
    return False


def add_github_repo(
    repo: str,
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> None:
    """Add a GitHub repo to track (format: owner/repo)."""
    config = load_config(repo_path=repo_path)
    github = config.setdefault("github", {"repos": []})
    repos = github.setdefault("repos", [])

    if repo not in repos:
        repos.append(repo)
        save_config(config, repo_path=repo_path)
        logger.info("Added GitHub repo: %s", repo)


def remove_github_repo(
    repo: str,
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> bool:
    """Remove a GitHub repo from tracking. Returns True if found."""
    config = load_config(repo_path=repo_path)
    repos = config.get("github", {}).get("repos", [])
    if repo in repos:
        repos.remove(repo)
        save_config(config, repo_path=repo_path)
        logger.info("Removed GitHub repo: %s", repo)
        return True
    return False


def add_calendar(
    calendar_id: str,
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> None:
    """Add a calendar to monitor."""
    config = load_config(repo_path=repo_path)
    calendars = config.setdefault("calendars", [])

    if calendar_id not in calendars:
        calendars.append(calendar_id)
        save_config(config, repo_path=repo_path)
        logger.info("Added calendar: %s", calendar_id)


def remove_calendar(
    calendar_id: str,
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> bool:
    """Remove a calendar from monitoring. Returns True if found."""
    config = load_config(repo_path=repo_path)
    calendars = config.get("calendars", [])
    if calendar_id in calendars:
        calendars.remove(calendar_id)
        save_config(config, repo_path=repo_path)
        logger.info("Removed calendar: %s", calendar_id)
        return True
    return False


def format_tracking_list(
    *,
    repo_path: Path = DEFAULT_STATE_PATH,
) -> str:
    """Format the current tracking config as a human-readable string."""
    config = load_config(repo_path=repo_path)
    lines: list[str] = []

    jira_entries = config.get("jira", [])
    if jira_entries:
        lines.append("Jira:")
        for entry in jira_entries:
            lines.append(f"  {entry['key']:20s} ({entry.get('tier', 'awareness')})")
    else:
        lines.append("Jira: (none)")

    repos = config.get("github", {}).get("repos", [])
    if repos:
        lines.append("GitHub repos:")
        for repo in repos:
            lines.append(f"  {repo}")
    else:
        lines.append("GitHub repos: (none)")

    calendars = config.get("calendars", [])
    if calendars:
        lines.append("Calendars:")
        for cal in calendars:
            lines.append(f"  {cal}")
    else:
        lines.append("Calendars: (none)")

    return "\n".join(lines)
