# Generated By: Claude Code (Claude Opus 4.6)
"""Calendar dashboard — Canvas-based single-day calendar view with navigation.

Follows TkInter standards: hidden root, composition over inheritance,
lazy window build, winfo_exists() safety.
"""

from __future__ import annotations

import json
import logging
import threading
import tkinter as tk
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Callable

from personal_assistant.config import (
    BG_OUTPUT,
    BG_WINDOW,
    BORDER_COLOR,
    FG_ACCENT,
    FG_DIM,
    FG_TEXT,
    FONT_BODY,
    FONT_HEADING,
    PAD,
)
from personal_assistant.state_repo import DEFAULT_STATE_PATH

logger = logging.getLogger(__name__)

# Colors
COLOR_CONFLICT = "#e06c75"
COLOR_CONFLICT_BG = "#3d2020"
COLOR_NORMAL = "#61afef"
COLOR_NORMAL_BG = "#1e2a3a"
COLOR_ONEONE = "#d19a66"
COLOR_ONEONE_BG = "#2e2418"
COLOR_CHANGE_NEW = "#98c379"
COLOR_CHANGE_CANCELLED = "#e5c07b"
COLOR_CHANGE_MOVED = "#61afef"
COLOR_SECTION_HEADER = "#c678dd"
COLOR_GRID_LINE = "#2a2a2a"
COLOR_HOUR_TEXT = "#5c6370"
COLOR_NOW_LINE = "#e06c75"
COLOR_NAV_BTN = "#4e4e4e"

# Layout
HOUR_HEIGHT = 60
MIN_BLOCK_HEIGHT = 22  # Minimum pixels for a readable event block
TIME_LABEL_WIDTH = 50
EVENT_LEFT_MARGIN = 55
EVENT_RIGHT_MARGIN = 15
WORK_DAY_START = 7
WORK_DAY_END = 18


class Dashboard:
    """Calendar dashboard — single-day view with date navigation."""

    def __init__(
        self,
        root: tk.Tk,
        *,
        state_path: Path = DEFAULT_STATE_PATH,
        on_quit: Callable[[], None] | None = None,
    ):
        self._root = root
        self._state_path = state_path
        self._on_quit = on_quit or root.quit
        self._window: tk.Toplevel | None = None
        self._canvas: tk.Canvas | None = None
        self._canvas_container: tk.Frame | None = None
        self._scrollbar: tk.Scrollbar | None = None
        self._changes_text: tk.Text | None = None
        self._calendar_frame: tk.Frame | None = None
        self._status_var = tk.StringVar(value="Starting...")
        self._date_var = tk.StringVar()
        self._current_date: date = date.today()
        self._all_events: list[dict[str, Any]] = []
        self._all_conflicts: list[Any] = []
        self._all_changes: list[Any] = []

    def show(self) -> None:
        if self._window and self._window.winfo_exists():
            self._window.deiconify()
            self._window.lift()
            return
        self._build()

    def hide(self) -> None:
        if self._window and self._window.winfo_exists():
            self._window.withdraw()

    @property
    def is_visible(self) -> bool:
        return bool(
            self._window
            and self._window.winfo_exists()
            and self._window.winfo_viewable()
        )

    def _build(self) -> None:
        self._window = tk.Toplevel(self._root)
        self._window.title("PA — Calendar Dashboard")
        self._window.geometry("900x700")
        self._window.configure(bg=BG_WINDOW)
        self._window.protocol("WM_DELETE_WINDOW", self._on_quit)
        self._window.minsize(width=600, height=400)

        main = tk.Frame(self._window, bg=BG_WINDOW)
        main.pack(fill=tk.BOTH, expand=True, padx=PAD, pady=PAD)

        # Top bar: nav + legend + refresh
        top_bar = tk.Frame(main, bg=BG_WINDOW)
        top_bar.pack(fill=tk.X, pady=(0, PAD))

        # Date navigation: < date >
        nav = tk.Frame(top_bar, bg=BG_WINDOW)
        nav.pack(side=tk.LEFT)

        tk.Button(
            nav,
            text="\u25c0",
            command=self._prev_day,
            bg=COLOR_NAV_BTN,
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground="#5e5e5e",
            cursor="hand2",
            padx=8,
        ).pack(side=tk.LEFT)

        self._date_label = tk.Label(
            nav,
            textvariable=self._date_var,
            bg=BG_WINDOW,
            fg=FG_ACCENT,
            font=FONT_HEADING,
            padx=12,
        )
        self._date_label.pack(side=tk.LEFT)
        self._date_label.bind("<Button-1>", lambda e: self._go_today())

        tk.Button(
            nav,
            text="\u25b6",
            command=self._next_day,
            bg=COLOR_NAV_BTN,
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground="#5e5e5e",
            cursor="hand2",
            padx=8,
        ).pack(side=tk.LEFT)

        tk.Button(
            nav,
            text="Today",
            command=self._go_today,
            bg=COLOR_NAV_BTN,
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground="#5e5e5e",
            cursor="hand2",
            padx=8,
        ).pack(side=tk.LEFT, padx=(8, 0))

        # Refresh button
        tk.Button(
            top_bar,
            text="Refresh",
            command=self.refresh,
            bg=COLOR_NAV_BTN,
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground="#5e5e5e",
            cursor="hand2",
            padx=12,
        ).pack(side=tk.RIGHT)

        # Legend
        # (legend moved to bottom bar)

        # Changes bar (only shown when there are changes)
        self._changes_text = tk.Text(
            main,
            bg=BG_OUTPUT,
            fg=FG_TEXT,
            font=FONT_BODY,
            wrap=tk.WORD,
            relief=tk.FLAT,
            height=2,
            padx=PAD,
            pady=4,
            state=tk.DISABLED,
            cursor="arrow",
            highlightthickness=0,
            borderwidth=0,
        )
        self._changes_text.tag_configure("new", foreground=COLOR_CHANGE_NEW)
        self._changes_text.tag_configure("cancelled", foreground=COLOR_CHANGE_CANCELLED)
        self._changes_text.tag_configure("moved", foreground=COLOR_CHANGE_MOVED)

        # Calendar area
        self._calendar_frame = tk.Frame(main, bg=BG_WINDOW)
        self._calendar_frame.pack(fill=tk.BOTH, expand=True)

        # Canvas + scrollbar (persistent, redrawn on nav)
        self._canvas_container = tk.Frame(self._calendar_frame, bg=BORDER_COLOR)
        self._canvas_container.pack(fill=tk.BOTH, expand=True)

        self._canvas = tk.Canvas(
            self._canvas_container,
            bg=BG_OUTPUT,
            highlightthickness=0,
            borderwidth=0,
        )
        self._canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        self._scrollbar = tk.Scrollbar(
            self._canvas_container, command=self._canvas.yview
        )
        self._scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self._canvas.configure(yscrollcommand=self._scrollbar.set)

        # Scroll bindings
        self._canvas.bind("<MouseWheel>", self._on_scroll)
        self._canvas.bind("<Button-4>", self._on_scroll)
        self._canvas.bind("<Button-5>", self._on_scroll)

        # Bottom bar: legend + status
        bottom = tk.Frame(main, bg=BG_WINDOW)
        bottom.pack(fill=tk.X, pady=(PAD, 0))

        # Legend (left side)
        legend = tk.Frame(bottom, bg=BG_WINDOW)
        legend.pack(side=tk.LEFT)
        for label_text, color in [
            ("conflict", COLOR_CONFLICT),
            ("1:1", COLOR_ONEONE),
            ("meeting", COLOR_NORMAL),
        ]:
            swatch = tk.Frame(legend, bg=color, width=10, height=10)
            swatch.pack(side=tk.LEFT, padx=(0, 2))
            swatch.pack_propagate(False)
            tk.Label(
                legend,
                text=label_text,
                bg=BG_WINDOW,
                fg=FG_DIM,
                font=FONT_BODY,
            ).pack(side=tk.LEFT, padx=(0, 8))

        tk.Label(
            legend,
            text=(
                "\u2501\u2501 accepted   - - tentative"
                "   no border = no response"
                "   (2/5) = attendees"
            ),
            bg=BG_WINDOW,
            fg=FG_DIM,
            font=FONT_BODY,
        ).pack(side=tk.LEFT, padx=(8, 0))

        # Status (right side)
        tk.Label(
            bottom,
            textvariable=self._status_var,
            bg=BG_WINDOW,
            fg=FG_DIM,
            font=FONT_BODY,
            anchor=tk.E,
        ).pack(side=tk.RIGHT)

        # Keyboard nav
        self._window.bind("<Left>", lambda e: self._prev_day())
        self._window.bind("<Right>", lambda e: self._next_day())

        self._update_date_label()

    def _on_scroll(self, event: Any) -> None:
        if not self._canvas:
            return
        if event.num == 4 or getattr(event, "delta", 0) > 0:
            self._canvas.yview_scroll(-3, "units")
        elif event.num == 5 or getattr(event, "delta", 0) < 0:
            self._canvas.yview_scroll(3, "units")

    def _prev_day(self) -> None:
        self._current_date -= timedelta(days=1)
        self._update_date_label()
        self._render_current_day()

    def _next_day(self) -> None:
        self._current_date += timedelta(days=1)
        self._update_date_label()
        self._render_current_day()

    def _go_today(self) -> None:
        self._current_date = date.today()
        self._update_date_label()
        self._render_current_day()

    def _update_date_label(self) -> None:
        today = date.today()
        if self._current_date == today:
            prefix = "Today — "
        elif self._current_date == today + timedelta(days=1):
            prefix = "Tomorrow — "
        elif self._current_date == today - timedelta(days=1):
            prefix = "Yesterday — "
        else:
            prefix = ""
        self._date_var.set(f"{prefix}{self._current_date.strftime('%A, %B %d')}")

    def refresh(self) -> None:
        self._status_var.set("Collecting...")
        thread = threading.Thread(
            target=self._do_refresh,
            daemon=True,
            name="dashboard-refresh",
        )
        thread.start()

    def _do_refresh(self) -> None:
        try:
            from personal_assistant.collectors.calendar_collector import (
                collect_all_calendars,
            )
            from personal_assistant.analyzers.calendar_analyzer import (
                analyze_all_calendars,
            )
            from personal_assistant.config_manager import load_config
            from personal_assistant.state_repo import init_repo

            init_repo(path=self._state_path)

            config = load_config(repo_path=self._state_path)
            calendar_ids = config.get("calendars", ["primary"])
            self._root.after(
                0,
                self._status_var.set,
                f"Collecting from {len(calendar_ids)} calendar(s)...",
            )
            collect_all_calendars(calendar_ids, repo_path=self._state_path)

            self._root.after(0, self._status_var.set, "Analyzing...")
            analyses = analyze_all_calendars(repo_path=self._state_path)

            # Load all events from state files
            all_events: list[dict[str, Any]] = []
            for analysis in analyses:
                abs_path = self._state_path / analysis.calendar_file
                if abs_path.exists():
                    try:
                        with open(abs_path) as f:
                            all_events.extend(json.load(f))
                    except (json.JSONDecodeError, OSError):
                        pass

            all_conflicts: list[Any] = []
            all_changes: list[Any] = []
            for analysis in analyses:
                all_conflicts.extend(analysis.conflicts)
                all_changes.extend(analysis.changes)

            self._root.after(
                0,
                self._on_data_loaded,
                all_events,
                all_conflicts,
                all_changes,
            )

        except Exception as exc:
            logger.exception("Dashboard refresh failed")
            self._root.after(0, self._status_var.set, f"Error: {exc}")

    def _on_data_loaded(
        self,
        events: list[dict[str, Any]],
        conflicts: list[Any],
        changes: list[Any],
    ) -> None:
        self._all_events = events
        self._all_conflicts = conflicts
        self._all_changes = changes
        self._render_changes()
        self._render_current_day()
        timestamp = datetime.now().strftime("%H:%M:%S")
        self._status_var.set(f"Updated at {timestamp}")

    def _render_changes(self) -> None:
        if not self._changes_text or not self._changes_text.winfo_exists():
            return

        self._changes_text.configure(state=tk.NORMAL)
        self._changes_text.delete("1.0", tk.END)

        if not self._all_changes:
            self._changes_text.pack_forget()
            self._changes_text.configure(state=tk.DISABLED)
            return

        if self._calendar_frame:
            self._changes_text.pack(
                fill=tk.X,
                pady=(0, PAD),
                before=self._calendar_frame,
            )
        else:
            self._changes_text.pack(fill=tk.X, pady=(0, PAD))

        for change in self._all_changes:
            if change.change_type == "new":
                self._changes_text.insert(
                    tk.END,
                    f"+ {change.event['summary']} "
                    f"at {_format_time(change.event['start'])}  ",
                    "new",
                )
            elif change.change_type == "cancelled":
                self._changes_text.insert(
                    tk.END,
                    f"- {change.event['summary']}  ",
                    "cancelled",
                )
            elif change.change_type == "time_changed":
                prev = _format_time(change.previous_event["start"])
                new_t = _format_time(change.event["start"])
                self._changes_text.insert(
                    tk.END,
                    f"~ {change.event['summary']} " f"{prev}->{new_t}  ",
                    "moved",
                )
            elif change.change_type == "attendees_changed":
                self._changes_text.insert(
                    tk.END,
                    f"~ {change.event['summary']} attendees  ",
                    "moved",
                )

        self._changes_text.configure(state=tk.DISABLED)

    def _render_current_day(self) -> None:
        if not self._canvas or not self._canvas.winfo_exists():
            return

        self._canvas.delete("all")

        date_str = self._current_date.strftime("%Y-%m-%d")
        day_events = _filter_events_for_date(self._all_events, date_str)

        now = datetime.now().astimezone()
        is_today = self._current_date == date.today()

        # True conflicts: only when BOTH events are accepted
        conflict_ids: set[str] = set()
        events_by_id = {e.get("id", ""): e for e in day_events}
        for c in self._all_conflicts:
            a_id = c.event_a["id"]
            b_id = c.event_b["id"]
            a_evt = events_by_id.get(a_id)
            b_evt = events_by_id.get(b_id)
            if not a_evt or not b_evt:
                continue
            a_status = _user_response_status(a_evt)
            b_status = _user_response_status(b_evt)
            if a_status == "accepted" and b_status == "accepted":
                conflict_ids.add(a_id)
                conflict_ids.add(b_id)

        # Time range
        earliest, latest = _day_time_range(day_events)
        total_hours = latest - earliest
        canvas_height = max(total_hours * HOUR_HEIGHT + 20, 200)

        self._canvas.configure(scrollregion=(0, 0, 2000, canvas_height))

        # Hour grid
        for hour in range(earliest, latest + 1):
            y = (hour - earliest) * HOUR_HEIGHT
            self._canvas.create_line(
                TIME_LABEL_WIDTH,
                y,
                2000,
                y,
                fill=COLOR_GRID_LINE,
            )
            self._canvas.create_text(
                TIME_LABEL_WIDTH - 5,
                y + 2,
                text=f"{hour:02d}:00",
                fill=COLOR_HOUR_TEXT,
                font=FONT_BODY,
                anchor=tk.NE,
            )

        # "Now" line
        if is_today:
            now_hour = now.hour + now.minute / 60
            if earliest <= now_hour <= latest:
                now_y = (now_hour - earliest) * HOUR_HEIGHT
                self._canvas.create_line(
                    TIME_LABEL_WIDTH,
                    now_y,
                    2000,
                    now_y,
                    fill=COLOR_NOW_LINE,
                    width=2,
                    dash=(4, 2),
                )
                self._canvas.create_text(
                    TIME_LABEL_WIDTH - 5,
                    now_y,
                    text=now.strftime("%H:%M"),
                    fill=COLOR_NOW_LINE,
                    font=FONT_BODY,
                    anchor=tk.NE,
                )

        # Layout and draw events
        positioned = _layout_events(day_events, earliest)

        self._canvas.update_idletasks()
        canvas_width = self._canvas.winfo_width() or 800
        available_width = canvas_width - EVENT_LEFT_MARGIN - EVENT_RIGHT_MARGIN

        for pos in positioned:
            event = pos["event"]
            y1 = pos["y"]
            y2 = pos["y2"]
            col = pos["col"]
            num_cols = pos["num_cols"]

            col_width = available_width / max(num_cols, 1)
            x1 = EVENT_LEFT_MARGIN + col * col_width + 1
            x2 = x1 + col_width - 2

            # Enforce minimum block height for readability
            block_height = y2 - y1
            if block_height < MIN_BLOCK_HEIGHT:
                y2 = y1 + MIN_BLOCK_HEIGHT
                block_height = MIN_BLOCK_HEIGHT

            event_id = event.get("id", "")
            is_conflict = event_id in conflict_ids
            is_oneone = _is_one_on_one(event)
            response = _user_response_status(event)

            if is_conflict:
                fill, outline, text_color = (
                    COLOR_CONFLICT_BG,
                    COLOR_CONFLICT,
                    COLOR_CONFLICT,
                )
            elif is_oneone:
                fill, outline, text_color = (
                    COLOR_ONEONE_BG,
                    COLOR_ONEONE,
                    COLOR_ONEONE,
                )
            else:
                fill, outline, text_color = (
                    COLOR_NORMAL_BG,
                    COLOR_NORMAL,
                    COLOR_NORMAL,
                )

            # Border style encodes response status
            if response == "accepted":
                self._canvas.create_rectangle(
                    x1,
                    y1,
                    x2,
                    y2,
                    fill=fill,
                    outline=outline,
                    width=2,
                )
            elif response == "tentative":
                self._canvas.create_rectangle(
                    x1,
                    y1,
                    x2,
                    y2,
                    fill=fill,
                    outline=outline,
                    width=2,
                    dash=(6, 4),
                )
            else:
                # No response — no border, just fill
                self._canvas.create_rectangle(
                    x1,
                    y1,
                    x2,
                    y2,
                    fill=fill,
                    outline="",
                    width=0,
                )

            summary = event.get("summary", "")
            start_t = _format_time(event["start"])
            attendee_info = _attendee_count(event)

            # Build label: "HH:MM Title (accepted/total)"
            label = f"{start_t} {summary}"
            if attendee_info:
                label += f" {attendee_info}"

            # Right-side: ownership on conflicts
            right_text = ""
            if is_conflict:
                right_text = _ownership_tag(event)

            text_width = x2 - x1 - 8

            # Consistent single-line format for all events
            self._canvas.create_text(
                x1 + 4,
                y1 + 4,
                text=label,
                fill=text_color,
                font=FONT_BODY,
                anchor=tk.NW,
                width=text_width,
            )
            if right_text:
                self._canvas.create_text(
                    x2 - 4,
                    y1 + 4,
                    text=right_text,
                    fill=FG_DIM,
                    font=FONT_BODY,
                    anchor=tk.NE,
                )

        # No events message
        if not day_events:
            self._canvas.create_text(
                400,
                100,
                text="No events",
                fill=FG_DIM,
                font=FONT_HEADING,
                anchor=tk.CENTER,
            )

        # Scroll to now or top
        if is_today and day_events:
            now_hour = now.hour + now.minute / 60
            if earliest <= now_hour <= latest:
                frac = max(
                    0,
                    (now_hour - earliest - 1) / total_hours,
                )
                self._canvas.yview_moveto(frac)
            else:
                self._canvas.yview_moveto(0)
        else:
            self._canvas.yview_moveto(0)


def _format_time(time_str: str) -> str:
    if not time_str or len(time_str) <= 10:
        return ""
    try:
        return datetime.fromisoformat(time_str).strftime("%H:%M")
    except ValueError:
        return time_str[:5]


def _ownership_tag(event: dict[str, Any]) -> str:
    if event.get("organizer_self"):
        return "[yours]"
    organizer = event.get("organizer_email", "")
    if organizer:
        return f"[{organizer.split('@')[0]}]"
    return ""


def _attendee_count(event: dict[str, Any]) -> str:
    """Format attendee count as (accepted/total) or (?) if unknown."""
    attendees = event.get("attendees", [])
    if not attendees:
        return ""
    total = len(attendees)
    accepted = sum(1 for a in attendees if a.get("response_status") == "accepted")
    return f"({accepted}/{total})"


def _user_response_status(event: dict[str, Any]) -> str:
    """Get the user's response status for this event."""
    user_att = next(
        (a for a in event.get("attendees", []) if a.get("self")),
        None,
    )
    if user_att:
        status: str = user_att.get("response_status", "needsAction")
        return status
    return "accepted"  # No attendees = likely user's own event


def _is_one_on_one(event: dict[str, Any]) -> bool:
    attendees = event.get("attendees", [])
    non_self = [a for a in attendees if not a.get("self")]
    if len(non_self) != 1:
        return False
    summary = event.get("summary", "").lower()
    return any(m in summary for m in ["1:1", "1 on 1", "1-on-1", "/"])


def _parse_hour(time_str: str) -> float:
    try:
        dt = datetime.fromisoformat(time_str)
        return dt.hour + dt.minute / 60
    except (ValueError, AttributeError):
        return 0


def _day_time_range(
    events: list[dict[str, Any]],
) -> tuple[int, int]:
    timed = [e for e in events if not e.get("all_day", False)]
    if not timed:
        return WORK_DAY_START, WORK_DAY_END

    earliest_h = min(_parse_hour(e["start"]) for e in timed)
    latest_h = max(_parse_hour(e["end"]) for e in timed)

    start = max(int(earliest_h) - 1, 0)
    end = min(int(latest_h) + 1, 24)
    return start, end


def _layout_events(
    events: list[dict[str, Any]],
    earliest_hour: int,
) -> list[dict[str, Any]]:
    timed = [
        e for e in events if not e.get("all_day", False) and _format_time(e["start"])
    ]
    timed.sort(key=lambda e: e["start"])

    if not timed:
        return []

    # Group overlapping events into clusters
    clusters: list[list[dict[str, Any]]] = []
    current_cluster: list[dict[str, Any]] = []
    cluster_end = 0.0

    for event in timed:
        start_h = _parse_hour(event["start"])
        end_h = _parse_hour(event["end"])

        if current_cluster and start_h < cluster_end:
            current_cluster.append(event)
            cluster_end = max(cluster_end, end_h)
        else:
            if current_cluster:
                clusters.append(current_cluster)
            current_cluster = [event]
            cluster_end = end_h

    if current_cluster:
        clusters.append(current_cluster)

    positioned: list[dict[str, Any]] = []
    for cluster in clusters:
        num_cols = len(cluster)
        for col, event in enumerate(cluster):
            start_h = _parse_hour(event["start"])
            end_h = _parse_hour(event["end"])
            y = (start_h - earliest_hour) * HOUR_HEIGHT
            y2 = (end_h - earliest_hour) * HOUR_HEIGHT
            positioned.append(
                {
                    "event": event,
                    "y": y,
                    "y2": y2,
                    "col": col,
                    "num_cols": num_cols,
                }
            )

    return positioned


def _filter_events_for_date(
    all_events: list[dict[str, Any]],
    date_str: str,
) -> list[dict[str, Any]]:
    """Filter events for a specific date, excluding declined and work location."""
    day_events = []
    for event in all_events:
        start = event.get("start", "")
        if date_str not in start:
            continue
        user_att = next(
            (a for a in event.get("attendees", []) if a.get("self")),
            None,
        )
        if user_att and user_att.get("response_status") == "declined":
            continue
        if event.get("event_type") == "workingLocation":
            continue
        day_events.append(event)

    day_events.sort(key=lambda e: e.get("start", ""))
    return day_events
