# Generated By: Claude Code (Claude Opus 4.6)
"""Main GUI window — text/voice input, Claude response output."""

from __future__ import annotations

import tkinter as tk
from typing import TYPE_CHECKING

from personal_assistant.config import (
    BG_INPUT,
    BG_OUTPUT,
    BG_WINDOW,
    BORDER_COLOR,
    FG_ACCENT,
    FG_DIM,
    FG_TEXT,
    FONT_BODY,
    FONT_HEADING,
    FONT_INPUT,
    PAD,
    WINDOW_HEIGHT,
    WINDOW_WIDTH,
)

if TYPE_CHECKING:
    from personal_assistant.controller import AppController


class MainWindow:
    """Primary interaction window — composition over inheritance."""

    def __init__(self, root: tk.Tk, controller: AppController):
        self._root = root
        self._controller = controller
        self._window: tk.Toplevel | None = None
        self._output_text: tk.Text | None = None
        self._input_var = tk.StringVar()
        self._status_var = tk.StringVar(value="Ready")
        self._build()

    def _build(self) -> None:
        self._window = tk.Toplevel(self._root)
        self._window.title("Personal Assistant")
        self._window.geometry(f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}")
        self._window.configure(bg=BG_WINDOW)
        self._window.protocol("WM_DELETE_WINDOW", self._controller.quit)
        self._window.minsize(width=400, height=300)

        # Main container
        main = tk.Frame(self._window, bg=BG_WINDOW)
        main.pack(fill=tk.BOTH, expand=True, padx=PAD, pady=PAD)

        # Header
        tk.Label(
            main,
            text="Personal Assistant",
            bg=BG_WINDOW,
            fg=FG_ACCENT,
            font=FONT_HEADING,
            anchor=tk.W,
        ).pack(fill=tk.X, pady=(0, PAD))

        # Output area
        output_frame = tk.Frame(main, bg=BORDER_COLOR)
        output_frame.pack(fill=tk.BOTH, expand=True, pady=(0, PAD))

        self._output_text = tk.Text(
            output_frame,
            bg=BG_OUTPUT,
            fg=FG_TEXT,
            font=FONT_BODY,
            wrap=tk.WORD,
            relief=tk.FLAT,
            padx=PAD,
            pady=PAD,
            state=tk.DISABLED,
            cursor="arrow",
        )
        self._output_text.pack(fill=tk.BOTH, expand=True, padx=1, pady=1)

        # Scrollbar
        scrollbar = tk.Scrollbar(self._output_text, command=self._output_text.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self._output_text.configure(yscrollcommand=scrollbar.set)

        # Input row
        input_frame = tk.Frame(main, bg=BG_WINDOW)
        input_frame.pack(fill=tk.X, pady=(0, 4))

        self._input_entry = tk.Entry(
            input_frame,
            textvariable=self._input_var,
            bg=BG_INPUT,
            fg=FG_TEXT,
            font=FONT_INPUT,
            insertbackground=FG_TEXT,
            relief=tk.FLAT,
            bd=0,
        )
        self._input_entry.pack(
            side=tk.LEFT, fill=tk.X, expand=True, ipady=6, padx=(0, PAD)
        )
        self._input_entry.bind("<Return>", lambda e: self._on_send())
        self._input_entry.focus_set()

        send_btn = tk.Button(
            input_frame,
            text="Send",
            command=self._on_send,
            bg=FG_ACCENT,
            fg="#ffffff",
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground="#4a8ac4",
            activeforeground="#ffffff",
            cursor="hand2",
            padx=12,
        )
        send_btn.pack(side=tk.LEFT, padx=(0, PAD))

        voice_btn = tk.Button(
            input_frame,
            text="Voice",
            command=self._on_voice,
            bg="#4e4e4e",
            fg=FG_TEXT,
            font=FONT_BODY,
            relief=tk.FLAT,
            activebackground="#5e5e5e",
            activeforeground="#ffffff",
            cursor="hand2",
            padx=12,
        )
        voice_btn.pack(side=tk.LEFT)

        # Status bar
        tk.Label(
            main,
            textvariable=self._status_var,
            bg=BG_WINDOW,
            fg=FG_DIM,
            font=FONT_BODY,
            anchor=tk.W,
        ).pack(fill=tk.X)

    def _on_send(self) -> None:
        prompt = self._input_var.get().strip()
        if not prompt:
            return
        self._input_var.set("")
        self._append_output(f"> {prompt}\n", tag="user")
        self._set_status("Thinking...")
        self._controller.send_prompt(prompt)

    def _on_voice(self) -> None:
        self._set_status("Recording... press Done in voice window")
        self._controller.start_voice()

    def append_response(self, text: str) -> None:
        """Append Claude's response to the output area."""
        self._append_output(f"{text}\n\n", tag="response")
        self._set_status("Ready")

    def append_user_input(self, text: str) -> None:
        """Append transcribed voice input to the output area."""
        self._append_output(f"> {text}\n", tag="user")

    def _append_output(self, text: str, *, tag: str = "") -> None:
        if self._output_text is None:
            return
        self._output_text.configure(state=tk.NORMAL)
        self._output_text.insert(tk.END, text)
        self._output_text.configure(state=tk.DISABLED)
        self._output_text.see(tk.END)

    def _set_status(self, text: str) -> None:
        self._status_var.set(text)

    def show(self) -> None:
        if self._window:
            self._window.deiconify()
            self._window.lift()

    def hide(self) -> None:
        if self._window:
            self._window.withdraw()
