# Generated By: Claude Code (Claude Opus 4.6)
"""Transcripts tab — enrichment and summarization pipeline UI.

Runs enrichment + summarization automatically on a timer. Displays meeting
transcript status and provides a console log of pipeline activity.

Library contracts:
  meet_enrich: MeetingFolder fields (concluded, has_artifacts, artifact_sources)
               populated by scan_meeting_folders(). No direct file reads.
  meet_summarize: is_completed()/is_failed() from state module.
                  has_summary()/get_summary() from summary module.
"""

from __future__ import annotations

import logging
import subprocess
import threading
import tkinter as tk
from tkinter import ttk
from queue import Empty, SimpleQueue
from typing import Any

from personal_assistant.models import ConsoleLogCallback
from personal_assistant.config import (
    BG_OUTPUT,
    BG_WINDOW,
    COLOR_ACTIVE,
    COLOR_BUTTON,
    COLOR_BUTTON_ACTIVE,
    COLOR_FAILED,
    COLOR_MENU_ACTIVE_BG,
    COLOR_MENU_ACTIVE_FG,
    COLOR_MENU_BG,
    COLOR_MENU_FG,
    COLOR_PENDING,
    COLOR_SUCCESS,
    COLOR_TAB_BG,
    FG_DIM,
    FG_TEXT,
    FONT_NAME_BODY,
    MAX_CONCURRENT_SUMMARIZATION,
    MENU_TIMEOUT_MS,
    PAD,
    PIPELINE_INTERVAL_MS,
    POLL_INTERVAL_MS,
)

logger = logging.getLogger(__name__)

# Map artifact kind values from meet-enrich DB to display names
ARTIFACT_DISPLAY_NAMES: dict[str, str] = {
    "recording": "Recording",
    "transcript": "Transcript",
    "calendar_attachment": "Attachment",
    "closed_caption": "CC",
    "chat": "Chat",
}


class MeetingsTab:
    """Transcripts tab for the PA dashboard.

    Automatically runs enrichment + summarization on a timer.
    """

    def __init__(
        self,
        parent: tk.Frame,
        root: tk.Tk,
        *,
        console_log: ConsoleLogCallback | None = None,
    ) -> None:
        self._parent = parent
        self._root = root
        self._console_log = console_log
        self._update_countdown_cb: Any = None  # Set by dashboard
        self._set_run_now_state_cb: Any = None  # Set by dashboard
        self._update_summarize_status_cb: Any = None  # Set by dashboard
        self._summarize_total: int = 0
        self._summarize_done: int = 0
        self._event_queue: SimpleQueue[tuple[str, Any]] = SimpleQueue()
        self._cc: Any = None  # ConcurrencyControl, lazy import
        self._running = False
        self._enrich_running = False
        self._summarize_running = False
        self._poll_id: str | None = None
        self._timer_id: str | None = None
        self._context_menu: tk.Menu | None = None
        self._menu_timer: str | None = None
        # _log_frame removed — all output goes to Console tab
        # Cache folder objects for context menu actions and filtering
        self._folders_by_key: dict[str, Any] = {}
        self._all_folders: list[Any] = []
        self._sum_state: dict = {}
        self._countdown_id: str | None = None
        self._next_run: float = 0
        self._build()
        # Run pipeline immediately on launch, then schedule recurring
        self._root.after(1000, self._auto_pipeline)

    def _build(self) -> None:
        # Control bar
        controls = tk.Frame(self._parent, bg=BG_WINDOW)
        controls.pack(fill=tk.X, padx=PAD, pady=(PAD, 0))

        # Search
        self._search_var = tk.StringVar()
        self._search_var.trace_add("write", lambda *_: self._apply_filter())
        search_entry = tk.Entry(
            controls,
            textvariable=self._search_var,
            bg=BG_OUTPUT,
            fg=FG_TEXT,
            font=FONT_NAME_BODY,
            insertbackground=FG_TEXT,
            width=20,
        )
        search_entry.pack(side=tk.LEFT, padx=(0, PAD))

        # Filters
        filter_frame = tk.Frame(controls, bg=BG_WINDOW)
        filter_frame.pack(side=tk.LEFT)

        def _make_filter(
            parent: tk.Frame, label: str, values: list[str]
        ) -> tk.StringVar:
            tk.Label(
                parent, text=label, bg=BG_WINDOW, fg=FG_DIM, font=FONT_NAME_BODY
            ).pack(side=tk.LEFT, padx=(0, 2))
            var = tk.StringVar(value=values[0])
            menu = tk.OptionMenu(
                parent,
                var,
                *values,
                command=lambda _: self._apply_filter(),
            )
            menu.configure(
                bg=COLOR_BUTTON,
                fg=FG_TEXT,
                font=FONT_NAME_BODY,
                activebackground=COLOR_BUTTON_ACTIVE,
                highlightthickness=0,
                relief=tk.FLAT,
            )
            menu.pack(side=tk.LEFT, padx=(0, PAD))
            return var

        self._filter_concluded = _make_filter(
            filter_frame, "Concluded:", ["All", "Yes", "No"]
        )
        self._filter_summary = _make_filter(
            filter_frame, "Summary:", ["All", "Yes", "No"]
        )

        # Right side: count + Refresh
        btn_frame = tk.Frame(controls, bg=BG_WINDOW)
        btn_frame.pack(side=tk.RIGHT)

        self._count_var = tk.StringVar(value="")
        tk.Label(
            btn_frame,
            textvariable=self._count_var,
            bg=BG_WINDOW,
            fg=FG_DIM,
            font=FONT_NAME_BODY,
        ).pack(side=tk.LEFT, padx=(0, PAD))

        tk.Button(
            btn_frame,
            text="Refresh",
            command=self.refresh,
            bg=COLOR_BUTTON,
            fg=FG_TEXT,
            font=FONT_NAME_BODY,
            relief=tk.FLAT,
            activebackground=COLOR_BUTTON_ACTIVE,
            cursor="hand2",
            padx=8,
        ).pack(side=tk.LEFT, padx=2)

        # Meeting list (Treeview)
        tree_frame = tk.Frame(self._parent, bg=BG_WINDOW)
        tree_frame.pack(fill=tk.BOTH, expand=True, padx=PAD, pady=(PAD, 0))

        style = ttk.Style()
        style.configure(
            "Meetings.Treeview",
            background=BG_OUTPUT,
            foreground=FG_TEXT,
            fieldbackground=BG_OUTPUT,
            font=FONT_NAME_BODY,
            rowheight=24,
        )
        style.configure(
            "Meetings.Treeview.Heading",
            background=COLOR_TAB_BG,
            foreground=FG_TEXT,
            font=FONT_NAME_BODY,
        )

        columns = ("date", "name", "concluded", "summarized", "sources")
        self._tree = ttk.Treeview(
            tree_frame,
            columns=columns,
            show="headings",
            style="Meetings.Treeview",
            selectmode="browse",
        )

        self._tree.heading("date", text="Date")
        self._tree.heading("name", text="Meeting")
        self._tree.heading("concluded", text="Concluded")
        self._tree.heading("summarized", text="Summary")
        self._tree.heading("sources", text="Sources")

        self._tree.column("date", width=90, minwidth=80)
        self._tree.column("name", width=300, minwidth=150)
        self._tree.column("concluded", width=80, minwidth=70, anchor=tk.CENTER)
        self._tree.column("summarized", width=70, minwidth=50, anchor=tk.CENTER)
        self._tree.column("sources", width=200, minwidth=100)

        tree_scroll = tk.Scrollbar(tree_frame, command=self._tree.yview)
        tree_scroll.pack(side=tk.RIGHT, fill=tk.Y)
        self._tree.configure(yscrollcommand=tree_scroll.set)
        self._tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        # Right-click context menu
        self._tree.bind("<Button-3>", self._on_tree_right_click)

        # Tag colors
        self._tree.tag_configure("success", foreground=COLOR_SUCCESS)
        self._tree.tag_configure("pending", foreground=COLOR_PENDING)
        self._tree.tag_configure("failed", foreground=COLOR_FAILED)
        self._tree.tag_configure("active", foreground=COLOR_ACTIVE)

        # No local log area — all output goes to the Console tab

    # --- Auto-pipeline timer ---

    def _schedule_pipeline(self) -> None:
        """Schedule the next pipeline run and start countdown."""
        import time

        self._next_run = time.time() + PIPELINE_INTERVAL_MS / 1000
        self._timer_id = self._root.after(PIPELINE_INTERVAL_MS, self._auto_pipeline)
        self._update_countdown()

    def _update_countdown(self) -> None:
        """Update the countdown display every second."""
        import time

        remaining = max(0, int(self._next_run - time.time()))
        minutes, seconds = divmod(remaining, 60)
        self._log_countdown(f"Next meeting enrichment in {minutes}:{seconds:02d}")
        if remaining > 0:
            self._countdown_id = self._root.after(1000, self._update_countdown)
        else:
            self._countdown_id = None

    def _log_countdown(self, text: str) -> None:
        """Update countdown text in the console tab."""
        if self._update_countdown_cb is not None:
            try:
                self._root.after(0, self._update_countdown_cb, text)
            except Exception:
                pass

    def force_pipeline(self) -> None:
        """Force an immediate pipeline run, resetting the timer."""
        if self._timer_id is not None:
            self._root.after_cancel(self._timer_id)
            self._timer_id = None
        if self._countdown_id is not None:
            self._root.after_cancel(self._countdown_id)
            self._countdown_id = None
        self._auto_pipeline()

    def _auto_pipeline(self) -> None:
        """Timer callback: run enrichment + summarization if not already running."""
        if not self._running:
            self._run_pipeline()
        else:
            # Already running — schedule next check
            self._schedule_pipeline()

    def _run_pipeline(self) -> None:
        """Run enrichment then summarization in background."""
        if self._running:
            return
        self._running = True
        self._enrich_running = True
        # Cancel countdown during run
        if self._countdown_id is not None:
            self._root.after_cancel(self._countdown_id)
            self._countdown_id = None
        self._log_countdown("Meeting enrichment running...")
        self._log("[Enrichment] starting meeting enrichment...", "progress")
        # Notify dashboard to disable Run Now
        if self._set_run_now_state_cb is not None:
            self._root.after(0, self._set_run_now_state_cb, False)
        self._start_polling()

        thread = threading.Thread(
            target=self._do_pipeline,
            daemon=True,
            name="meetings-pipeline",
        )
        thread.start()

    def _do_pipeline(self) -> None:
        """Background: enrich then summarize."""
        # Suppress verbose logging from meet-enrich and meet-summarize
        for mod in ("meet_enrich", "meet_summarize"):
            logging.getLogger(mod).setLevel(logging.WARNING)

        try:
            # Phase 1: Enrichment
            from meet_enrich.enricher import run_enrichment

            summary = run_enrichment()

            # Concise enrichment summary
            new_folders = summary.get("folders_created", 0)
            downloaded = summary.get("files_downloaded", 0)
            if new_folders or downloaded:
                mtg = "meeting" if new_folders == 1 else "meetings"
                fl = "file" if downloaded == 1 else "files"
                msg = (
                    f"[Enrichment] {new_folders} new {mtg},"
                    f" {downloaded} {fl} downloaded"
                )
                self._event_queue.put(("log", (msg, "success")))
            else:
                self._event_queue.put(
                    (
                        "log",
                        ("[Enrichment] no new data", "info"),
                    )
                )

            self._enrich_running = False

            # Phase 2: Summarization
            self._summarize_running = True
            from meet_summarize.scanner import scan_meetings, filter_actionable
            from meet_summarize.executor import (
                run_batch,
                BatchConfig,
                ConcurrencyControl,
            )
            from meet_summarize.state import load_state
            from meet_summarize.config import TRANSCRIPTS_ROOT, STATE_FILENAME

            state_path = TRANSCRIPTS_ROOT / STATE_FILENAME
            state = load_state(state_path)
            candidates = scan_meetings(TRANSCRIPTS_ROOT)
            actionable = filter_actionable(candidates, state)

            if not actionable:
                self._event_queue.put(
                    (
                        "log",
                        ("[Summarization] nothing to summarize", "info"),
                    )
                )
                self._event_queue.put(("pipeline_done", None))
                return

            count = len(actionable)
            mtg = "meeting" if count == 1 else "meetings"
            self._event_queue.put(
                (
                    "log",
                    (f"[Summarization] {count} {mtg} to process", "progress"),
                )
            )

            self._cc = ConcurrencyControl(MAX_CONCURRENT_SUMMARIZATION)

            def on_event(event: Any) -> None:
                self._event_queue.put(("summarize_event", event))

            config = BatchConfig(
                max_concurrent=MAX_CONCURRENT_SUMMARIZATION,
                on_event=on_event,
                concurrency_control=self._cc,
            )

            success, failure = run_batch(actionable, state, state_path, config=config)
            self._event_queue.put(("summarize_done", (success, failure)))
        except ImportError as exc:
            self._event_queue.put(
                (
                    "log",
                    (
                        f"Import error: {exc}. Install meet-enrich and meet-summarize.",
                        "error",
                    ),
                )
            )
            self._event_queue.put(("pipeline_done", None))
        except Exception as exc:
            logger.exception("Pipeline failed")
            self._event_queue.put(
                (
                    "log",
                    (f"Pipeline error: {exc}", "error"),
                )
            )
            self._event_queue.put(("pipeline_done", None))
        finally:
            self._enrich_running = False
            self._summarize_running = False
            self._cc = None
            # Restore logging levels
            for mod in ("meet_enrich", "meet_summarize"):
                logging.getLogger(mod).setLevel(logging.INFO)

    # --- Data scanning ---

    def refresh(self) -> None:
        """Scan the transcripts directory and populate the tree."""
        thread = threading.Thread(
            target=self._do_scan,
            daemon=True,
            name="meetings-scan",
        )
        thread.start()

    def _do_scan(self) -> None:
        """Background: scan meeting folders and load summarization state."""
        try:
            from meet_enrich.discovery import scan_meeting_folders
            from meet_enrich.config import TRANSCRIPTS_ROOT
            from meet_summarize.state import load_state
            from meet_summarize.config import (
                TRANSCRIPTS_ROOT as SUM_ROOT,
                STATE_FILENAME,
            )

            folders = scan_meeting_folders(transcripts_root=TRANSCRIPTS_ROOT)
            sum_state = load_state(SUM_ROOT / STATE_FILENAME)

            self._root.after(0, self._populate_tree, folders, sum_state)
        except ImportError as exc:
            self._root.after(
                0,
                self._log,
                f"Import error: {exc}. Install meet-enrich and meet-summarize.",
                "error",
            )
        except Exception as exc:
            logger.exception("Transcripts scan failed")
            self._root.after(0, self._log, f"Scan error: {exc}", "error")

    def _populate_tree(self, folders: list[Any], sum_state: dict) -> None:
        """Populate the Treeview from MeetingFolder objects and summarize state."""
        self._all_folders = folders
        self._sum_state = sum_state
        self._render_filtered_tree()

    def _apply_filter(self) -> None:
        """Re-render the tree with the current attendance filter."""
        self._render_filtered_tree()

    def _render_filtered_tree(self) -> None:
        """Render the tree with the current filter applied."""
        self._tree.delete(*self._tree.get_children())
        self._folders_by_key.clear()

        completed = self._sum_state.get("completed", {})
        failed = self._sum_state.get("failed", {})

        # Search text
        search = self._search_var.get().strip().lower()

        # Apply filters
        conc_filter = self._filter_concluded.get()
        sum_filter = self._filter_summary.get()

        folders_sorted = sorted(self._all_folders, key=lambda f: f.date, reverse=True)

        for folder in folders_sorted:
            folder_key = f"{folder.date}/{folder.name}"
            title = folder.meeting_title or folder.name

            # Search filter
            if search and search not in title.lower() and search not in folder.date:
                continue

            # Concluded filter
            if conc_filter == "Yes" and not folder.concluded:
                continue
            if conc_filter == "No" and folder.concluded:
                continue

            # Compute summary status for this folder
            if folder_key in completed:
                sum_status = "\u2713"
                tag = "success"
                has_sum = True
            elif folder_key in failed:
                sum_status = "\u2717"
                tag = "failed"
                has_sum = False
            else:
                sum_status = "-"
                tag = "pending"
                has_sum = False

            # Summary filter
            if sum_filter == "Yes" and not has_sum:
                continue
            if sum_filter == "No" and has_sum:
                continue

            self._folders_by_key[folder_key] = folder

            concluded_status = "\u2713" if folder.concluded else "-"

            # Sources from MeetingFolder.artifact_sources + filesystem flags
            sources: list[str] = []
            for kind in folder.artifact_sources:
                display = ARTIFACT_DISPLAY_NAMES.get(kind, kind)
                if display not in sources:
                    sources.append(display)
            if folder.has_closed_caption and "CC" not in sources:
                sources.append("CC")
            if folder.has_chat and "Chat" not in sources:
                sources.append("Chat")
            if folder.has_checkpoint_processed:
                sources.append("Checkpoints")

            self._tree.insert(
                "",
                tk.END,
                iid=folder_key,
                values=(
                    folder.date,
                    folder.meeting_title or folder.name,
                    concluded_status,
                    sum_status,
                    ", ".join(sources),
                ),
                tags=(tag,),
            )

        visible = len(self._tree.get_children())
        total = len(self._all_folders)
        if visible == total:
            self._count_var.set(f"{total}")
        else:
            self._count_var.set(f"{visible} / {total}")

    # --- Context menu ---

    def _dismiss_context_menu(self) -> None:
        """Destroy context menu and cancel timer."""
        if self._menu_timer:
            self._root.after_cancel(self._menu_timer)
            self._menu_timer = None
        if self._context_menu:
            try:
                self._context_menu.unpost()
                self._context_menu.destroy()
            except tk.TclError:
                pass
            self._context_menu = None

    def _on_tree_right_click(self, event: Any) -> None:
        """Show context menu for the selected meeting."""
        self._dismiss_context_menu()

        item = self._tree.identify_row(event.y)
        if not item:
            return
        self._tree.selection_set(item)

        # Check summary existence via meet-summarize API
        folder = self._folders_by_key.get(item)
        summary_exists = False
        if folder is not None:
            try:
                from meet_summarize.summary import has_summary

                summary_exists = has_summary(folder.path)
            except ImportError:
                pass

        menu = tk.Menu(
            self._parent,
            tearoff=0,
            bg=COLOR_MENU_BG,
            fg=COLOR_MENU_FG,
            activebackground=COLOR_MENU_ACTIVE_BG,
            activeforeground=COLOR_MENU_ACTIVE_FG,
        )
        self._context_menu = menu

        def open_folder() -> None:
            self._dismiss_context_menu()
            self._open_meeting_folder(item)

        def view_summary() -> None:
            self._dismiss_context_menu()
            self._view_summary(item)

        menu.add_command(label="Open Folder", command=open_folder)
        if summary_exists:
            menu.add_command(label="View Summary", command=view_summary)
        else:
            menu.add_command(label="View Summary", state=tk.DISABLED)

        try:
            menu.tk_popup(event.x_root, event.y_root)
        finally:
            menu.grab_release()

        self._menu_timer = self._root.after(MENU_TIMEOUT_MS, self._dismiss_context_menu)

    def _open_meeting_folder(self, folder_key: str) -> None:
        """Open the meeting folder in the file manager."""
        folder = self._folders_by_key.get(folder_key)
        if folder is None:
            return
        if folder.path.exists():
            subprocess.Popen(["xdg-open", str(folder.path)])

    def _view_summary(self, folder_key: str) -> None:
        """Show summary content in a popup."""
        folder = self._folders_by_key.get(folder_key)
        if folder is None:
            return

        try:
            from meet_summarize.summary import get_summary

            content = get_summary(folder.path)
        except ImportError:
            self._log("[Summarization] meet-summarize not installed", "error")
            return

        if content is None:
            self._log(f"[Summarization] no summary for {folder_key}", "info")
            return

        popup = tk.Toplevel(self._root)
        popup.title(f"Summary — {folder_key}")
        popup.configure(bg=BG_WINDOW)
        popup.geometry("700x500")

        text = tk.Text(
            popup,
            bg=BG_OUTPUT,
            fg=FG_TEXT,
            font=FONT_NAME_BODY,
            wrap=tk.WORD,
            padx=PAD,
            pady=PAD,
            highlightthickness=0,
        )
        scrollbar = tk.Scrollbar(popup, command=text.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        text.configure(yscrollcommand=scrollbar.set)
        text.pack(fill=tk.BOTH, expand=True)
        text.insert("1.0", content)
        text.configure(state=tk.DISABLED)

        popup.bind("<Escape>", lambda _: popup.destroy())

    # --- Controls ---

    def _set_idle(self) -> None:
        """Reset to idle state and schedule next run."""
        self._running = False
        self._enrich_running = False
        self._summarize_running = False
        self._cc = None
        # Re-enable Run Now
        if self._set_run_now_state_cb is not None:
            self._root.after(0, self._set_run_now_state_cb, True)
        # Schedule next pipeline run
        self._schedule_pipeline()

    # --- Event polling ---

    def _start_polling(self) -> None:
        """Start polling the event queue."""
        if self._poll_id is not None:
            return
        self._poll_events()

    def _poll_events(self) -> None:
        """Process events from the queue."""
        had_events = False
        try:
            while True:
                event_type, data = self._event_queue.get_nowait()
                self._handle_event(event_type, data)
                had_events = True
        except Empty:
            pass

        if (
            self._running
            or self._enrich_running
            or self._summarize_running
            or had_events
        ):
            self._poll_id = self._root.after(POLL_INTERVAL_MS, self._poll_events)
        else:
            self._poll_id = None

    def _handle_event(self, event_type: str, data: Any) -> None:
        """Handle a single event from the queue."""
        if event_type == "log":
            message, tag = data
            self._log(message, tag)
        elif event_type == "summarize_event":
            event_tuple = data
            kind = event_tuple[0] if event_tuple else ""
            if kind == "total":
                self._summarize_total = event_tuple[1] if len(event_tuple) > 1 else 0
                self._summarize_done = 0
                self._update_summarize_status()
            elif kind == "start":
                folder = event_tuple[1] if len(event_tuple) > 1 else ""
                self._log(f"[Summarization] summarizing {folder}...", "progress")
                self._update_tree_tag(folder, "active")
            elif kind == "success":
                folder = event_tuple[1] if len(event_tuple) > 1 else ""
                self._log(f"[Summarization] \u2713 {folder}", "success")
                self._update_tree_tag(folder, "success")
                self._update_tree_value(folder, "summarized", "\u2713")
                self._summarize_done += 1
                self._update_summarize_status()
            elif kind == "failure":
                folder = event_tuple[1] if len(event_tuple) > 1 else ""
                self._log(f"[Summarization] \u2717 {folder}", "error")
                self._update_tree_tag(folder, "failed")
                self._update_tree_value(folder, "summarized", "\u2717")
                self._summarize_done += 1
                self._update_summarize_status()
            elif kind == "cancelled":
                folder = event_tuple[1] if len(event_tuple) > 1 else ""
                self._log(f"[Summarization] cancelled {folder}", "info")
        elif event_type == "summarize_done":
            success, failure = data
            parts = []
            if success:
                parts.append(f"{success} summarized")
            if failure:
                parts.append(f"{failure} failed")
            if parts:
                self._log(
                    f"[Summarization] {', '.join(parts)}",
                    "success" if not failure else "warning",
                )
            else:
                self._log("[Summarization] complete", "success")
            self._summarize_total = 0
            self._summarize_done = 0
            self._update_summarize_status()
            self._set_idle()
            self.refresh()
        elif event_type == "pipeline_done":
            self._summarize_total = 0
            self._summarize_done = 0
            self._update_summarize_status()
            self._set_idle()
            self.refresh()

    # --- Filter state persistence ---

    def get_filter_state(self) -> dict[str, str]:
        """Return current filter values for state persistence."""
        return {
            "search": self._search_var.get(),
            "concluded": self._filter_concluded.get(),
            "summary": self._filter_summary.get(),
        }

    def set_filter_state(self, state: dict[str, str]) -> None:
        """Restore filter values from saved state."""
        if "search" in state:
            self._search_var.set(state["search"])
        if "concluded" in state:
            self._filter_concluded.set(state["concluded"])
        if "summary" in state:
            self._filter_summary.set(state["summary"])

    def _update_summarize_status(self) -> None:
        """Update the summarization count display in the Console tab."""
        if self._update_summarize_status_cb is None:
            return
        if self._summarize_total > 0:
            text = f"Summarizing: {self._summarize_done} / {self._summarize_total}"
        else:
            text = ""
        try:
            self._root.after(0, self._update_summarize_status_cb, text)
        except Exception:
            pass

    # --- Tree helpers ---

    def _update_tree_tag(self, folder_key: str, tag: str) -> None:
        """Update the tag (color) for a tree row."""
        if self._tree.exists(folder_key):
            self._tree.item(folder_key, tags=(tag,))

    def _update_tree_value(self, folder_key: str, column: str, value: str) -> None:
        """Update a single column value in the tree."""
        if not self._tree.exists(folder_key):
            return
        current = list(self._tree.item(folder_key, "values"))
        columns = ("date", "name", "concluded", "summarized", "sources")
        try:
            idx = columns.index(column)
            current[idx] = value
            self._tree.item(folder_key, values=current)
        except (ValueError, IndexError):
            pass

    # --- Logging ---

    def _log(self, message: str, tag: str = "info") -> None:
        """Forward message to the dashboard Console tab."""
        if self._console_log is not None:
            try:
                self._root.after(0, self._console_log, message, tag, "", "")
            except Exception:
                pass

    def on_destroy(self) -> None:
        """Called during dashboard shutdown to clean up resources."""
        if self._poll_id is not None:
            self._root.after_cancel(self._poll_id)
            self._poll_id = None
        if self._timer_id is not None:
            self._root.after_cancel(self._timer_id)
            self._timer_id = None
        if self._countdown_id is not None:
            self._root.after_cancel(self._countdown_id)
            self._countdown_id = None
        if self._menu_timer is not None:
            self._root.after_cancel(self._menu_timer)
            self._menu_timer = None
