# Generated By: Claude Code (Claude Opus 4.6)
# Optional target: start the PA dashboard with logging.
# PA_DIR is the working directory the dashboard operates in.
# Set via: make run PA_DIR=/path/to/dir

PA_DIR ?=
LOG_FILE := pa-dashboard.log

run: $(PYTHON)  ## Start the app (use DEBUG=1, PA_DIR=/path for working dir)
	@if [ -z "$(PA_DIR)" ]; then echo "ERROR: PA_DIR is required (e.g., make run PA_DIR=~/my-pa)"; exit 1; fi
	@if [ "$$(cd "$(PA_DIR)" 2>/dev/null && pwd)" = "$$(pwd)" ]; then echo "ERROR: PA_DIR must not be the project repo"; exit 1; fi
	@mkdir -p "$(PA_DIR)"
	@echo "Working dir: $(PA_DIR)"
	@echo "Logging to $(PA_DIR)/$(LOG_FILE)"
	cd "$(PA_DIR)" && "$(CURDIR)/$(PYTHON)" -m personal_assistant $(if $(DEBUG),--debug) gui --log-file $(LOG_FILE)
